### ISSUE TITLE
Agora appID is invalid error in react-native-ios android build works fine

### ISSUE THREAD

**Issue by StarkAndy** [syanbo/react-native-agora#101]
Hi ,
   Having problem when i am calling joiningChannel function in react-native for ios . Currently i am using agora 2.4.1-alpha.3 .its throw error 101 i checked what it is and in agora warning code its says App id invalid.

**Comment by Matrixbirds** [comment]
Pls check u did apply appId correctly and make sure u don’t set some token permission If u did enable token pls pass the valid token with joinChannel method

**Comment by StarkAndy** [comment]
Hi @Matrixbirds  i am not using the token i am using joinChannel function .

Below is my agora.js file.

`import React, { Component } from 'react';
import {
  StyleSheet,
  Text,
  View,
  TouchableOpacity,
  Dimensions,
  Modal,
  Platform,
  NativeModules,
  ActivityIndicator,
  Image,
  FlatList
} from 'react-native';
import Icon from 'react-native-vector-icons/SimpleLineIcons';
import { RtcEngine, AgoraView } from 'react-native-agora';
import MaterialCommunityIcons from 'react-native-vector-icons/MaterialCommunityIcons';
import { APPID, isIphoneX, isIphoneXR } from '../../util/agoraUtil';
import OperateButton from './OperateButton';
import isUndefined from '../../util/validation';
import theme from '../../styles/theme.style';
import { TextBolder } from '../common';

import {
  _callEndButton,
  _screenSharingDisabled,
  _screenSharingEnabled,
  _videoStreamingDisabled,
  _videoStreamingEnabled,
  _voiceStreamingDisabled,
  _voiceStreamingEnabled
} from './videoButtons';
import themeStyle from '../../styles/theme.style';

const { Agora } = NativeModules;
const APPBAR_HEIGHT = Platform.OS === 'ios' ? 50 : 56;
const urbanproLogo = require('../../../assets/urbanpro_logo.png');

if (!Agora) {
  throw new Error(
    'Agora load failed in react-native, please check ur compiler environments'
  );
}

const {
  FPS30,
  FixedLandscape,
  Adaptative,
  Host,
  AudioProfileDefault,
  AudioScenarioDefault
} = Agora;

const { width, height } = Dimensions.get('window');

const safeTop = top => {
  const safeView = top;
  if (isIphoneX(Platform, width, height)) {
    return safeView + 88;
  } else if (isIphoneXR(Platform, width, height)) {
    return safeView + 64;
  }
  return safeView;
};

type Props = {
  channelProfile: Number,
  channelName: String,
  videoProfile: Number,
  clientRole: Number,
  onCancel: Function,
  uid: Number,
  showVideo: boolean
};

export default class AgoraComponent extends Component<Props> {
  state = {
    peerIds: [],
    joinSucceed: false,
    isSpeak: true,
    isMute: false,
    isCameraTorch: false,
    showVideo: true,
    hideButton: false,
    visible: false,
    selectedUid: undefined,
    secondsElapsed: 0,
    screenDisplay: false,
    displayTime: '00:00:00'
  };

  componentWillMount() {
    const config = {
      appid: APPID,
      channelProfile: this.props.channelProfile,
      videoProfile: this.props.videoProfile,
      clientRole: isUndefined(this.props.clientRole)
        ? Host
        : this.props.clientRole,
      videoEncoderConfig: {
        width: 720,
        height: 1280,
        bitrate: 1,
        frameRate: FPS30,
        orientationMode: Adaptative
      },
      audioProfile: AudioProfileDefault,
      audioScenario: AudioScenarioDefault
    };

    RtcEngine.on('firstRemoteVideoDecoded', data => {
      console.log('[RtcEngine] onFirstRemoteVideoDecoded', data);
    });

    RtcEngine.on('userJoined', data => {
      console.log('[RtcEngine] onUserJoined', data);
      const { peerIds } = this.state;
      let selectedUid = this.state.selectedUid;
      if (isUndefined(this.state.selectedUid)) {
        selectedUid = data.uid;
      }
      if (peerIds.indexOf(data.uid) === -1) {
        this.setState({
          peerIds: [...peerIds, data.uid],
          selectedUid
        });
      }
    });

    RtcEngine.on('userOffline', data => {
      console.log('[RtcEngine] onUserOffline', data);
      this.setState({
        peerIds: this.state.peerIds.filter(uid => uid !== data.uid),
        visible: false,
        screenDisplay: false
      });
    });

    RtcEngine.on('joinChannelSuccess', data => {
      console.log('[RtcEngine] onJoinChannelSuccess', data);
      RtcEngine.startPreview();
      this.setState({
        joinSucceed: true
      });
    });

    RtcEngine.on('audioVolumeIndication', data => {
      // console.log('[RtcEngine] onAudioVolumeIndication', data);
    });

    RtcEngine.on('clientRoleChanged', data => {
      console.log('[RtcEngine] onClientRoleChanged', data);
    });

    RtcEngine.on('error', data => {
      if (data.error === 17) {
        RtcEngine.leaveChannel().then(x => {
          console.log('leaving channel', x);
          RtcEngine.destroy();
          this.props.onCancel(data);
        });
      }
    });

    console.log('[CONFIG]', JSON.stringify(config));
    console.log('[CONFIG.encoderConfig', config.videoEncoderConfig);
    RtcEngine.init(config);
  }

  componentDidMount() {
    RtcEngine.getSdkVersion(version => {
      console.log('[RtcEngine] getSdkVersion', version);
    });

    console.log('Join_Channel', this.props.channelId, this.props.uid);

    RtcEngine.joinChannel(
      this.props.channelId.toString(),
      this.props.uid,
      'nil',
      'nil'
    ).then( result =>{
      console.log("result",result);    
    });



    RtcEngine.enableAudioVolumeIndication(500, 3);
    this.startTimer();

  }

  componentWillUnmount() {
    if (this.state.joinSucceed) {
      RtcEngine.leaveChannel();
      RtcEngine.removeAllListeners();
      RtcEngine.destroy();
    }
  }

  onPressVideo = uid => {
    this.setState(
      {
        selectedUid: uid
      }
      ,
      () => {
        this.setState({
          visible: true
        });
      }
    );
    setTimeout(() => {
      this.setTimePassed();
    }, 200);
  };

  setTimePassed() {
    this.setState({ screenDisplay: true });
  }

  handleCancel = () => {
    RtcEngine.leaveChannel();
    RtcEngine.removeAllListeners();
    RtcEngine.destroy();
    clearTimeout(this.state.durationTimer);
    this.props.onCancel();
  };

  switchCamera = () => {
    RtcEngine.switchCamera();
  };

  toggleAllRemoteAudioStreams = () => {
    this.setState(
      {
        isMute: !this.state.isMute
      },
      () => {
        RtcEngine.enableLocalAudio(!this.state.isMute);
      }
    );
  };

  toggleSpeakerPhone = () => {
    this.setState(
      {
        isSpeak: !this.state.isSpeak
      },
      () => {
        RtcEngine.setDefaultAudioRouteToSpeakerphone(this.state.isSpeak);
      }
    );
  };

  toggleCameraTorch = () => {
    this.setState(
      {
        isCameraTorch: !this.state.isCameraTorch
      },
      () => {
        RtcEngine.setCameraTorchOn(this.state.isCameraTorch).then(val => {
          console.log('setCameraTorch', val);
        });
      }
    );
  };

  toggleVideo = () => {
    const showVideo = !this.state.showVideo;
    this.setState({
      showVideo
    });
    RtcEngine.enableLocalVideo(showVideo);
  };

  toggleHideButtons = () => {
    this.setState({
      hideButton: !this.state.hideButton
    });
  };

  shareScreen = () => {
    console.log('need to check whether it is possible or not');
  };

  renderMicEnableAndDisableButton = () => {
    return (
      <OperateButton
        style={styles.OperateButtonStyle}
        onPress={this.toggleAllRemoteAudioStreams}
        source={
          this.state.isMute
            ? _voiceStreamingDisabled()
            : _voiceStreamingEnabled()
        }
      />
    );
  };

  renderVideoEnableAndDisableButton = () => {
    return (
      <OperateButton
        style={styles.OperateButtonStyle}
        onPress={this.toggleVideo}
        source={
          this.state.showVideo
            ? _videoStreamingEnabled()
            : _videoStreamingDisabled()
        }
      />
    );
  };

  renderShareScreenEnableAndDisableButton = () => {
    return (
      <OperateButton
        style={styles.OperateButtonStyle}
        onPress={this.shareScreen}
        source={
          this.state.showVideo
            ? _screenSharingEnabled()
            : _screenSharingDisabled()
        }
      />
    );
  };

  renderEndCallButton = () => {
    return (
      <OperateButton
        style={styles.OperateButtonStyle}
        onPress={this.handleCancel}
        source={_callEndButton()}
      />
    );
  };

  renderAvailableOptions = () => {
    if (!this.state.hideButton) {
      return (
        <View style={styles.bottomView}>
          {this.renderLocalVideoAndPeerVideoes()}
          <View style={styles.footerStyle}>
            {this.renderMicEnableAndDisableButton()}
            {this.renderVideoEnableAndDisableButton()}
            {this.renderEndCallButton()}
          </View>
        </View>
      );
    }
    return (
      <View style={styles.bottomView}>{this.renderLocalVideoAndPeerVideoes()}</View>
    );
  };

  renderControlsForPresentationMode = () => {
    if (!this.state.hideButton) {
      return (
        <View style={styles.bottomView}>
          <View style={styles.footerStyle}>
            {this.renderMicEnableAndDisableButton()}
            {this.renderVideoEnableAndDisableButton()}
            {this.renderEndCallButton()}
          </View>
        </View>
      );
    }
    return (
      <View />
    );
  }

  renderLocalVideoAndPeerVideoes = () => {
    console.log('renderLocalVideoAndPeerVideoes peerIds', this.state.peerIds);
    return (
      <View style={styles.sideBySideStyle}>
        {this.renderPeerViews()}
        {this.renderLocalVideoStreaming()}
      </View>
    );
  };

  renderPeerViews = () => {
    const peerIds = [...this.state.peerIds];
    peerIds.shift();
    if (peerIds.length > 0) {
      return (
        <FlatList
          horizontal
          inverted
          showsHorizontalScrollIndicator={false}
          disableVirtualization={false}
          data={peerIds}
          renderItem={this.renderPeerView}
          keyExtractor={(item, index) => {
            const key = `peer_${item}_${index}`;
            return key;
          }}
          initialNumToRender={5}
        />
      );
    }
    return <View />;
  };
  /**
   *
   *
   * @param {*} { item, index }
   *
   * @item here item is uid of a particular peer
   * @index is the index of peer in the peerIds list
   *
   */
  renderPeerView = ({ item, index }) => {
    return (
      <TouchableOpacity onPress={() => this.onPressVideo(item)}>
        <AgoraView style={styles.peerViewStyle} zOrderMediaOverlay remoteUid={item} />
      </TouchableOpacity>
    );
  };

  renderLocalVideoStreaming = () => {
    return (

      <TouchableOpacity style={{ margin: 10, alignSelf: 'flex-start' }}>
        <AgoraView
          style={styles.remoteView}
          zOrderMediaOverlay
          showLocalVideo={true}
        />
      </TouchableOpacity>
    );
  };

  renderFeedBackDialog = ({ visible }) => {
    if (!this.state.screenDisplay && this.state.visible) {
      return (
        <View />
      );
    } else {

      return (
        <Modal
          visible={visible}
          presentationStyle={'fullScreen'}
          animationType={'slide'}
          onRequestClose={() => { }}
        >
          <TouchableOpacity
            style={styles.container}
            onPress={() =>
              this.setState({
                visible: false,
                screenDisplay: false
              })
            }
          >
            <AgoraView
              style={styles.localView}
              remoteUid={this.state.selectedUid}
              mode={2}
            />
            {this.renderControlsForPresentationMode()}
          </TouchableOpacity>
        </Modal>
      );
    }
  };

  // renderFeedBackDialog = ({ visible }) => {
  //   return (
  //     <Modal
  //       visible={visible}
  //       presentationStyle={'fullScreen'}
  //       animationType={'slide'}
  //       onRequestClose={() => { }}
  //     >
  //       <TouchableOpacity
  //         activeOpacity={1}
  //         style={{ flex: 1, flexDirection: 'row', alignItems: 'center' }}
  //         onPress={() =>
  //           this.setState({
  //             visible: false
  //           })
  //         }
  //       >
  //         <AgoraView remoteUid={this.state.selectedUid}
  //           style={{ width: width, height: height }}
  //         />
  //         {this.renderControlsForPresentationMode()}
  //       </TouchableOpacity>
  //     </Modal>
  //   );
  // };

  renderHeader = () => {
    if (!this.state.hideButton) {
      return (
        <View style={styles.headerStyle}>
          <Image style={styles.image} source={urbanproLogo} />
          <View style={styles.broadCastStyle}>
            <TextBolder>{this.state.displayTime}</TextBolder>
          </View>
        </View>
      );
    }
  };

  renderFirstPeerVideoOnScreenIfAvailable = () => {
    if (this.state.peerIds.length > 0) {
      const selectedUid = this.state.selectedUid;
      return <AgoraView style={styles.localView} remoteUid={selectedUid} />;
    }

    return (
      <View
        style={[
          styles.localView,
          { justifyContent: 'center', alignItems: 'center' }
        ]}
      >
        <TextBolder>Peers are not available</TextBolder>
      </View>
    );
  };

  showTimer = () => {
    let seconds = this.state.secondsElapsed;
    seconds++;
    this.setState({ secondsElapsed: seconds });

    let hoursLeft = Math.floor(seconds);
    let hours = Math.floor(hoursLeft / 3600);
    let minutesLeft = Math.floor(hoursLeft - hours * 3600);
    let minutes = Math.floor(minutesLeft / 60);
    let remainingSeconds = seconds % 60;
    hours = hours < 10 ? "0" + hours : hours;
    minutes = minutes < 10 ? "0" + minutes : minutes;
    remainingSeconds = remainingSeconds < 10 ? "0" + remainingSeconds : remainingSeconds;

    this.setState({
      displayTime: hours + ":" + minutes + ":" + remainingSeconds
    });


  }
  startTimer() {
    let durationTimer = setInterval(this.showTimer, 1000);
    this.setState({ durationTimer });
  }

  render() {
    if (!this.state.joinSucceed) {
      return (
        <View
          style={{
            flex: 1,
            backgroundColor: '#fff',
            justifyContent: 'center',
            alignItems: 'center'
          }}
        >
          <ActivityIndicator size="large" color="#999" />
          <Text>Creating a video conference...</Text>
        </View>
      );
    }

    return (
      <TouchableOpacity
        activeOpacity={1}
        onPress={this.toggleHideButtons}
        style={styles.container}
      >
        {this.renderFirstPeerVideoOnScreenIfAvailable()}
        {this.renderHeader()}
        {this.renderAvailableOptions()}
        {this.renderFeedBackDialog(this.state)}
      </TouchableOpacity>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.PAGE_BACKGROUND
  },
  absView: {
    position: 'absolute',
    top: safeTop(0),
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'space-between'
  },
  videoView: {
    padding: 5,
    flexWrap: 'wrap',
    flexDirection: 'row',
    zIndex: 100
  },
  localView: {
    flex: 1,
    margin: 5
  },
  remoteView: {
    width: (width - 20) / 4,
    height: (width + 60) / 4
  },
  bottomView: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1
  },
  footerStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    marginBottom: 20,
    flex: 1
  },
  headerStyle: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: safeTop(0),
    justifyContent: 'space-between',
    flex: 1,
    height: APPBAR_HEIGHT,
    flexDirection: 'row',
    backgroundColor: theme.PAGE_BACKGROUND,
    marginLeft: 5,
    marginRight: 5
  },
  broadCastStyle: {
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center'
  },
  image: {
    alignSelf: 'flex-start',
    width: 130,
    height: APPBAR_HEIGHT,
    resizeMode: 'contain'
  },
  OperateButtonStyle: {
    flex: 1,
    alignItems: 'center'
  },
  sideBySideStyle: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center'
  },
  peerViewStyle: {
    width: (width - 20) / 4,
    height: (width + 60) / 4,
    borderRadius: (width - 40) / 2,
    borderColor: theme.PAGE_BACKGROUND,
    alignSelf: 'flex-end'
  },
  agoraViewStyle: {
    width: (width - 40) / 3,
    height: (width - 40) / 3,
    overflow: 'hidden'
  }
});`

**Comment by harshalijain** [comment]
Hi @Matrixbirds , we are not using any token permission anywhere, and hence passing 'nil', the issue is that after we fire joinChannel, the RTCEngine does not fire the event 'joinChannelSuccess' , any insight as to why this might happen would be appreciated.

**Comment by harshalijain** [comment]
When we are calling  RtcEngine.init(config), our config object is this:
[CONFIG] {"appid":<APPID goes here>,"channelProfile":1347,"videoProfile":40,"clientRole":1,"videoEncoderConfig":{"width":720,"height":1280,"bitrate":1,"frameRate":30,"orientationMode":0},"audioProfile":0,"audioScenario":0}
App Id is working fine on Android, but returns AgoraError : 101 on iOS.  any insight as to why this might happen would be appreciated.

**Comment by StarkAndy** [comment]
Hi got the solution .
 As per agora has provided ios default project there it tries to pass token as string assuming nil as a value which was causing the error.

I changed token to nil in joinChannel in ios project & voila !! .

RCTAgora.m file:
` NSInteger res = [self.rtcEngine joinChannelByToken:nil channelId:options[@"channelName"] info:options[@"info"] uid:[AgoraConst share].localUid joinSuccess:nil];
    `

**Comment by Matrixbirds** [comment]
@StarkAndy 
I just tried the 2.9.0-alpha.3 with [quickstart](http://github.com/agoraio-community/agora-rn-quickstart), it works fine. Probably please check your joinChannel parameters. You can find the token parameter is optional in document If u don't fill it the native layer wouldn't receive the token and in objc it will handle it by nil.
