### ISSUE TITLE
How can I show a message to everyone if anyone join in video broadcast mode ?

### ISSUE THREAD

**Issue by rakib-09** [syanbo/react-native-agora#103]
Hello @Matrixbirds 
My video broadcasting is working fine. 
I want to invoke an event if anyone joined in the live broadcast video. 
I tried 
`RtcEngine.sendMediaData('UserX Joined')` 
inside ` RtcEngine.joinChannel` method but its not working and give an error. 
I am not sure how to do that.

**Comment by Matrixbirds** [comment]
Which platform u cause this error? Please listen on("error") event, and reproduce your case and paste your log here, BTW Can u tell me more about your scenario?

**Comment by rakib-09** [comment]
Actually I want to broadcast a message like "OneUser Joined in Live".  If anyone joined in any live broadcast. 
After that I found "Agora-RTM" to solve this problem. 
Now I cannot implement AGORA-RTM with Agora Video broadcasting. 
Would you like to give me give me a better solution to show message like this ? :)

**Comment by Matrixbirds** [comment]
You could try to use agora-react-native-rtm, here is [example](https://github.com/AgoraIO/agora-react-native-rtm/tree/master/examples/chatsapp).
