### ISSUE TITLE
Attempt to invoke virtual method  'boolean jaba.lang.Boolean.booleanValue() on null object refrence 

### ISSUE THREAD

**Issue by rizwan92** [syanbo/react-native-agora#104]
getting this errror `Attempt to invoke virtual method 'boolean jaba.lang.Boolean.booleanValue() on null object refrence`

while running this code in component did mount 
```
componentDidMount() {
const config = {
			appid: APP_ID,
			channelProfile: 1,
			clientRole: Host,
			videoEncoderConfig: {
				width: 360,
				height: 480,
				bitrate: 1,
				frameRate: FPS30,
				orientationMode: Adaptative
			},
			audioProfile: AudioProfileDefault,
			audioScenario: AudioScenarioDefault
		};
                RtcEngine.init(config);
		RtcEngine.joinChannel('qwe', 123, '01df5dbf8d274778b3cf5da2967074ab')
			.then((result) => {
				console.log(result);
			})
		RtcEngine.enableAudioVolumeIndication(500, 3) // i am getting error when i run this line 
	}
```

i am getting this error when ran this line  `RtcEngine.enableAudioVolumeIndication(500, 3) `
when i comment this line then get error on error event listener like below
![image](https://user-images.githubusercontent.com/19162978/66917184-8a441d80-f03a-11e9-8608-3581119c8ba1.png)

**Comment by rizwan92** [comment]
i solved this issue by passing updating code
 from 
`RtcEngine.enableAudioVolumeIndication(500, 3)
`to 
`RtcEngine.enableAudioVolumeIndication(500, 3,true)`

now everything is working fine 
please someone tells me the best  production practice

**Comment by Matrixbirds** [comment]
Yes this is new api which supported since 2.9.1-alpha.1.
I suggest to lock all of your react native npm dependencies by hand include some babel plugin, don't use `^` `~` those update operator in your package.json, that would be more safety.

**Comment by rizwan92** [comment]
any tips for production cause I am gonna launch my app that will more helpfull

**Comment by HaseemUlHaq** [comment]
> i solved this issue by passing updating code
> from
> `RtcEngine.enableAudioVolumeIndication(500, 3) `to
> `RtcEngine.enableAudioVolumeIndication(500, 3,true)`
> 
> now everything is working fine
> please someone tells me the best production practice

Worked for me, Thanks
