### ISSUE TITLE
App Crashes when release signed APK

### ISSUE THREAD

**Issue by HemanthSurimani** [syanbo/react-native-agora#106]
In debugging mode application working fine 
after release signed APK app get crashed

Fatal Exception: java.lang.RuntimeException
create rtc engine failed java.lang.ClassNotFoundException: Didn't find class "io.agora.rtc.mediaio.VideoFrameConsumerImpl" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.vikipedia-Yv0L7rMiQLWONuMYd6E_7A==/base.apk"],nativeLibraryDirectories=[/data/app/com.vikipedia-Yv0L7rMiQLWONuMYd6E_7A==/lib/arm64, /data/app/com.vikipedia-Yv0L7rMiQLWONuMYd6E_7A==/base.apk!/lib/arm64-v8a, /system/lib64]] at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134) at java.lang.ClassLoader.loadClass(ClassLoader.java:379) at java.lang.ClassLoader.loadClass(ClassLoader.java:312) at java.lang.Runtime.nativeLoad(Native Method) at java.lang.Runtime.loadLibrary0(Runtime.java:1014) at java.lang.System.loadLibrary(System.java:1669) at io.agora.rtc.internal.RtcEngineImpl.zda(Unknown Source:5) at io.agora.rtc.internal.RtcEngineImpl.yda(Unknown Source:7) at d.a.a.e.a(Unknown Source:5) at com.syan.agora.a.a(Unknown Source:30) at com.syan.agora.AgoraModule.init(Unknown Source:10) at java.lang.reflect.Method.invoke(Native Method) at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:149) at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:21) at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) at android.os.Handler.handleCallback(Handler.java:873) at android.os.Handler.dispatchMessage(Handler.java:99) at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0) at android.os.Looper.loop(Looper.java:216) at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37) at java.lang.Thread.run(Thread.java:764)

**Comment by StarkAndy** [comment]
@HemanthSurimani  i ran into similar issue .It happens when there are some function which should not be there please check your constructor of that file and see if your are initialising any ref value or something similar.

**Comment by arvenjadeaguilar** [comment]
Experience the same issue.. How did you fix this? Please help. Thanks

**Comment by ankitmeddo** [comment]
Experiencing the same issue.. Can anyone help please.

**Comment by ankitmeddo** [comment]
For those, who are still facing this issue, you need to add below line in android/proguard-rules.pro:
Dont know why they have not highlighted this line in their documentation.

-keep class io.agora.**{*;}

[https://github.com/syanbo/react-native-agora/blob/master/docs/v1/android.md](url)

**Comment by marcusmolchany** [comment]
same step in the v2 android docs: https://github.com/syanbo/react-native-agora/blob/master/docs/v2/android.md#for-obfuscation-code-edit-androidproguard-rulespro

**Comment by LichKing-2234** [comment]
I will close this issue because it is not active. if there are still problems, you can reopen this issue.

**Comment by KaviduAloka** [comment]
As per Agora.io documentation:

Add the following line in the **android/app/proguard-rules.pro** file to prevent code obfuscation,

`-keep class io.agora.**{*;}`

**Comment by gauravsbagul** [comment]
Thanks this solved my issue

**Comment by Missice** [comment]
Thanks this also solved my problem!!!!!!!

**Comment by LichKing-2234** [comment]
the 3.+ version has added the proguard rules by default.
