### ISSUE TITLE
library not found for -lcrypto

### ISSUE THREAD

**Issue by GuoJiKaiHehe** [syanbo/react-native-agora#107]
看了好多遍文档。然后报这个错。有没有兄弟解决的。给个答复，求救

**Comment by Matrixbirds** [comment]
可以的话提供一份比较完整的编译日志。感觉是编译时发现缺少这个库crypto链接

**Comment by CoderTitan** [comment]
我也遇到这个错误了, 
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lcrypto
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lcrypto is not an object file (not allowed in a library)
Command Libtool failed with a nonzero exit code

**Comment by CoderTitan** [comment]
@GuoJiKaiHehe 请问你这个最后怎么解决的

**Comment by esdotzed** [comment]
@GuoJiKaiHehe @CoderTitan 我也遇到了相同的问题，请问最后解决了吗？

**Comment by esdotzed** [comment]
@GuoJiKaiHehe @CoderTitan 我貌似解决了这个问题，我删除了Link Binary With Libraries 里面手动加进去的librctagora.a 就编译通过了。目前在react native里面 `const {Agora} = NativeModules； console.log(Agora);`是没有显示任何错误的，所以我觉得可能是没问题了。如果之后我发现还有问题会再回来更新。

**Comment by KarenQiao** [comment]
我也遇到这个问题了，删除Link Binary With Libraries 里面手动加进去的librctagora.a 之后，又会报这个错误：找不到#import <React/RCTViewManager.h> 这个文件

**Comment by syanbo** [comment]
#208 
2.9.1-alpha.4 已解决
如果0.60版本一下
cd ios 
pod init
在 Podfile 文件下新增
pod "AgoraRtcEngine_iOS", "2.9.1"
