### ISSUE TITLE
Local and Remote Video Not Shown

### ISSUE THREAD

**Issue by JavidHaji-zada** [syanbo/react-native-agora#108]
I have tried to implement exact same code from Youtube tutorial. I am testing video call. One of devices is physical another one is emulator ( both android). I can see colors of emulator's camera on my phone, however video through phone's camera is not shown on either device. What I see is only black screen.

I have also tried on 2 physical devices. Both shows black screen for remote video. Nothing is shown for local video

**Comment by Matrixbirds** [comment]
Can u try to reproduce this case on our [quickstart](https://github.com/agoraio-community/agora-rn-quickstart)?

**Comment by JavidHaji-zada** [comment]
@Matrixbirds I could not reproduce the case on [https://github.com/agoraio-community/agora-rn-quickstart] quickstart. Local video is shown on the sample you gave. However, when I try to implement the same code on my own project video doesn't work. Here is what I have implemented: 

> const { Agora } = NativeModules;

const {
    FPS30,
    AudioProfileDefault,
    AudioScenarioDefault,
    Host,
    Adaptative
} = Agora

class VideoScreen extends Component {
    state = {
        uid: Math.floor(Math.random() * 100),
        channelName: 'channel',
        peerIds: [],
        joinSucceed: false,
        isMute: false,
        hideButton: false,
        visible: false,
        selectedUid: undefined,
        animating: true
    }
    componentWillMount() {
        const config = {
            appid: '', //deleted on purpose
            channelProfile: this.props.channelProfile,
            clientRole: this.props.clientRole,
            videoEncoderConfig: {
                width: 360,
                height: 480,
                bitrate: 1,
                frameRate: FPS30,
                orientationMode: Adaptative,
            },
            audioProfile: AudioProfileDefault,
            audioScenario: AudioScenarioDefault
        }
        console.log("[CONFIG]", JSON.stringify(config));
        console.log("[CONFIG.encoderConfig", config.videoEncoderConfig);
        RtcEngine.on('videoSizeChanged', (data) => {
            console.log("[RtcEngine] videoSizeChanged ", data)
        })
        RtcEngine.on('remoteVideoStateChanged', (data) => {
            console.log('[RtcEngine] `remoteVideoStateChanged`', data);
        })
        RtcEngine.on('userJoined', (data) => {
            console.log('[RtcEngine] onUserJoined', data);
            const { peerIds } = this.state;
            if (peerIds.indexOf(data.uid) === -1) {
                this.setState({
                    peerIds: [...peerIds, data.uid]
                })
            }
        })
        RtcEngine.on('userOffline', (data) => {
            console.log('[RtcEngine] onUserOffline', data);
            this.setState({
                peerIds: this.state.peerIds.filter(uid => uid !== data.uid)
            })
            console.log('peerIds', this.state.peerIds, 'data.uid ', data.uid)
        })
        RtcEngine.on('joinChannelSuccess', (data) => {
            console.log('[RtcEngine] onJoinChannelSuccess', data);
            RtcEngine.startPreview().then(_ => {
                this.setState({
                    joinSucceed: true,
                    animating: false
                })
            })
        })
        RtcEngine.on('audioVolumeIndication', (data) => {
            console.log('[RtcEngine] onAudioVolumeIndication', data);
        })
        RtcEngine.on('clientRoleChanged', (data) => {
            console.log("[RtcEngine] onClientRoleChanged", data);
        })
        RtcEngine.on('videoSizeChanged', (data) => {
            console.log("[RtcEngine] videoSizeChanged", data);
        })
        RtcEngine.on('error', (data) => {
            console.log('[RtcEngine] onError', data);
            if (data.error === 17) {
                RtcEngine.leaveChannel().then(_ => {
                    this.setState({
                        joinSucceed: false
                    })
                    const { state, goBack } = this.props.navigation;
                    this.props.onCancel(data);
                    goBack();
                })
            }
        })
        RtcEngine.init(config);
    }

    componentDidMount() {
        RtcEngine.getSdkVersion((version) => {
            console.log('[RtcEngine] getSdkVersion', version);
        })

        RtcEngine.joinChannel(this.state.channelName, this.state.uid)
            .then(result => {
                /**
                 * ADD the code snippet after join channel success.
                 */
            });
        RtcEngine.enableAudioVolumeIndication(500, 3, true);
    }

  
    componentWillUnmount() {
        if (this.state.joinSucceed) {
            RtcEngine.leaveChannel().then(res => {
                RtcEngine.destroy();
            }).catch(err => {
                RtcEngine.destroy();
                console.log("leave channel failed", err);
            })
        } else {
            RtcEngine.destroy();
        }
    }
render() {
        return (
            <View style={{ flex: 1 }}>
                <AgoraView style={{ flex: 1 }} showLocalVideo={true} mode={
            </View>
        )
}

**Comment by remidi** [comment]
Is there any version changes because all the issues similar to `video not showing` or `black screen in local/remote ` are being raised quite recently ?

**Comment by ijelechimaobi** [comment]
Why do I get null is not an object (evaluating Agora.FPS30')

**Comment by LichKing-2234** [comment]
suggest using react-native-agora@3.0.1-beta.3

**Comment by HarshitMadhav** [comment]
@LichKing-2234 the version you mentioned is it stable?

**Comment by LichKing-2234** [comment]
@HarshitMadhav Yes, It is stable more than the alpha version.

**Comment by Erre35** [comment]
> Why do I get null is not an object (evaluating Agora.FPS30')

I have the same problem, did you solve it?

**Comment by LichKing-2234** [comment]
@Erre35 pls refer to the new SDK and match version Demo.

**Comment by prastogi957** [comment]
> 
> 
> Why do I get null is not an object (evaluating Agora.FPS30')

I have the same problem, Can someone suggest a method to solve it

**Comment by hasanalfath** [comment]
> Why do I get null is not an object (evaluating Agora.FPS30')

I have the same problem, did you solve it?

**Comment by LichKing-2234** [comment]
> @Erre35 pls refer to the new SDK and match version Demo.
```
null is not an object (evaluating Agora.FPS30')
```

this error means you are using the old version on JS layer, but the native layer is new.

**Comment by hasanalfath** [comment]
Why do I get TypeError: null is not an object (evaluating 'engine.joinChannel')

**Comment by plutoless** [comment]
@hasanalfath seems engine is null

**Comment by hasanalfath** [comment]
I upgraded to "react-native": "0.64.0", and solved, my previous versions  "react-native": "0.63.4"
