### ISSUE TITLE
如果接第三方比如相芯美颜，该如何在你当前版本上改进呢？

### ISSUE THREAD

**Issue by clycheng2015** [syanbo/react-native-agora#109]

**Comment by Matrixbirds** [comment]
一般美颜实现方式是使用声网的视频自采集sdk接口 可以提供一下您目前使用的美颜sdk的文档吗？

**Comment by clycheng2015** [comment]
只提供了native端和美颜SDK集成的示例项目，但和您项目中差别还是很大的！始终没生效！改动的地方也很多，麻烦给参看下：示例地址：Android : https://github.com/AgoraIO/FaceUnity/tree/master/Agora-Video-With-FaceUnity-Android

**Comment by clycheng2015** [comment]
网上找的美颜方的文档地址：http://www.faceunity.com/docs_develop/#/markdown/integrate/introduction

**Comment by clycheng2015** [comment]
首先要将您当前项目改动成实现自定义视频源和渲染器的形式吧，您当前项目视频源应该是默认的！

**Comment by Matrixbirds** [comment]
是的 目前这个项目是默认的 这个后面我也会考虑一下怎么改进来支持这样的操作 可能需要花一点时间
