### ISSUE TITLE
没有封装 用户启用/关闭视频回调 (didVideoEnabled) 这个方法 吗？

### ISSUE THREAD

**Issue by DMCHZP** [syanbo/react-native-agora#11]
视频通话时，把程序挂到后台这时对方只能听到声音，但是其他用户没有这个事件的回调，可以加多这个封装吗？这个回调是不是 （ 用户启用/关闭视频回调 (didVideoEnabled)  ） 这个方法?

**Comment by syanbo** [comment]
好的 下个版本会完善其他的回调事件

**Comment by DMCHZP** [comment]
@syanbo 下个版本是什么时候呢？
