### ISSUE TITLE
Agora header expansion issue coming up after pod install

### ISSUE THREAD

**Issue by StarkAndy** [syanbo/react-native-agora#110]
Argument list too long: recursive header expansion failed at /Users/gyaneshbohara/Documents/Programs/React/UrbanProSync/urbanprosync/node_modules/react-native-agora/ios/../../../ios/Pods/React/node_modules/ast-query/node_modules/esprima/bin.

**Comment by Matrixbirds** [comment]
Did u update the header path in xcode environment? It seems you r missing the offical react module ast-query package
