### ISSUE TITLE
How to show incoming call notification in android application ?

### ISSUE THREAD

**Issue by nitheeshskiploop** [syanbo/react-native-agora#111]
I'm trying to build one to one video calling Mobile App using react-native-agora.
I'm able to join to call one to one perfectly.

Now i'm trying to show the incoming call notification on android app.

Any idea to show incoming call notification on android app.

My dependencies
"react": "16.8.3",
"react-native": "0.59.3",
 "react-native-agora": "2.4.0-alpha-1",

**Comment by varunsdcet** [comment]
@nitheeshskiploop same problem here . have you find its workaround

**Comment by Matrixbirds** [comment]
It seems you need integrate some notification component, you can try to use firebase or aws cloud component

**Comment by Nitheeshsalian** [comment]
@varunsdcet i have used firebase notification component.

**Comment by LichKing-2234** [comment]
I will close this issue because it is not active. if there are still problems, you can reopen this issue.
