### ISSUE TITLE
userJoined eventListener not working

### ISSUE THREAD

**Issue by herrera-ignacio** [syanbo/react-native-agora#112]
Hi, I'am trying to use the `userJoined` event listener to update a streaming's viewers amount but the event is never emitted when new users joins.

Here's how I setup the listener:

```
RtcEngine.on('userJoined', (data) => {
	console.log('[RtcEngine] userJoined', data);
	// Update channel users count
	return updateViews(channelViews + 1);
});
```

I'm using `"react-native-agora": "^2.9.1-alpha.2"`. Any ideas?

**Comment by hiscc** [comment]
the **leaveChannel、userOffline、firstRemoteAudioFrame** also not working!!!
version: "react-native-agora": "^2.9.1-alpha.3"

**Comment by prateekchachra** [comment]
+1

**Comment by LichKing-2234** [comment]
you may try react-native-agora@beta, the new version of our SDK

**Comment by LichKing-2234** [comment]
I will close this issue because it is not active. if there are still problems, you can reopen this issue.

**Comment by meliodev** [comment]
All listeners are still not working, even on react-native-agora@beta. Any solution please ?

**Comment by lgarro27** [comment]
You are using the wrong casing
