### ISSUE TITLE
Incoming Call Alert and Screenshot Capturing & Sharing

### ISSUE THREAD

**Issue by achus-ui** [syanbo/react-native-agora#114]
Dear Team
We are building a Video Calling Application for mobile app in React-Native and Web App in Angular 8. Everything is working fine, now we have a new requirement from our client.
1) If Web App is initiating a call towards mobile app, how can I alert the mobile app user for an Incoming Call like other Calling Apps like WhatsApp or Skype.
2) I want to capture the screenshot from mobile app and send it to Web App. How we can do this?

Any suggestions for this would be really helpful! Looking forward to your hear from you.

Thanks
Harikrishnan

**Comment by Matrixbirds** [comment]
I think u can build your own signal service on both native & web client. If you just have simple scenario such as chat, send picture in chat, you can try agora.io RTM services.

**Comment by AGC786** [comment]
@Matrixbirds Can agoro.io RTM send messages while app is closed? I am using socket.io and it doesn't work when app is closed.

**Comment by LichKing-2234** [comment]
@AGC786 RTM can not send messages while the app is closed. you can use FCM.
