### ISSUE TITLE
Value of uid cannot be cast from string to double

### ISSUE THREAD

**Issue by AGC786** [syanbo/react-native-agora#115]
My App is working fine when using low level security in agora(using just AppID), but when I try to use high level security(using AppID, App Certificate, Temporary Token) it gives me error "Value of uid cannot be cast from string to double", you can check my screen shots.
![Screenshot_2019-12-19-12-56-57-112_com agorademoreactnative](https://user-images.githubusercontent.com/46619420/71265456-1854c100-2368-11ea-84f2-5ef523f78ac0.jpg)
![01](https://user-images.githubusercontent.com/46619420/71265459-1854c100-2368-11ea-807e-af530dbfadff.PNG)

**Comment by harshalijain** [comment]
Value of uid passed is string but it should always be a numeric value, hence this error is raised  you can use parseInt to parse the string value

**Comment by AGC786** [comment]
Thanks for your answer and sorry for the late reply. I have also tried that but still no luck so for now I am using low level security(just AppID). But I am still researching on it.
