### ISSUE TITLE
Blank screen 

### ISSUE THREAD

**Issue by bang88** [syanbo/react-native-agora#117]
Can not see the live broadcast video but audio is correct. I have checkout the starter project. And  some codes are copying from that project.

How can i display a live broadcast in react-native. I can view the live broadcast in web.

Thank you!

**Comment by Matrixbirds** [comment]
U need a react-native co-video web demo?

**Comment by bang88** [comment]
不是web ，直播软件推流后要 Web 跟react native都能正常显示，现在Web没有问题了。但是rn 这边只能听到声音 看不到视频

matrixbirds <notifications@github.com>于2020年1月16日 周四20:51写道：

**Comment by bang88** [comment]
@Matrixbirds Help 。。
