### ISSUE TITLE
this value is duplicated AGRtcStats event‘s value is duplicated

### ISSUE THREAD

**Issue by yuwenbai** [syanbo/react-native-agora#118]
statsMap.putInt("rxVideoKBitRate", stats.rxVideoKBitRate);
                    statsMap.putInt("rxAudioKBitRate", stats.rxAudioKBitRate);
                    statsMap.putInt("txVideoKBitRate", stats.txVideoKBitRate);
                    statsMap.putInt("rxVideoKBitRate", stats.rxVideoKBitRate);
                    statsMap.putInt("lastmileDelay", stats.lastmileDelay);
                    statsMap.putInt("userCount", stats.users);
                    statsMap.putDouble("cpuAppUsage", stats.cpuAppUsage);
                    statsMap.putDouble("cpuTotalUsage", stats.cpuTotalUsage);
                    statsMap.putInt("txPacketLossRate", stats.txPacketLossRate);
                    statsMap.putInt("rxPacketLossRate", stats.rxPacketLossRate);

                    WritableMap map = Arguments.createMap();
                    map.putMap("stats", statsMap);
                    sendEvent(getReactApplicationContext(), AGRtcStats, map);

this value is duplicated

**Comment by LichKing-2234** [comment]
not a problem

**Comment by yuwenbai** [comment]
> not a bug
statsMap.putInt("rxVideoKBitRate", stats.rxVideoKBitRate);
statsMap.putInt("rxVideoKBitRate", stats.rxVideoKBitRate);    not a bug???

**Comment by LichKing-2234** [comment]
> > not a bug
> > statsMap.putInt("rxVideoKBitRate", stats.rxVideoKBitRate);
> > statsMap.putInt("rxVideoKBitRate", stats.rxVideoKBitRate);    not a bug???

Sorry, my mistake, I mean it has been fixed before you comment.
