### ISSUE TITLE
xcode Profile error

### ISSUE THREAD

**Issue by sakuraiki** [syanbo/react-native-agora#120]
Error: 
"_OBJC_CLASS_$_AgoraImage", referenced from:
Objc-class-ref in RCTAgora-5768F4989D642C4D.o
Objc-class-ref in libRCTAgora.a(RCTAgora.o)

The project can be built successfully when "Run" or "Archive", but throws 11 errors when "Profile"...

**Comment by LichKing-2234** [comment]
is this problem still exist?
