### ISSUE TITLE
Argument list too long and React/RCTEventEmitter.h file not found

### ISSUE THREAD

**Issue by vaibhav22c** [syanbo/react-native-agora#124]
Argument list too long: recursive header expansion failed at `/AGORA/node_modules/react-native-agora/ios/../../../ios/Pods/React/node_modules/set-value/node_modules`

And second error `'React/RCTEventEmitter.h'` file not found

![Screenshot 2020-01-28 at 3 12 42 PM](https://user-images.githubusercontent.com/47855926/73252463-c9107480-41e0-11ea-8939-720de61e24d8.png)

my package.json 

> {
   "name": "ephibank",
   "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "and": "react-native run-android",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.6.1",
    "buffer": "^5.2.1",
    "jetifier": "^1.6.3",
    "moment-timezone": "^0.5.27",
    "native-base": "2.5.1",
    "react": "16.8.3",
    "react-infinite-calendar": "^2.3.1",
    "react-native": "0.59.0",
    "react-native-agora": "^2.9.1-alpha.2",
    "react-native-firebase": "^5.3.1",
    "react-native-fs": "^2.15.2",
    "react-native-gesture-handler": "^1.4.0",
    "react-native-linear-gradient": "2.4.0",
    "react-native-permissions": "^1.1.1",
    "react-native-vector-icons": "^4.5.0",
    "react-navigation": "^3.4.1",
    "react-redux": "5.0.7",
    "redux": "3.7.2",
    "redux-persist": "^5.10.0",
    "redux-persist-filesystem-storage": "^1.4.1",
    "redux-thunk": "2.2.0",
    "rn-fetch-blob": "^0.10.16",
    "underscore": "1.9.1"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/runtime": "^7.5.5",
    "babel-jest": "^24.8.0",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.55.0",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by Matrixbirds** [comment]
It seems your native IDE cannot resolve appropriate iOS SDK.
You can follow our [quickstart](http://github.com/agoraio-community/agora-rn-quickstart) preference to fix that.
