### ISSUE TITLE
ios  podfile

### ISSUE THREAD

**Issue by G1King** [syanbo/react-native-agora#128]
![image](https://user-images.githubusercontent.com/21077737/74518337-9ab7c680-4f4e-11ea-8431-aed9112a6f16.png)
pod install

**Comment by syanbo** [comment]
(1)  podfile添加source 'https://github.com/CocoaPods/Specs.git'

（2）pod repo list 查看一下源列表

（3）pod repo remove trunk 移除trunk源

**Comment by syanbo** [comment]
你的  pod 版本应该 大于 1.8
