### ISSUE TITLE
[tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Module AppRegistry is not a registered callable module (calling runApplication)

### ISSUE THREAD

**Issue by harshasri1** [syanbo/react-native-agora#129]
In IOS it is showing error and used the quickStart project only
![Screen Shot 2020-02-25 at 7 17 49 PM](https://user-images.githubusercontent.com/61417463/75252920-923f7580-5803-11ea-96ca-b6be5668ddc9.png)

**Comment by LichKing-2234** [comment]
is the problem still exist?
