### ISSUE TITLE
Unknown argument type '_Bool' in method [RCTAgora setBeautyEffectOptions:options:resolve:reject:]. Extend RCTConvert to support this type

### ISSUE THREAD

**Issue by waldiirawan** [syanbo/react-native-agora#130]
My app is working fine when using agora RtcEngine without setBeautyEffect, but when I try to use setBeautyEffectOptions method my app returning  "Unknown argument type '_Bool' in method ".
Any solution ?

<img width="361" alt="Screen Shot 2020-02-26 at 11 56 54" src="https://user-images.githubusercontent.com/10203954/75313745-51da0900-5890-11ea-93f8-265033690854.png">

![IMG_0531](https://user-images.githubusercontent.com/10203954/75313786-7cc45d00-5890-11ea-9b11-adc6ba6d1ac8.PNG)

System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 60.38 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 8.11.1 - ~/.nvm/versions/node/v8.11.1/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.1/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 17, 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3, 29.0.2
      System Images: android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6200805
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7

**Comment by KarenQiao** [comment]
same issue,any updated?

**Comment by voslartomas** [comment]
Same here :/

**Comment by LichKing-2234** [comment]
fixed in 2.9.1-alpha.6
