### ISSUE TITLE
How to show incoming video call using react native agora.

### ISSUE THREAD

**Issue by AGC786** [syanbo/react-native-agora#135]
I want to add real time calling feature in my app.
I am using agora with socket.io to make it real time and it's working fine when app is in foreground, but I am stuck when app is closed because socket does not work when app is closed I want to show WhatsApp like incoming call screen. Kindly help me.
Thanks in advance.

**Comment by awitherow** [comment]
Anyone have an idea on how to do this? I would like to be able to integrate this with the app I am building as well.

**Comment by LichKing-2234** [comment]
you can use CallKit and PushKit on iOS, ConnectionService and Firebase Cloud Messaging on Android
