### ISSUE TITLE
alternative for sendMessage

### ISSUE THREAD

**Issue by mtalhagaoglu** [syanbo/react-native-agora#136]
Hi. I want to send my listener invite for join me. I looked the files and i found sendMessage() func but its deprecated. Is there any alternative?

**Comment by LichKing-2234** [comment]
if you want to sendMessage, you can use our RTM SDK

**Comment by mtalhagaoglu** [comment]
thank you!


https://github.com/AgoraIO/agora-react-native-rtm

**Comment by mtalhagaoglu** [comment]
thank you!

https://github.com/AgoraIO/agora-react-native-rtm
