### ISSUE TITLE
Keeping alive

### ISSUE THREAD

**Issue by mtalhagaoglu** [syanbo/react-native-agora#137]
Hi. When i listening stream i want to go another page but when i do that stream connection is closing. how can i solve that problem? and also if there is a option for background solution for changing app when i listen.

**Comment by LichKing-2234** [comment]
Android or iOS?
you mean the video and audio will stop when you enter another app, is it?

**Comment by mtalhagaoglu** [comment]
both of them. think like spotify. if you background app music still playing. but i found the solution. if  i don't run rtcengine.destroy() stream playing even app on background

**Comment by gwendall** [comment]
@mtalhagaoglu Have you managed to solve that ?

**Comment by mtalhagaoglu** [comment]
@gwendall you need give permission for background play on ios. for android some devices need adjust battery optimization thing.

**Comment by LichKing-2234** [comment]
update for this issue.

https://github.com/AgoraIO-Community/react-native-agora/issues/176#issuecomment-717670413
