### ISSUE TITLE
Battery and Heating issue (iOS)

### ISSUE THREAD

**Issue by marqroldan** [syanbo/react-native-agora#138]
Anyone else getting huge battery drain and heats up fast on iPhones? I don't notice this on Android, and I'm not using video either just audio

It turns out, some older Android phones are experiencing this too. But I don't experience this drain and heating on a Huawei Nova 3i

**Comment by LichKing-2234** [comment]
pls provide the SDK log, then we can get the usage of CPU

**Comment by marqroldan** [comment]
I'm sorry that I wasn't able to, but it turns out muting the local video doesn't really turn off the local stream so I had to use enableVideo() and disableVideo()
