### ISSUE TITLE
Adding audio effects

### ISSUE THREAD

**Issue by mtalhagaoglu** [syanbo/react-native-agora#139]
Hi. I need to add my stream add continious music, and i want to control it.Is it possible to add background music or something?

i found startAudioMixing() but it's not working properly. when i press button nothing happen and getAudioMixingDuration() returns null. it give 701 error and that means it can't find or read files but i'm sure files are not broken.

RtcEngine.startAudioMixing({
								filepath: './laugh.mp3',
								loopback: true,
								replace: true,
								cycle: 2,
							});

do you know something about that? @Matrixbirds

**Comment by gwendall** [comment]
+1, any idea about that ?

**Comment by mtalhagaoglu** [comment]
you need to give spesific location for audio (/storage/emulated/0/sound/laugh.mp3 ) . they explain that android document. i used react-native-fs for that problem but i'm using url now.

**Comment by gwendall** [comment]
Great, thank you
