### ISSUE TITLE
Linking Error when achieving

### ISSUE THREAD

**Issue by ozsirma** [syanbo/react-native-agora#14]
Firstly, thank you for this repo and your labor.

I completed installation of the library. I set enable bitcode no for targets. My project is build succeed but when I do achieve for project I take an error. "duplicate symbols for architecture arm64"

![screen shot 2018-01-06 at 20 31 17](https://user-images.githubusercontent.com/17460410/34642229-9cf82a8e-f320-11e7-9f71-5fad5bdc0dab.png)

How can I run my project ? 

> react-native 0.48.3
> react-native-agora 1.1.0

**Comment by syanbo** [comment]
duplicate   You need to check if you have repeatedly imported the library, etc.
