### ISSUE TITLE
Prevent device lock

### ISSUE THREAD

**Issue by luisfusim** [syanbo/react-native-agora#141]
In Android devices when I'm in a video call after some minutes the device do no detect interactions and then lock it or the turn off the screen, is possible prevent this ?

**Comment by LichKing-2234** [comment]
search this configuration `FLAG_KEEP_SCREEN_ON`, then use it in MainAcitivity

**Comment by luisfusim** [comment]
I'm using this library for iOS and Android https://github.com/marcshilling/react-native-idle-timer to keep the screen only on the calls, but i thing maybe Agora has a config parameter to do this native. But thanks

**Comment by LichKing-2234** [comment]
I will close this issue because it is not active. if there are still problems, you can reopen this issue.
