### ISSUE TITLE
RtcEngine.joinChannel Crashes app on ios but works fine on android

### ISSUE THREAD

**Issue by SafirMonroe** [syanbo/react-native-agora#142]
When I call the RtcEngine.joinChannel method, the app crashes before I can catch the error.
Sometimes the function catches that it is a Native Module error.

**Comment by LichKing-2234** [comment]
any crash log?

**Comment by SafirMonroe** [comment]
Illegal callback invocation from native module error

**Comment by LichKing-2234** [comment]
can you get the log from Android logcat?

**Comment by SafirMonroe** [comment]
its not crashing on android, only ios and if i wrap the function in a try, catch, it crashes before i can get the error.  I used the package react-native-exception-handler to get the crash logs

**Comment by LichKing-2234** [comment]
you can run the app with Xcode, then you can get the crash track

**Comment by SafirMonroe** [comment]
O i didnt have my permission set in info.plist!

Here was the fix
<key>NSMicrophoneUsageDescription</key>
<string>Need microphone access for video calls</string>
<key>NSCameraUsageDescription</key>
<string>$(PRODUCT_NAME) uses camera</string>

**Comment by fluxroom-git** [comment]
I am facing this issue on iOS as well.
Android works fine.


It gives me this error:
![Screenshot 2020-12-15 at 11 19 16 PM](https://user-images.githubusercontent.com/68992038/102252542-37127700-3f2c-11eb-895e-60dcfdf8668a.png)

**Comment by LichKing-2234** [comment]
@fluxroom-git I think it is a 32-bit vs 64-bit issue. could you pls provide more information about your device?
