### ISSUE TITLE
Where can I find setVideoEncoderConfiguration method ?

### ISSUE THREAD

**Issue by Macrow** [syanbo/react-native-agora#144]
我想要在频道内改变推送视频的分辨率等配置，除了初始化时设置好这些参数外，还有没有办法更改？

原生采取调用setVideoEncoderConfiguration来更改，请问这个RN库采用什么方法来更新？找了半天没找到对应的方法。

**Comment by LichKing-2234** [comment]
目前RN没有和原生API对齐，4月底之前会发一个新版本

**Comment by LichKing-2234** [comment]
add it at react-native-agora@beta

**Comment by voslartomas** [comment]
Will you be able to add it alpha version as well?

**Comment by LichKing-2234** [comment]
@voslartomas what version you used?

**Comment by voslartomas** [comment]
2.9.1-alpha.3

**Comment by LichKing-2234** [comment]
try beta version?

**Comment by LichKing-2234** [comment]
> Will you be able to add it alpha version as well? It seems beta is not ready. For example I could not find RtcEngineEvents, it seems this is not exposed out of the API, so I am not able to addEventListener for userJoined.

this comment for alpha or beta?

**Comment by voslartomas** [comment]
I have tried also beta version, but as I wrote before, it seems it's not ready, I've described for example that problem with RctEngineEvents. (I was using latest beta)

**Comment by voslartomas** [comment]
So I was asking if it is possible to add `setVideoEncoderConfiguration` to alpha version as well? Or is there any other method how to change video resolution after you create client?

**Comment by LichKing-2234** [comment]
EventType is string, you should use `engine.addListener('UserJoined', callback);`
```
addListener<EventType extends keyof RtcEngineEvents>(event: EventType, listener: RtcEngineEvents[EventType]): Subscription
```

**Comment by voslartomas** [comment]
I will try that, so it's not possible to add it older version?

**Comment by LichKing-2234** [comment]
@voslartomas the alpha version is too difficult to use and maintain, I suggest you use the beta version

**Comment by voslartomas** [comment]
Ok, will try to rewrite it, thanks.

**Comment by Macrow** [comment]
> I will try that, so it's not possible to add it older version?

you can use this for temporary, I have add setVideoEncoderConfiguration.

https://www.npmjs.com/package/react-native-agora-fix

**Comment by hhemmati81** [comment]
What is the syntax for setting the video encoder configuration? I am trying to set the video dimensions but it doesn't take the settings. Here is my code.

```
const engine = RtcEngine.create(config.appid);

  //enable video
  useEffect(() => {
    let isSubscribed = true;

    if (isSubscribed) {
      const fetch = async () => {
        await (await engine).enableVideo();
        await (await engine).setVideoEncoderConfiguration({
          // The video resolution.
          dimensions: {
            width: 640,
            height: 480,
          },
        });
      };
      fetch();
    }
    return () => (isSubscribed = false);
  }, [engine]);
```

**Comment by LichKing-2234** [comment]
@hhemmati81 you can refer to the .ts file, or our [API doc](https://docs.agora.io/en/Interactive%20Broadcast/API%20Reference/react_native/classes/rtcengine.html#setvideoencoderconfiguration)
