### ISSUE TITLE
Question regarding `getConnectionState`

### ISSUE THREAD

**Issue by marqroldan** [syanbo/react-native-agora#145]
react-native-agora: 2.9.1-alpha.3

Not sure about how it is presented in iOS as I don't have a mac to test and check, but on Android I am getting the connection state as an error.

Checking the iOS code it seems that it's right to resolve it (rather than having a reject block).
But on Android, the code seems to always reject it because res will never equal to 0 (because it's a promise?) and would otherwise resolve `null` if it did equal to 0

I have no experience in native coding, but I probably can follow pattern; I'll try to make a pull request.

**Comment by LichKing-2234** [comment]
thank you for your PR, we will upgrade later
