### ISSUE TITLE
Native Module cannot be null

### ISSUE THREAD

**Issue by HamzaIkram2727** [syanbo/react-native-agora#148]
I integrated react-native-agora into my project. Everything works on android but on ios I am getting this error "Native module cannot be null"

<img width="375" alt="Screenshot 2020-04-03 at 10 58 00 PM" src="https://user-images.githubusercontent.com/47101070/78390855-b78f8280-75fe-11ea-9281-257109d854a9.png">

I have been trying to figure out for 3 days now but cant seem to figure it out. Please if anyone can help.

**Comment by uendar** [comment]
can you send an example on android how it works because i have same problem in android

**Comment by HamzaIkram2727** [comment]
Hi @uendar 
This is probably due to a linking issue. Just make sure that on android you have the following lines in the files specified

In settings.gradle
`include ':react-native-agora'
project(':react-native-agora').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-agora/android')
`
In app/build.gradle
`implementation project(':react-native-agora')`

In MainActivity.java
`new AgoraPackage()`

Just make sure all these lines are present in the android project.
Let me know if this helps.

**Comment by uendar** [comment]
Hi @HamzaIkram2727  

How is the import in  In MainActivity.java for new AgoraPackage()

**Comment by uendar** [comment]
I found it is it :

import io.agora.openlive.AgoraPackage;

**Comment by MrHazimAli** [comment]
@HamzaIkram2727 , can you share how do you init/initiate call for ios ?

**Comment by KarenQiao** [comment]
same issue on ios，any update?

**Comment by LichKing-2234** [comment]
this error means you forget to link the module

**Comment by Ali-hd** [comment]
> this error means you forget to link the module if your RN version <0.60

I'm getting a similar error on android RN 0.63.2 
TypeError: null is not an object (evaluating 'Agora.FPS30')

`const { Agora } = NativeModules;                  //Define Agora object as a native module

const {
  FPS30,
  AudioProfileDefault,
  AudioScenarioDefault,
  Adaptative,
} = Agora;  `

I opened android/settings.gradle but all i found is this
`rootProject.name = 'testAgro'
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'`

I did install react-native-agora but do i have to link it or is there an extra step?

**Comment by LichKing-2234** [comment]
@Ali-hd if you want to use 3.0.0+version, pls refer to our samples

**Comment by gaurav8809** [comment]
> @Ali-hd if you want to use 3.0.0+version, pls refer to our samples

Which example?

**Comment by LichKing-2234** [comment]
@gaurav8809 https://github.com/AgoraIO-Community/react-native-agora/blob/master/samples/README.md

**Comment by gaurav8809** [comment]
> @gaurav8809 https://github.com/AgoraIO-Community/react-native-agora/blob/master/samples/README.md

I refer this https://github.com/EkaanshArora/Agora-RN-Quickstart
But getting error
![Screenshot_1599128669](https://user-images.githubusercontent.com/59197887/92103563-c2dd1900-edfd-11ea-98ff-8da5ee53bd73.png)

**Comment by gaurav8809** [comment]
> @gaurav8809 https://github.com/AgoraIO-Community/react-native-agora/blob/master/samples/README.md

Same issue in this sample
