### ISSUE TITLE
ios Doesn't work with use_frameworks! on 0.61.0 version of ReactNative

### ISSUE THREAD

**Issue by dekameron22** [syanbo/react-native-agora#151]
React native version is 0.61.0

steps are the same as in link ios documentation.
<img width="373" alt="Screenshot 2020-04-08 at 10 08 23" src="https://user-images.githubusercontent.com/4967797/78754858-e3a15f80-7980-11ea-94f5-3189df5ef208.png">

**Comment by mmatheusmmiguel** [comment]
Hi dekameron22,

I solved this by adding `s.static_framework = true` to react-native-agora.podspec and running pod install again

**Comment by dekameron22** [comment]
Hello @mmatheusmmiguel , that worked like a charm!
thanks a lot!
