### ISSUE TITLE
Only mute mic while audio mix playing

### ISSUE THREAD

**Issue by mtalhagaoglu** [syanbo/react-native-agora#152]
Hi. I want to mute microphone while background music keeps playing. I looked android documentation (because it's similar) but i couldn't file any solution.
for example enableLocalAudio() mutes everything not just microphone. is there anybody know how can i do that?

**Comment by LichKing-2234** [comment]
@mtalhagaoglu you can use `AudioMixingOption.replace` 

https://docs.agora.io/en/Video/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#ac56ceea1a143a4898382bce10b04df09``

**Comment by mtalhagaoglu** [comment]
> @mtalhagaoglu you can use `AudioMixingOption.replace` 
> 
> https://docs.agora.io/en/Video/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#ac56ceea1a143a4898382bce10b04df09

if audio mix already started this won't do the job :/

**Comment by LichKing-2234** [comment]
@mtalhagaoglu sorry, we don't support switch at playing.

**Comment by mtalhagaoglu** [comment]
> @mtalhagaoglu sorry, we don't support switch at playing.

sorry for late reply. is there any unofficial way for do that? for example disable mic directly.

**Comment by LichKing-2234** [comment]
you can try  close-mic in native platform code

**Comment by LichKing-2234** [comment]
I will close this issue because it is not active. if there are still problems, you can reopen this issue.

**Comment by mtalhagaoglu** [comment]
use this directly for mute or adjust volume during playing music.

adjustRecordingSignalVolume
