### ISSUE TITLE
unknown type name 'namespace'  

### ISSUE THREAD

**Issue by HuangZhe007** [syanbo/react-native-agora#157]
react-native 版本 0.59.10
xcode 版本 11.3
我在集成react-native-agora会报错
"Unknown type name 'namespace"，和expected ';' after top level declarator
上网搜索发现oc的话将.m文件改成.mm就可以解決，但是Swift不行

请问有什么办法吗，谢谢

**Comment by HuangZhe007** [comment]
![image](https://user-images.githubusercontent.com/45168628/79296779-f7177200-7f0e-11ea-8d0c-57e8d09b55a2.png)

**Comment by HuangZhe007** [comment]
信息如上

**Comment by LichKing-2234** [comment]
有试过在podfile中加`use_frameworks!`么，同时，podspec需要配置成static #151

**Comment by HuangZhe007** [comment]
我通过移除libRCTAgora.a来解决这个错误，我不知道这样的做法是不是正确的

**Comment by LichKing-2234** [comment]
移除了，就不会起作用了

**Comment by HuangZhe007** [comment]
但我现在可以正常的使用它

**Comment by LichKing-2234** [comment]
好吧，如果还有问题欢迎随时提出
