### ISSUE TITLE
Border radius not working on android. Working on iOs

### ISSUE THREAD

**Issue by musmanfaisal** [syanbo/react-native-agora#158]
I am trying to show local video stream to the user. I have applied the border radius to the local video stream. On iOs, I can see it working fine. But on android, it doesn't get applied.
![android](https://user-images.githubusercontent.com/61688410/79422197-df56f100-7fd5-11ea-936b-247fe208c1e1.png)
![iPhone](https://user-images.githubusercontent.com/61688410/79422211-e7169580-7fd5-11ea-9768-87953b654d5a.jpeg)

My JSX object is: 

`<AgoraView style={{
                        width: width / 3, //width is obtained from device width
                        height: width / 2,
                        backgroundColor: '#ddd',
                        position: 'absolute',
                        top: 50,
                        right: 20,
                        borderRadius: 15,
                        overflow: 'hidden',
                        zIndex: 3
                    }}
                        zOrderMediaOverlay={true}
                        showLocalVideo />
`
if I set zOrderMediaOverlay false, then on android, the local video stream does not appear at all.
Kindly fix this issue

**Comment by LichKing-2234** [comment]
We use SurfaceView on the Android platform, so it does not support radius.
We will upgrade it before Q3, it will support TextureView.

**Comment by LichKing-2234** [comment]
add texture view at  react-native-agora@beta
