### ISSUE TITLE
create rtc engine failed

### ISSUE THREAD

**Issue by uendar** [syanbo/react-native-agora#160]
I get this error 

I was following this example :  https://www.agora.io/en/blog/how-to-build-a-react-native-video-calling-app-using-agora/

dependecies:
```
 "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-agora": "^2.9.1-alpha.3",
    "react-native-gesture-handler": "^1.4.1",
    "react-native-reanimated": "^1.8.0",
    "react-native-router-flux": "^4.2.0",
    "react-native-screens": "^2.5.0",
    "react-native-twilio-video-webrtc": "^1.0.1",
    "react-native-vector-icons": "^6.6.0"

```
But when i run the project i het the error

![Screenshot_20200416-204102](https://user-images.githubusercontent.com/13899301/79494674-b2312f80-8023-11ea-890d-d8172e562993.png)

**Comment by LichKing-2234** [comment]
you may forget to add some init config

**Comment by LichKing-2234** [comment]
I will close this issue because it is not active. if there are still problems, you can reopen this issue.
