### ISSUE TITLE
null is not an object Agora.FPS30

### ISSUE THREAD

**Issue by uendar** [syanbo/react-native-agora#161]
```
const {Agora} = NativeModules;
const {
  FPS30,
  AudioProfileDefault,
  audioScenarioDefault,
  Adaptive
} = Agora;
```

I get this error when i implement above code in class component.

**Comment by LichKing-2234** [comment]
Agora is a null object, you may forget to npm install or react-native link?

**Comment by LichKing-2234** [comment]
I will close this issue because it is not active. if there are still problems, you can reopen this issue.

**Comment by pdSatyam** [comment]
Also getting same problem. This issue needs to be reopened..I could not find the answer to this problem in other issues of react-native-agora.
Currently installed -> react-native-agora^3.0.1-rc.5

**Comment by LichKing-2234** [comment]
@gaurav8809 @pdSatyam I believe your code is too old.
pls refer to https://github.com/AgoraIO-Community/Agora-RN-Quickstart/blob/master/App.tsx
