### ISSUE TITLE
RtcEngine.joinChannel not firing the on('userJoined') event at all.

### ISSUE THREAD

**Issue by prateekchachra** [syanbo/react-native-agora#162]
This was working perfectly a while back. 

The event doesn't fire anymore.

**Comment by LichKing-2234** [comment]
any log? you can provide our SDK log

**Comment by LichKing-2234** [comment]
you may try react-native-agora@beta

**Comment by LichKing-2234** [comment]
I will close this issue because it is not active. if there are still problems, you can reopen this issue.
