### ISSUE TITLE
java.lang.string cannot be cast to com.facebook.react.bridge.readablenativemap

### ISSUE THREAD

**Issue by cutenesss** [syanbo/react-native-agora#164]
I got this when using Rtc.startAudioRecording('/sdcard/emulated/0/aac.aac' ,0). Did i use this in an incorrect way and do you have example for this?

**Comment by LichKing-2234** [comment]
public static startAudioRecording(options: AudioRecordingOption): Promise<any>

**Comment by cutenesss** [comment]
Yes, i read that from the doc already. AudioRecordingOption include filePath: string and quality: int but from what i have here, filePath make up this issue: 
![Screenshot_2020-04-22-19-44-16-10_4e0e83bd4acc1607324b13ccc3ef5239](https://user-images.githubusercontent.com/47804907/79983260-b3ee6d80-84d1-11ea-9d33-8c5c5cfab9bf.png)

**Comment by LichKing-2234** [comment]
options is a object, not a string

**Comment by cutenesss** [comment]
oh yes, thank you so much. Btw, is there any way to record the video call? Not just audio but also the screen

**Comment by LichKing-2234** [comment]
https://docs.agora.io/en/cloud-recording/product_cloud_recording?platform=All%20Platforms
