### ISSUE TITLE
Video LIVE streams

### ISSUE THREAD

**Issue by voslartomas** [syanbo/react-native-agora#166]
Hello, I am trying to create video LIVE streaming as seen in this example.

https://docs.agora.io/en/Interactive%20Broadcast/start_live_android?platform=Android

But I can't see any setChannelProfile/setupRemoteVideo method for example.

**Comment by LichKing-2234** [comment]
this doc just for Android platform, you can refer https://syanbo.github.io/react-native-agora/globals.html
