### ISSUE TITLE
'Unknown type name 'namespace' after trying to add the iOS build

### ISSUE THREAD

**Issue by prateekchachra** [syanbo/react-native-agora#168]
I'm trying to build iOS and getting:

 'Could not build module 'AgoraRtcEngineKit'
Unknown type name 'namespace'

Cocoapods is 1.8.4
XCode is 10.2.1

React native 0.61.2

**Comment by LichKing-2234** [comment]
try to add `s.static_framework = true` into `react-native-agora.podspec`.

**Comment by LichKing-2234** [comment]
then run `pod install`
