### ISSUE TITLE
IOS Cannot read property 'init' of undefined

### ISSUE THREAD

**Issue by xvbo** [syanbo/react-native-agora#17]
IOS Cannot read property 'init' of undefined

**Comment by Geek-ch** [comment]
@xvbo   我一开始也会这样,那是因为iOS没有导入成功, 把RCTAgora.xcodeproj导入到lib,然后添加.a文件就行了.

**Comment by yudhis8** [comment]
same here but i got this error on android

**Comment by yudhis8** [comment]
> same here but i got this error on android

umm i think i fix this error by add new AgoraPackage() in MainApplication.java
this error happend because react-native link not adding AgoraPackage() in MainApllication.java

**Comment by Matrixbirds** [comment]
thx. @Geek-ch @yudhis8 have resolved the problem.
