### ISSUE TITLE
setEnableSpeakerphone 无法切换扩音器

### ISSUE THREAD

**Issue by HuangZhe007** [syanbo/react-native-agora#170]
华为p30pro 调用setEnableSpeakerphone(true)无法切换为外放，promise.then返回为调用成功的null但是audioRouteChanged没有收到回掉也没有成功切换为外放模式，手机没有处于耳机，蓝牙耳机等状态

**Comment by LichKing-2234** [comment]
有测试其他Android手机么

**Comment by HuangZhe007** [comment]
好多手机出现这个问题

**Comment by HuangZhe007** [comment]
debug会有这个问题 release这个问题会消失，release一切正常

**Comment by sebazh** [comment]
I also faced with issue that switching from Speaker to Earpiece and vise versa on Android by 
RtcEngine.setEnableSpeakerphone(enable) has no effect. Could you please point how to solve that

**Comment by sebazh** [comment]
And i have it in release mode also

**Comment by LichKing-2234** [comment]
you can try this function and set the scenario param to GAME_STREAMING.
https://docs.agora.io/en/Interactive%20Broadcast/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#a34175b5e04c88d9dc6608b1f38c0275d
