### ISSUE TITLE
v3.0.0 

### ISSUE THREAD

**Issue by techechelons** [syanbo/react-native-agora#171]
As v3.0.0 is already released in march. When is this version included in SDK? Any possibility sooner for new SDK to arrive for this version?

**Comment by marqroldan** [comment]
I'm actually waiting for this too, but I don't think this project is under Agora.

**Comment by LichKing-2234** [comment]
@techechelons @marqroldan 
We have published react-native-agora@beta, you can try it.
but there are many changes from v2.

**Comment by marqroldan** [comment]
That's really great to hear! I'll find time to check how much of a difference is 3.0.0 from 3.1.0
I've recently reported a bug where stream from the WebSDK is flipped on Native SDKs (issue for iOS 13.4.1 and up only)

**Comment by LichKing-2234** [comment]
@marqroldan what is 3.1.0?

**Comment by AdamFu** [comment]
@LichKing-2234 你好，请问3.0的正式版，大概什么时候能发布？看dev已经到beta.4了

**Comment by LichKing-2234** [comment]
@AdamFu beta测试一段时间，没啥问题会发布正式版

**Comment by AdamFu** [comment]
@LichKing-2234 好的，谢谢。我看先安排按beta版本接入，到时候再升级到正式版

**Comment by LichKing-2234** [comment]
@AdamFu 好的，beta版本使用遇到问题或者有bug，欢迎随时提issue或者PR，我会尽快处理修复

**Comment by hirapong** [comment]
@LichKing-2234 Hello. Do you have any updates? I'm waiting for v3.0.0.

**Comment by LichKing-2234** [comment]
@hirapong have you try it? any issues? welcome to comment here.

**Comment by hirapong** [comment]
@LichKing-2234  Hello. I'm testing v3.0.0-beta4. 
Is there any migration guide or example project for ReactNative?

**Comment by LichKing-2234** [comment]
@hirapong 
here is a example of the new version
https://github.com/EkaanshArora/Agora-RN-Quickstart/tree/sdk-v3

**Comment by hirapong** [comment]
@LichKing-2234 Thank you for sharing the example. I completed the version update for our system successfully.

**Comment by LichKing-2234** [comment]
by the way, I have fixed some bugs at 3.0.1-beta.3, if you found some bug when you use it, welcome to create issues or create a pull request.
