### ISSUE TITLE
混合音频的相关几个接口有问题

### ISSUE THREAD

**Issue by sihuayin** [syanbo/react-native-agora#172]
react-native-agora/ios/RCTAgora/RCTAgora.m  -> line 934

RCT_EXPORT_METHOD(getAudioMixingDuration
                  :(RCTPromiseResolveBlock)resolve
                  reject:(RCTPromiseRejectBlock)reject) {
  NSInteger res = [self.rtcEngine getAudioMixingDuration];
  if (res == 0) { // 改为 >= 0
    resolve(nil); // 改为 resolve(@(res).stringValue);
  } else {
    reject(@(-1).stringValue, @(res).stringValue, nil);
  }
}

line：971
RCT_EXPORT_METHOD(getAudioMixingCurrentPosition
                  :(RCTPromiseResolveBlock)resolve
                  reject:(RCTPromiseRejectBlock)reject) {
  NSInteger res = [self.rtcEngine getAudioMixingDuration]; // 改为getAudioMixingCurrentPosition
  if (res == 0) { // 改为 >= 0
    resolve(nil); // 改为 resolve(@(res).stringValue);
  } else {
    reject(@(-1).stringValue, @(res).stringValue, nil);
  }
}

**Comment by LichKing-2234** [comment]
fixed in 2.9.1-alpha.6
