### ISSUE TITLE
3.0.0-beta.4 pod install error 'target has libraries with conflicting names: libcrypto.a.'

### ISSUE THREAD

**Issue by altinredapple** [syanbo/react-native-agora#175]
I have been trying to use version 3.0.0-beta.4 (Have also tried with beta 1, 2 and 3) with no success. I get the below error when running "pod install" on an existing and fresh react native project. 

Console Output from pod install command:
`Detected React Native module pod for react-native-agora
Analyzing dependencies
Downloading dependencies
Installing AgoraRtcEngine_iOS_Crypto (3.0.0)
Installing react-native-agora (3.0.0-beta.4)
[!] The 'Pods-[project name]' target has libraries with conflicting names: libcrypto.a.`

**Comment by LichKing-2234** [comment]
@altinredapple you may use RN 0.62.x, you need to disable Flipper in your Podfile and remove the code about Flipper, I will upgrade the README

```
# Enables Flipper.
#
# Note that if you have use_frameworks! enabled, Flipper will not work and
# you should disable these next few lines.
add_flipper_pods!
```

**Comment by altinredapple** [comment]
Yup that worked! Thanks so much for your quick reply.
