### ISSUE TITLE
Keep audio on background

### ISSUE THREAD

**Issue by gwendall** [syanbo/react-native-agora#176]
Right now, switching to another app or locking the phone shuts the sound down. Is there a way to keep it running ?

**Comment by LichKing-2234** [comment]
you may need to add foreground service to the android code.
https://docs.agora.io/en/faq/android_background

**Comment by fritzfr** [comment]
@LichKing-2234 Any chance you have more info on this? Shouldn't this be included in this SDK?

**Comment by LichKing-2234** [comment]
you can refer to this comment.
https://github.com/AgoraIO/Flutter-SDK/issues/28#issuecomment-717667342

**Comment by tak-bro** [comment]
@LichKing-2234 Where should I add the code `setParameters('{"che.audio.opensl":true}');`? Could you please tell me how to add Android code on React Native project?

**Comment by LichKing-2234** [comment]
@tak-bro RN also export `setParameters` function

**Comment by tak-bro** [comment]
@LichKing-2234 Thanks. Is it available from version 3.0.0 or higher?

**Comment by tak-bro** [comment]
> @tak-bro RN SDK also export `setParameters` function

@LichKing-2234 Thanks. Is it available from version 3.0.0 or higher?

**Comment by tak-bro** [comment]
> @tak-bro RN SDK also export `setParameters` function

Thanks!

**Comment by eyalcohen4** [comment]
Hi fellows,
I can't find `setParameters` on react-native nor react-native-agora package.
wdymn when you say `RN SDK also export setParameters function`?

@LichKing-2234

**Comment by LichKing-2234** [comment]
@eyalcohen4 here.
https://github.com/AgoraIO-Community/react-native-agora/blob/master/src/common/RtcEngine.native.ts#L496

**Comment by arya-man** [comment]
@LichKing-2234 what do you mean by export the function? Is `await this.agora.setParameters('{"che.audio.opensl":true}');` not enough? If so, what extra thing are we supposed to do?

**Comment by LichKing-2234** [comment]
@eyalcohen4 any problem?

**Comment by dhavalagile** [comment]
audio not working when app goes in backgroud after 1 min.

I had set await _engine.setParameters('{"che.audio.opensl":true}');

**Comment by LichKing-2234** [comment]
@dhavalagile you should start a foreground service
https://docs.agora.io/en/Interactive%20Broadcast/faq/android_background

**Comment by arya-man** [comment]
Any success on starting a foreground service? I have no android coding experience, so for me its super confusing

**Comment by hongzhou85** [comment]
How about for iOS? any web document or information on this? I want to keep audio on as well when app goes into background.

**Comment by LichKing-2234** [comment]
@hongzhou85 https://github.com/AgoraIO-Community/react-native-agora/issues/176#issuecomment-717670413

**Comment by hongzhou85** [comment]
Does this need to add background processing and fetch to the info,plist for iOS on xcode?

**Comment by hongzhou85** [comment]
I have successfully enabled this on iOS by enabling the VoIP and Audio modes. How do we do it on React native Android?

**Comment by LichKing-2234** [comment]
I have commented above.

**Comment by LichKing-2234** [comment]
@hongzhou85 I have commented above.

**Comment by jaymovaliya** [comment]
@hongzhou85 , can you share some code SS for doing this?

**Comment by hongzhou85** [comment]
> Although we will not integrate Callkit (iOS) and ConnectionService (Android) in the SDK in the near future, if you just want the app to keep calling in the background, you can call `setParameters('{"che.audio.opensl":true}');` on the Android platform(>2.3.2), enable `Background Modes` and select the `Audio, Airplay, and Picture in Picture`, and `Voice over IP` options on the IOS platform.
> 
> ![image](https://user-images.githubusercontent.com/9312526/97386080-0770c680-190e-11eb-90f0-9fa16150a765.png)

@jaymovaliya this one for ios would work

**Comment by hongzhou85** [comment]
For Android, I'm going to attempt this for foreground service. 
https://github.com/Raja0sama/rn-foreground-service

Another paid alternative may be this:
https://notifee.app/react-native/docs/android/foreground-service

Otherwise, for React Native you would have to code the headless js, which has little example on how to do it.

**Comment by shahabt24** [comment]
> I have successfully enabled this on iOS by enabling the VoIP and Audio modes. How do we do it on React native Android?

How did you do this?
I checked those options in background mode in XCode but the app still closes after 5 second going to background

**Comment by OscarJuniusDev** [comment]
> 
My app also closes after exactly 5 seconds in background, although the user is in an active call. Have you found a solution for this?

**Comment by shahabt24** [comment]
> > 
> 
> My app also closes after exactly 5 seconds in background, although the user is in an active call. Have you found a solution for this?


Hi,
Sorry for delay, yes I found the solution,
In **IOS**, you have to put all the functions related to redux and storage in this:

```
if (AppState.currentState === 'active') {
      //do whatever you want
}
```

In **ANDROID**, you have to run a foreground service which is listed below,

**ANDROID FOREGROUND SERVICE:**

I use this package for foreground service: @supersami/rn-foreground-service
--------------------------------------------------------------------------------------------------
```
import ReactNativeForegroundService from '@supersami/rn-foreground-service';

export const initForegroundService = () => {
  return new Promise((result) => {
    ReactNativeForegroundService?.add_task(() => {}, {
      delay: 100,
      onLoop: true,
      taskId: 'taskid',
      onError: (e: any) => {},
    });
    result(true);
  });
};
export const removeForegroundService = () => {
  ReactNativeForegroundService?.remove_task('taskid');
};

export const startForegroundService = () => {
  ReactNativeForegroundService?.start({
    id: 144,
    title: '...',
    message: '...',
  });
};
export const stopForegroundService = () => {
  if (ReactNativeForegroundService) {
    ReactNativeForegroundService?.stop();
  }
};
```

**Comment by SamarthKejriwal** [comment]
Follwing this [#176 (comment)](https://github.com/AgoraIO-Community/react-native-agora/issues/176#issuecomment-717670413) approach has rejected my ios app from app store saying that - 

```
Your app declares support for VoIP in the UIBackgroundModes key in your Info.plist, but it does not include any Voice over IP services.

Next Steps

To resolve this issue, please revise your app to either add VoIP features or remove the "voip" setting from the UIBackgroundModes key.

We recognize that VoIP can provide "keep alive" functionality that is useful for many app features. However, using VoIP in this manner is not the intended purpose of VoIP.
```

**Comment by hongzhou85** [comment]
> Follwing this [#176 (comment)](https://github.com/AgoraIO-Community/react-native-agora/issues/176#issuecomment-717670413) approach has rejected my ios app from app store saying that -
> 
> ```
> Your app declares support for VoIP in the UIBackgroundModes key in your Info.plist, but it does not include any Voice over IP services.
> 
> Next Steps
> 
> To resolve this issue, please revise your app to either add VoIP features or remove the "voip" setting from the UIBackgroundModes key.
> 
> We recognize that VoIP can provide "keep alive" functionality that is useful for many app features. However, using VoIP in this manner is not the intended purpose of VoIP.
> ```

I believe this reply means you have not utilized any VoIP features in your App, so including it is not required. Appstore do not accept additional permission request without having actual features using the permission.

**Comment by nyoung697** [comment]
Hey @SamarthKejriwal did you get this sorted? My app just got rejected from Apple for the exact same reason. Why is this being suggested as an approach?  Is there another solution to keep audio in background?

**Comment by nyoung697** [comment]
@cranberry08 I removed the VOIP background mode and just left in the Audio, Air Play, Picture in Picture.

https://docs.agora.io/en/Voice/ios_audio?platform=iOS#additional-settings-and-permissions

Those docs there led me to try that out.

Apple accepted our app and it seems to work fine when in the background.

Apple review did ask me to make a video demonstrating why I needed background audio capabilities.

**Comment by cranberry08** [comment]
Hello Nick,

Thank you!! That was very helpful. Good luck to you.

**Comment by abhijith-sys** [comment]
is there any updates form agora sdk for enabling the voice call even if the app is in the background?.what is the best solution for this problem

**Comment by jfbourne** [comment]
Same issue here, any built-in solution from Agora to achieve this on Android without having to write a java service to do this?

**Comment by rajeshbejugam** [comment]
After a lot of pain and research, found a way to make this work.

When using Agora you need your app to start a foreground service to be able to receive audio while the app is in the background. While using react-native, you can have this done for you by using react-native-call-keep. The catch however is it does not work off the shelf. You need to adjust the AndroidManifest.xml entry for call keep to get it to work.

Specifically change change the android:foregroundServiceType property to include "microphone|mediaPlayback". Also ensure you have declared necessary permissions in manfiest file as per https://docs.agora.io/en/help/quality-issues/android_background.

    <service android:name="io.wazo.callkeep.VoiceConnectionService" android:label="Wazo" android:exported="false" android:permission="android.permission.BIND_TELECOM_CONNECTION_SERVICE" android:foregroundServiceType="phoneCall|microphone|mediaPlayback">
      <intent-filter>
        <action android:name="android.telecom.ConnectionService"/>
      </intent-filter>
    </service>
