### ISSUE TITLE
What we share on share button to other platform

### ISSUE THREAD

**Issue by varunsdcet** [syanbo/react-native-agora#177]
@Matrixbirds We have to build share button and share which method we get data to live streaming to other platform like whatsapp

**Comment by LichKing-2234** [comment]
could this method helps you?
https://docs.agora.io/en/Voice/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#aeb1a5691094a10cb047d106d6c6c32b7
