### ISSUE TITLE
AndroidX Support

### ISSUE THREAD

**Issue by sin2** [syanbo/react-native-agora#178]
Can this library be updated to support AndroidX. Project fails to build on newer versions of react-native.

**Comment by LichKing-2234** [comment]
you can try the beta version

**Comment by sin2** [comment]
Currently using 2.9.1-alpha.3 and getting the following errors:
`> Task :react-native-agora:compileReleaseJavaWithJavac FAILED
/Users/sinthu/Documents/git/rally-mobile/node_modules/react-native-agora/android/src/main/java/com/syan/agora/AgoraVideoView.java:10: error: package android.support.annotation does not exist
import android.support.annotation.RequiresApi;
                                 ^
/Users/sinthu/Documents/git/rally-mobile/node_modules/react-native-agora/android/src/main/java/com/syan/agora/AgoraManager.java:4: error: package android.support.v7.widget does not exist
import android.support.v7.widget.LinearLayoutCompat;
                                ^
/Users/sinthu/Documents/git/rally-mobile/node_modules/react-native-agora/android/src/main/java/com/syan/agora/AgoraModule.java:4: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/Users/sinthu/Documents/git/rally-mobile/node_modules/react-native-agora/android/src/main/java/com/syan/agora/AgoraModule.java:2718: error: cannot find symbol
                           @Nullable WritableMap params) {
                            ^
  symbol:   class Nullable
  location: class AgoraModule
4 errors`

I am able to patch the following imports with the androidx equivalent and its working. However, I would like to see this formally addressed.

**Comment by LichKing-2234** [comment]
@sin2 have your try the beta version?

**Comment by sin2** [comment]
Updated to 3.0.0-beta.4 and its working. Thanks!
