### ISSUE TITLE
injectStream

### ISSUE THREAD

**Issue by mtalhagaoglu** [syanbo/react-native-agora#182]
Hi. I want to watch a youtube video with my audience. i found this link (https://syanbo.github.io/react-native-agora/classes/rtcengine.html#addinjectstreamurl) but it says live video stream. youtube videos not live. does it support that? and i couldn't find any resume start stop function for that. is that even possible?

**Comment by LichKing-2234** [comment]
you should add a custom video source, but it only supports by native SDK.
https://github.com/AgoraIO/Advanced-Video/blob/master/Android/lib-external-video/src/main/java/io/agora/advancedvideo/externvideosource/localvideo/LocalVideoInput.java
