### ISSUE TITLE
Streaming an mp4 file

### ISSUE THREAD

**Issue by tinyCoder32** [syanbo/react-native-agora#183]
Hi, how to I set a custom video source to a static media file, like shown in this example:

https://webdemo.agora.io/agora-web-showcase/examples/Agora-Custom-VideoSource-Web/

**Comment by LichKing-2234** [comment]
you can only add it to native code by yourself.

**Comment by tinyCoder32** [comment]
Thanks for the quick response, can you lead me to the shortest way to do it please? a link would be enough.

**Comment by LichKing-2234** [comment]
[android demo](https://github.com/AgoraIO/Advanced-Video/blob/master/Android/lib-external-video/src/main/java/io/agora/advancedvideo/externvideosource/localvideo/LocalVideoInput.java)
[doc](https://docs.agora.io/en/Interactive%20Broadcast/custom_video_android?platform=Android)
