### ISSUE TITLE
Could not find the following native modules: react-native-agora

### ISSUE THREAD

**Issue by tdevere** [syanbo/react-native-agora#184]
Platform: Mac
Following Sample: https://reactnative.dev/docs/0.61/getting-started
Ran:
npm install --save react-native-agora
react-native link react-native-agora

I receive the following warning: 

warn Calling react-native link [packageName] is deprecated in favor of autolinking. It will be removed in the next major release. 
Autolinking documentation: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md 

info Linking "react-native-agora" iOS dependency 
info iOS module "react-native-agora" has been successfully linked 
info Linking "react-native-agora" Android dependency 
info Android module "react-native-agora" has been successfully linked 

When I try to run the code, I get the following errors:

MY-LAPTOP:mynewreactproject tdevere$ npx react-native run-ios 

error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 

  - react-native-agora (to unlink run: "react-native unlink react-native-agora") 

This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers. 

Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md 

error Could not find the following native modules: react-native-agora. Did you forget to run "pod install" ? 

What am I missing?

**Comment by LichKing-2234** [comment]
you may miss `pod install`

**Comment by tdevere** [comment]
@LichKing-2234 Thanks for the response. I have no pod file at all. Just want is available to the getting started default react-native sample.

**Comment by LichKing-2234** [comment]
@tdevere if you want to use auto-linking, you must use RN 0.60.+, the Podfile will create when you init the project.

**Comment by tdevere** [comment]
Wow. I'm dull. You're correct. I did have pod file. I ran pod install and I get. No podspec found for 'react-native-agora' in '../node_modules/react-native-agora'

**Comment by tdevere** [comment]
I figured out that last problem. thank you @LichKing-2234 very helpful!!! got it installed
