### ISSUE TITLE
localVideo

### ISSUE THREAD

**Issue by bamaarintoko** [syanbo/react-native-agora#185]
local video not showing on iOS device

**Comment by LichKing-2234** [comment]
we need more info about your problem

**Comment by tinyCoder32** [comment]
Same problem here on iOS.

**Comment by LichKing-2234** [comment]
what version did you use?

**Comment by tinyCoder32** [comment]
The latest, but not the beta.

**Comment by mtalhagaoglu** [comment]
you need to enable local video on ios devices. enableLocalVideo(true)

at least it works for me :)

**Comment by bamaarintoko** [comment]
@mtalhagaoglu yeah its work, but when another user join the chanel, the local video disappear
