### ISSUE TITLE
Error while updating property 'remoteUid' of a view managed by RCTAgoraVideoView  null

### ISSUE THREAD

**Issue by jiyunkeji** [syanbo/react-native-agora#186]

**Comment by jiyunkeji** [comment]
![Screenshot_20200515_151757_com rmonlineeducation](https://user-images.githubusercontent.com/50569560/82022586-81462800-96bf-11ea-938e-1c920d786962.jpg)

**Comment by LichKing-2234** [comment]
try the beta version?

**Comment by jiyunkeji** [comment]
> try the beta version?

"react-native-agora": "^2.9.1-alpha.3"

**Comment by jiyunkeji** [comment]
> try the beta version?

I use ts to develop rn。I find quick start demo run no problem ,but it uses js.
<AgoraView style={[CommonStyles.flex1]} zOrderMediaOverlay={false}
          remoteUid={1589515290} showLocalVideo={false} mode={1} />
if i add this node, this bug appears.

**Comment by LichKing-2234** [comment]
you can refer to this demo.
https://github.com/EkaanshArora/Agora-RN-Quickstart/tree/sdk-v3

**Comment by jiyunkeji** [comment]
> you can refer to this demo.
> https://github.com/EkaanshArora/Agora-RN-Quickstart/tree/sdk-v3

I have run this project, it is no problem. But i use ts to develop my project.
Other problem:  In ts ,this four property need to set value.
* @property mode: {@link AgoraViewMode}, this property will setup video render mode. You could see more [details](https://docs.agora.io/en/Interactive%20Broadcast/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#ac08882c4d0ec47b329900df169493673)
 * @property showLocalVideo: boolean, this property will render local video, NOTICE: IF YOU SET showLocalVideo YOU CANNOT SET remoteUid
 * @property remoteUid: number, this property will render video with remote uid, NOTICE: IF YOU SET remoteUid YOU CANNOT SET showLocalVideo
 * @property zOrderMediaOverlay: boolean, this property will working for android side and it likes zIndex behaviour on web side.
 *

**Comment by jiyunkeji** [comment]
> you can refer to this demo.
> https://github.com/EkaanshArora/Agora-RN-Quickstart/tree/sdk-v3

你好，我自己写了超简单的demo，还是会报错，不过不是这个错。https://github.com/jiyunkeji/AgoraTest.git

问题描述
1、有空帮我看一个很简单，集成Agora的界面呗。执行这个，react-native run-android --variant=release，android应用删除了，然后第一次装，可以正常打开界面。如果不删，直接在执行react-native run-android --variant=release，程序直接崩了。这个是我自己写的只集成Agora。

2、这四个参数都有传，我看定义里是说remoteUid，不传showLocalVideo，反之？？？


> you can refer to this demo.
> https://github.com/EkaanshArora/Agora-RN-Quickstart/tree/sdk-v3
你好，我自己写了超简单的demo，还是会报错，不过不是这个错。https://github.com/jiyunkeji/AgoraTest.git

问题描述
1、有空帮我看一个很简单，集成Agora的界面呗。执行这个，react-native run-android --variant=release，android应用删除了，然后第一次装，可以正常打开界面。如果不删，直接在执行react-native run-android --variant=release，程序直接崩了。这个是我自己写的只集成Agora。

2、这四个参数都有传，我看定义里是说remoteUid，不传showLocalVideo，反之？？？
![Uploading image.png…]()

**Comment by syanbo** [comment]
[https://github.com/agoraio-community/agora-rn-quickstart](url)
可以先参考一下示例

我看了下你代码流程是不对的
你需要初始完成加入房间 才去进行 render AgoraView 组件
