### ISSUE TITLE
Local Video freezes after client role changed

### ISSUE THREAD

**Issue by isumesh** [syanbo/react-native-agora#187]
Hi @LichKing-2234 

I am changing the client role using `RtcEngine.setClientRole(2);` dynamically.
But as soon as i do it, the local video stream freezes.
I tried `RtcEngine.setClientRole(2).then(() => {
          RtcEngine.enableLocalVideo(true);
          RtcEngine.startPreview();
        });` but no change.

**Comment by syanbo** [comment]
2 = AgoraClientRoleAudience    no video
1 = AgoraClientRoleBroadcaster

**Comment by isumesh** [comment]
Hi thank you for your reply @syanbo 
When client joins the channel as channelProfile: 1, i am running the following code on successful join of channel `RtcEngine.enableLocalVideo(true);
      RtcEngine.startPreview();` this enables the local stream. Then i change the client role using `RtcEngine.setClientRole(1)`local stream is still visible. But after changing the role to 2, local video freezes and i am unable to load it again.

**Comment by LichKing-2234** [comment]
> Hi thank you for your reply @syanbo
> When client joins the channel as channelProfile: 1, i am running the following code on successful join of channel `RtcEngine.enableLocalVideo(true); RtcEngine.startPreview();` this enables the local stream. Then i change the client role using `RtcEngine.setClientRole(1)`local stream is still visible. But after changing the role to 2, local video freezes and i am unable to load it again.

The Audience can not capture video.
