### ISSUE TITLE
How can I load the native SDK's into an expo project?

### ISSUE THREAD

**Issue by shamoons** [syanbo/react-native-agora#188]
I know I have to `expo eject`, but then what?

**Comment by LichKing-2234** [comment]
I think you can run expo project at a physical device but it does not support web because it can not load the native plugin.

**Comment by LichKing-2234** [comment]
first, run [`expo eject`](https://docs.expo.io/bare/exploring-bare-workflow/#existing-expo-managed-workflow-apps) to switch to the bare workflow.
second, run [`npx react-native run-ios` `npx react-native run-android`](https://docs.expo.io/bare/hello-world/) to run application.

**Comment by EkaanshArora** [comment]
With the release of Expo SDK 42, it’s now possible to customize the native runtime of your apps using custom development clients, this means that you can now use libraries that contain native code (like this one) with Expo without having to resort to the bare workflow.

You can read this [blog](https://www.agora.io/en/blog/building-a-video-calling-app-using-the-agora-sdk-on-expo-react-native/) to learn how to build a video calling app with Agora using Expo custom development clients.
