### ISSUE TITLE
ios按照教程一步一步安装之后还是报这个错误。

### ISSUE THREAD

**Issue by TXLtianxiaolong** [syanbo/react-native-agora#191]
<img width="2378" alt="WeChatdb6cb4c7b9cade9047265e65fc734382" src="https://user-images.githubusercontent.com/15356406/82201142-7e06a280-9932-11ea-9fcf-802426152fe9.png">

**Comment by syanbo** [comment]
react-native info 
贴一下

**Comment by TXLtianxiaolong** [comment]
> react-native info
> 贴一下

贴了图片的，可能是你没加载出来

**Comment by syanbo** [comment]
确保一下你的 pod install 是成功的。
这个错误是RN自带的库文件没install到项目中
你可以检查Pod文件夹下React-Core/Default/Views/RCTViewManager.h 是否存在

**Comment by TXLtianxiaolong** [comment]
> 确保一下你的 pod install 是成功的。
> 这个错误是RN自带的库文件没install到项目中
> 你可以检查Pod文件夹下React-Core/Default/Views/RCTViewManager.h 是否存在


pod install是成功的，没有报错
React-Core文件夹只在pods/development文件夹下面找到。
在pods/development pods/React-Core/Default/Views/RCTViewManager.h 存在这个文件
<img width="2250" alt="WeChatabc922a0b35d53696a7cad1d7d65786b" src="https://user-images.githubusercontent.com/15356406/82305926-ecaa3580-99f0-11ea-9152-43db212c1709.png">

![1589878120935](https://user-images.githubusercontent.com/15356406/82306011-0e0b2180-99f1-11ea-9f21-eb8178766323.jpg)

**Comment by TXLtianxiaolong** [comment]
![1589879862775](https://user-images.githubusercontent.com/15356406/82308907-064d7c00-99f5-11ea-861c-13503c2f263d.jpg)

**Comment by syanbo** [comment]
你把错误地方换成
#import "RCTViewManager.h"
清掉缓存跑一下
我这边和你一样的环境运行都是正常的
