### ISSUE TITLE
你好，rn中，我离开界面的时候调的离开视频直播通道，离开实时聊天通道的时候报错了。他们都是异步的

### ISSUE THREAD

**Issue by jiyunkeji** [syanbo/react-native-agora#193]
![9469A14F8CDB7AEC776B940810E382B2](https://user-images.githubusercontent.com/50569560/82403669-f637aa00-9a91-11ea-8d0a-55ce1e72c887.jpg)
![49B0CECE4770F9A623BDF0C582385F6D](https://user-images.githubusercontent.com/50569560/82403670-f768d700-9a91-11ea-9203-9ff00b153d9c.jpg)
![B2B6FAB37AFD75D3AC9195FD66992B34](https://user-images.githubusercontent.com/50569560/82403673-f9329a80-9a91-11ea-94de-172eb1441b35.jpg)
<img width="368" alt="image" src="https://user-images.githubusercontent.com/50569560/82403695-0485c600-9a92-11ea-9d46-30eecb24ee6e.png">

**Comment by LichKing-2234** [comment]
comment at https://github.com/AgoraIO/agora-react-native-rtm/issues/9
