### ISSUE TITLE
beta版本使用问题

### ISSUE THREAD

**Issue by Macrow** [syanbo/react-native-agora#194]
我昨晚测试了beta版，发现比alpha版完善太多，感谢这么辛苦的工作，赞一个。

有几个疑问：

1.beta版本里面的RtcEngine没有找到```startPreview```和```stopPreview```方法，我只能用```RtcChannel```的```publish```和```unpublish```来进行操作，但是在有些场景不方便，请问```startPreview```方法有没有对应的接口？

2.在使用```RtcRemoteView.SurfaceView```时，调用远端推流视频，在Android上表现正常，在iOS端会经常出现问题，比如1v1视频时，iOS端的这个```RtcRemoteView.SurfaceView```会不停在本地视频和远端视频之间快闪，导致App崩溃，我调试了半天，确认uid是没有问题的，同样的代码在Android下表现正常，不知是不是我的用法有问题。

代码片段如下
```
<RtcRemoteView.SurfaceView
    key={user.id}
    style={{
        width: fullScreen ? '100%' : width,
        height: fullScreen ? '100%' : height,
        backgroundColor: 'black'
    }}
    renderMode={VideoRenderMode.Hidden}
    channelId={agoraChannel}
    uid={user.agoraId}
/>
```

3.程序运行会报很多警告，是没有添加RtcEngine的一些事件监听函数，我按照提示添加了这些监听函数，但是仍然不停地出现这些警告，非常多，导致充满整个屏幕，我可以如何添加监听函数来消除警告？

**Comment by LichKing-2234** [comment]
1、使用RtcLocalView会自动调用preview，不预览就移除就好了
2、uid是不是有0的情况
3、这个后续会考虑优化

**Comment by Macrow** [comment]
谢谢解答！

第二个问题我这里测试，确认uid没有问题，在Android机上正常，只出现在iOS上，不知有什么方法可以调试不，因为这个问题，我暂时只能停在2.9上了。

我在同一画面同时用了LocalView和RemoteView，不知道这个有什么影响没。

**Comment by LichKing-2234** [comment]
@Macrow 需要在原生那边调试，看下uid是什么，我这边抽空也看下

**Comment by Macrow** [comment]
我今天试用了```3.0.1-beta.3```，以前的问题都不见了，现在正常了！
