### ISSUE TITLE
Subscriber able to publish audio in broadcast

### ISSUE THREAD

**Issue by gwendall** [syanbo/react-native-agora#195]
Hello - we are setting up an audio broadcast and we have a problem. The subscribers are able to publish audio into the conversation - but they should not as they are just subscriber (not publishers / hosts). Here is what we did. What went wrong ?

```
    // on the client    
    RtcEngine.init({
      appid: AGORA_APP_ID,
      mode: 0,
      channelProfile: 1, // broadcast
      clientRole: 1,
      audioProfile: AudioProfileDefault,
      audioScenario: AudioScenarioDefault,
    });
    // then somewhere else
    RtcEngine.joinChannel(roomId, userAgoraId, userAgoraToken);

    // on the server 
    const {
      RtcTokenBuilder,
      RtcRole,
    } = require("agora-access-token");
    const userAgoraToken = RtcTokenBuilder.buildTokenWithUid(
      AGORA_APP_ID,
      AGORA_APP_CERTIFICATE,
      roomId,
      userAgoraId,
      RtcRole.SUBSCRIBER,
      privilegeExpiredTs
    );
```

**Comment by LichKing-2234** [comment]
you should set the client role to 2 when init if you don't want to publish stream.

**Comment by gwendall** [comment]
The problem is, the user may join different channels, where he may or may not be able to publish audio. So I need to enable / disable audio dynamically. Isn’t it possible with Agora ?

**Comment by LichKing-2234** [comment]
you can control audio publishing by set client role.

**Comment by gwendall** [comment]
So client role is client-side ? By the client itself ? So any client should be able to set himself as a host. Isn’t that very unsafe ? 

Gwendall Esnault

**Comment by LichKing-2234** [comment]
The audience role can not publish stream anyway. The broadcast role can publish stream, if you do not want to publish, you can call muteLocalAudioStream method.
