### ISSUE TITLE
Build failed. RCTViewManager.h not found.

### ISSUE THREAD

**Issue by alexandr-makarov-am** [syanbo/react-native-agora#196]
After installation via manual i get issue. 

![image](https://user-images.githubusercontent.com/13029529/82601665-9687ee80-9bb8-11ea-93aa-a4b452c9fbec.png)

'React/RCTViewManager.h' file not found.

My build log

![image](https://user-images.githubusercontent.com/13029529/82601645-8b34c300-9bb8-11ea-9fb7-68987df0e366.png)

Any ideas?

**Comment by alexandr-makarov-am** [comment]
My repo with demo project. Via this project you can reproduce this bug. https://github.com/alexandr-makarov-am/agora-demo-app

**Comment by LichKing-2234** [comment]
you should not add the library to the project, RN >0.60.0 will link plugins auto.

**Comment by alexandr-makarov-am** [comment]
> you should not add the library to the project, RN >0.60.0 will link plugins auto.

It is really works!) Thank you.
