### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for

### ISSUE THREAD

**Issue by codetheweb** [syanbo/react-native-agora#197]
Using this import statement:
```js
import RtcEngine, {RtcRemoteView, RtcLocalView} from 'react-native-agora';
```

results in the below error:

![Screen Shot 2020-05-21 at 5 54 10 PM](https://user-images.githubusercontent.com/7410405/82613886-1481d080-9b8c-11ea-95ef-b9aefacbbe65.png)

Versions:
- react-native-agora: 3.0.0-beta.4
- react-native: 0.62.2
- Google API 29

Any idea what the issue could be? The same code runs fine on iOS.

**Comment by LichKing-2234** [comment]
you should init SDK before you use the widget

**Comment by codetheweb** [comment]
Thank you, that was the problem.  I was rendering `<RtcLocalView.SurfaceView/>` before an instance of RtcEngine was created.
