### ISSUE TITLE
android 退出直播界面，AgoraView为什么会还在呢？一直挡在别的界面最前面。

### ISSUE THREAD

**Issue by jiyunkeji** [syanbo/react-native-agora#198]
android 退出直播界面，AgoraView为什么会还在呢？一直挡在别的界面最前面。
![Screenshot_20200525-135608](https://user-images.githubusercontent.com/50569560/82783401-f02a3a80-9e90-11ea-81c2-ae190382958c.jpg)

**Comment by TXLtianxiaolong** [comment]
我也遇到过相同问题，但是现在又没出现了。

**Comment by LichKing-2234** [comment]
请问还能复现么，是不是widget没有释放，我们用的是SurfaceView，会盖在上面

**Comment by jiyunkeji** [comment]
> 请问还能复现么，是不是widget没有释放，我们用的是SurfaceView，会盖在上面

你好，有的手机会这样，有的手机不会呢？这是什么情况呢？
<img width="360" alt="image" src="https://user-images.githubusercontent.com/50569560/83829032-93424600-a714-11ea-9212-b0fe1156b427.png">
github的demo只有leaveChannel，上图是我加的，还有什么方法可以释放吗？

**Comment by jiyunkeji** [comment]
> 请问还能复现么，是不是widget没有释放，我们用的是SurfaceView，会盖在上面

我把Agora-RN-Quickstart这个项目的，Video搞到项目，我把上面的按钮去了（就是AgoraView全屏的时候），退出视频直播，然后就出现整个界面黑色，档在最前面。加上上面的按钮，就不会出现。
其实就是AgoraView上面加上个VIew就没问题。

**Comment by LichKing-2234** [comment]
请用最新版本做测试
