### ISSUE TITLE
退出以后底部有一条黑怎么解决啊？

### ISSUE THREAD

**Issue by 326886472** [syanbo/react-native-agora#2]

**Comment by DBshaoYan** [comment]
有一条黑线，这个属于样式问题吧 ！单纯的API调用逻辑，出现黑线不太可能。
所以您检查一下退出后的样式之类的。

**Comment by 326886472** [comment]
我用的是RN老版本的navigator导航push进去的，在退出的时候pop出来，然后底部就出现了一条20px左右的黑边把下面挡住了

**Comment by yudhis8** [comment]
there is still no answer for this bugs ? i have a same problem

**Comment by Matrixbirds** [comment]
@326886472 @yudhis8 now 2.3.3-alpha is released. You guys can try the new one.
