### ISSUE TITLE
这些是什么错？？？

### ISSUE THREAD

**Issue by jiyunkeji** [syanbo/react-native-agora#200]
Sending `ag_rtcapiCallExecute` with no listeners registered.

 Sending `ag_rtcerror` with no listeners registered.

我加上 RtcEngine.removeAllListeners();但是（@deprecated removeAllListeners）
<img width="419" alt="image" src="https://user-images.githubusercontent.com/50569560/82796800-b6652e00-9ea8-11ea-8537-3b0c0918df11.png">

**Comment by LichKing-2234** [comment]
这是RN时间的警告，原生发了事件，但是没有设置listener，后面会优化，可以暂时忽略

**Comment by LichKing-2234** [comment]
最新版本已优化
