### ISSUE TITLE
setRemoteRenderMode方法问题 

### ISSUE THREAD

**Issue by TXLtianxiaolong** [syanbo/react-native-agora#201]
项目之中需要对远端视频实现“镜像反转”，通过查看官方api，可以通过setRemoteRenderMode方法来实现。

![1590482171533](https://user-images.githubusercontent.com/15356406/82879323-600ef280-9f6f-11ea-997a-3f924ad0b1ea.jpg)

setRemoteRenderMode有三个参数，但是RtcEngine.setRemoteRenderMode只实现了前两个参数。没有实现“ mirrorMode”参数。

![1590482712747](https://user-images.githubusercontent.com/15356406/82879991-59cd4600-9f70-11ea-87f9-74507c52bb8d.jpg)

请问，可以通过其他方法来解决镜像反转的问题吗？

**Comment by LichKing-2234** [comment]
你可以试试beta版本，适配了原生3.0SDK

**Comment by TXLtianxiaolong** [comment]
> 你可以试试beta版本，适配了原生3.0SDK

beta版本在哪里可以安装使用呢？

**Comment by syanbo** [comment]
@TXLtianxiaolong 3.0.0-beta.4
