### ISSUE TITLE
[3.0.0-beta.4] The 'Pods-app' target has libraries with conflicting names: libcrypto.a.

### ISSUE THREAD

**Issue by noway** [syanbo/react-native-agora#204]
Getting this error when running `pod install` in 3.0.0-beta.4:

```
[!] The 'Pods-app' target has libraries with conflicting names: libcrypto.a.
```

wasn't an issue in 2.9.1-alpha.2.

I suspect the issue is coming from AgoraRtcEngine_iOS_Crypto, which seems to be a new pod dependency. Perhaps it would be possible to vendor libcrypto.a in podspec like so? https://github.com/syanbo/react-native-agora/blob/97b0826197457e62489ee885a687f2a3c54efb38/react-native-agora.podspec#L17-L20
Not sure it would help, but just an idea.

But for now while that's not done, is there a workaround?

Cheers

**Comment by LichKing-2234** [comment]
if you use RN 0.62.+, you should disable the Flipper.
```
# Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  add_flipper_pods!
  post_install do |installer|
    flipper_post_install(installer)
  end
```

**Comment by noway** [comment]
Thanks

**Comment by bolan9999** [comment]
It means that flipper can not be enabled on it?

**Comment by LichKing-2234** [comment]
@bolan9999 If you want to use flipper, you can use react-native-agora 3.3.+ version, the latest version is 4.x
