### ISSUE TITLE
build error on ios. duplicate symbol '_md5_block_data_order' in:

### ISSUE THREAD

**Issue by ArkaneKhan** [syanbo/react-native-agora#211]
duplicate symbol '_md5_block_data_order' in:
    ios/Pods/AgoraRtcEngine_iOS_Crypto/Agora_Native_SDK_for_iOS_FULL/libs/libcrypto.a(md5_dgst.o)
    /Users/xxxxx/Library/Developer/Xcode/DerivedData/agora-test-crcrornwpvkestbxvvueflllkgah/Build/Products/Debug-iphonesimulator/BoringSSL-GRPC/libBoringSSL-GRPC.a(md5.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ArkaneKhan** [comment]
i was using react-native-agora@beta version with RN 61.4 which caused this issue switching to stable version solved my issue.

**Comment by LichKing-2234** [comment]
In the beta version we use the `libcrypto.a` to support encryption, you should disable the Flipper when your RN version > 0.62.0.
maybe you use the Firebase lib, Firebase uses the BoringSSL, it causes duplicate symbol.

**Comment by ArkaneKhan** [comment]
yes it conflicted with firebase

**Comment by LichKing-2234** [comment]
@ArkaneKhan I will upgrade our static library to the dynamic framework later, then it will be fixed.

**Comment by LichKing-2234** [comment]
@ArkaneKhan you can try the 3.0.1-beta.3, I have upgraded our static library to the dynamic framework.
