### ISSUE TITLE
How to use setChannelProfile

### ISSUE THREAD

**Issue by nikhilkbansal** [syanbo/react-native-agora#212]
I want to setChannelProfile in my audio conferencing application to use the audio broadcasting feature of Agora https://docs.agora.io/en/Voice/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#a1bfb76eb4365b8b97648c3d1b69f2bd6. This is the function that I want to use.

**Comment by LichKing-2234** [comment]
you can use the beta version, it provides the setChannelProfile method.

**Comment by nikhilkbansal** [comment]
Using this.RtcEngine.setChannelProfile(Types.ChannelProfile.LiveBroadcasting) is giving an error
java.lang.Double cannot be cast to java.lang.String

**Comment by LichKing-2234** [comment]
@nikhilkbansal is the bug still exists?
