### ISSUE TITLE
Task :react-native-agora:compileReleaseJavaWithJavac FAILED

### ISSUE THREAD

**Issue by MariaNabil** [syanbo/react-native-agora#214]
It is working good in debug mode but in release I got this error : 
Task :react-native-agora:compileReleaseJavaWithJavac FAILED

Here is my package.json file :

"dependencies": {
    "@babel/runtime": "^7.4.5",
    "@eva-design/eva": "^1.0.1",
    "@valdio/react-native-scrollable-tabview": "^0.8.12",
    "accordion-collapse-react-native": "^0.1.11",
    "axios": "^0.19.0",
    "html-entities": "^1.2.1",
    "moment": "^2.24.0",
    "native-base": "^2.8.2",
    "react": "^16.13.1",
    "react-native": "^0.62.2",
    "react-native-agora": "2.9.1-alpha.3",
    "react-native-awesome-alerts": "^1.2.0",
    "react-native-bouncing-preloader": "^1.0.1",
    "react-native-btr": "^1.1.4",
    "react-native-dash": "0.0.9",
    "react-native-date-picker": "^2.7.3",
    "react-native-datepicker": "^1.7.2",
    "react-native-dates": "^2.0.4",
    "react-native-document-picker": "^3.2.4",
    "react-native-easy-grid": "^0.2.2",
    "react-native-floating-action": "^1.18.0",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-image-crop-picker": "^0.25.3",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-maps": "^0.26.1",
    "react-native-modal-datetime-picker": "^7.6.0",
    "react-native-multiple-select": "^0.5.3",
    "react-native-ratings": "^6.5.0",
    "react-native-raw-bottom-sheet": "^2.0.5",
    "react-native-reanimated": "^1.9.0",
    "react-native-render-html": "^4.1.2",
    "react-native-restart": "0.0.13",
    "react-native-screens": "^2.8.0",
    "react-native-simple-time-picker": "^0.2.0",
    "react-native-snap-carousel": "^3.8.4",
    "react-native-star-rating": "^1.1.0",
    "react-native-svg": "^12.1.0",
    "react-native-swipeable-cards": "^1.1.23",
    "react-native-swipeable-flat-list": "^0.1.1",
    "react-native-ui-kitten": "^4.1.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-webview": "^8.0.2",
    "react-navigation": "^3.11.1",
    "react-redux": "^7.1.1",
    "redux": "^4.0.4",
    "redux-thunk": "^2.3.0"
  },

How can I solve this please ? 
Thanks in advance .

**Comment by LichKing-2234** [comment]
any more build log?

**Comment by ank26oct** [comment]
facing same issue on release build

**Comment by rebirthtobi** [comment]
I am also facing this same issue as @ank26oct after bundleRelease but works with metro server

**Comment by ank26oct** [comment]
I have resolved it by adding following:

1. Add these permissions in AndroidManifest.xml

<uses-permission android:name="android.permission.RECORD_AUDIO" />
  <uses-permission android:name="android.permission.CAMERA" />
  <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>

2. Edit android/proguard-rules.pro add following :
-keep class io.agora.**{*;}

3. mkdir -p android/app/src/main/assets
curl "localhost:8081/index.bundle?platform=android&dev=false&minify=true" -o "android/app/src/main/assets/index.android.bundle"
cd android
./gradlew assembleRelease

**Comment by MariaNabil** [comment]
![error](https://user-images.githubusercontent.com/18213661/84823221-4caaf080-b01e-11ea-9c8b-9e2ce5325f09.PNG)

**Comment by rebirthtobi** [comment]
Thanks @ank26oct `-keep class io.agora.**{*;}` fix the issue for me, I am left with remote video not showing now

**Comment by LichKing-2234** [comment]
@MariaNabil have you migrate to AndroidX? maybe you should add `android.enableJetifier=true` to your `gradle.properties`
