### ISSUE TITLE
joinChannel with Info

### ISSUE THREAD

**Issue by keisan1231** [syanbo/react-native-agora#216]
I wanna join channel with info.

I got error in iOS
```
Exception '-[__NSDictionaryM length]: unrecognized selector sent to instance 0x280d66840' was thrown while invoking joinChannel on target Agora with params
```

## my code

```js
await RtcEngine.joinChannel(channel, undefined, undefined, {
      userName: 'testUser1',
    })
```

**Comment by LichKing-2234** [comment]
the laster param is a string, I will fix it later.

**Comment by keisan1231** [comment]
@LichKing-2234 
Thanks a lot 🙏

Do I have to write like this??

```js
await RtcEngine.joinChannel(channel, undefined, undefined, `{
      userName: 'testUser1',
    }`)
```

**Comment by LichKing-2234** [comment]
the last param is not using for userName, you can't get the value which you have set.

**Comment by keisan1231** [comment]
@LichKing-2234 
How can I join Channel with user's custom infomation

**Comment by LichKing-2234** [comment]
with your business service. our use the `joinChannelWithUserAccount` method.

**Comment by keisan1231** [comment]
@LichKing-2234 

I see 🤔

**Comment by keisan1231** [comment]
@LichKing-2234 
I want to see example `joinChannelWithUserAccount`😰

I tried this, but listner did not work('userJoined')
```js
await RtcEngine.joinChannelWithUserAccount(
      channel,
      'TESTACCOUNT',
      'TESTTOKEN',
    )
```

**Comment by LichKing-2234** [comment]
have you set the correct token? you don't need to set token if you don't enable token in the dashboard console.

**Comment by keisan1231** [comment]
@LichKing-2234 

this?? I did not set App Certificate.

I cannot discover `Generate Temp Token`😰

<img width="671" alt="スクリーンショット 2020-06-18 20 13 21" src="https://user-images.githubusercontent.com/46130313/85013803-2b720d80-b1a0-11ea-9102-8f72e1ce2872.png">

**Comment by marqroldan** [comment]
Generate Temp Token shows when you activate/enable the App Certificate

You can't however go back once you enable  the App Certificate

**Comment by keisan1231** [comment]
@LichKing-2234 

I enabled App Certificate but listner did not work😰

```js
    RtcEngine.init(config);

RtcEngine.on('userJoined', (data) => {
      console.log('userJoin' + JSON.stringify(data));
    
    });
    RtcEngine.on('userOffline', (data) => {
    
    });

    RtcEngine.on('localUserRegistered', (data) => {
      console.log('local' + JSON.stringify(data));
    });
    RtcEngine.on('userInfoUpdated', (data) => {
      console.log('userInfoUpdated' + JSON.stringify(data));
    });
    RtcEngine.on('joinChannelSuccess', (data) => {
      
      //If Local user joins RTC channel
      RtcEngine.startPreview(); //Start RTC preview
    });



    await RtcEngine.joinChannelWithUserAccount(
      channel,
      'Account',
      'MY TOKEN',
    )
````

**Comment by LichKing-2234** [comment]
your token is 'MY TOKEN'?
Generate Temp Token shows when you activate/enable the App Certificate.
you can test by using the Generate Temp Token

**Comment by keisan1231** [comment]
@LichKing-2234 

yes . I Generate Temp Token

<img width="835" alt="スクリーンショット 2020-06-19 12 00 55" src="https://user-images.githubusercontent.com/46130313/85092442-ae3cac00-b224-11ea-9e05-c5dfd3efa93e.png">

**Comment by LichKing-2234** [comment]
so, 'MY TOKEN'  means the generate temp token?

**Comment by keisan1231** [comment]
@LichKing-2234 

'MY TOKEN' means the generate temp token, not a random string

**Comment by LichKing-2234** [comment]
the alpha version may have some unknown bugs. I suggest you use the beta version, here is the [demo](https://github.com/EkaanshArora/Agora-RN-Quickstart/tree/sdk-v3)

**Comment by keisan1231** [comment]
@LichKing-2234 
I begin using beta version, but issue happen😰
#221

**Comment by LichKing-2234** [comment]
@keisan1231 I have published a new version, you can try again.

**Comment by keisan1231** [comment]
@LichKing-2234 Thanks a lot🤓

**Comment by keisan1231** [comment]
@LichKing-2234 I tried.

`engine.addListener('UserJoined', .....` did not work.

Both `RtcEngine` & `RtcChannel` class have `joinChannel` method, then what's difference??

I tried both, but both 'UserJoined' listener did not work. 

I want to see sample code of lastest🙏

Is [this](https://github.com/EkaanshArora/Agora-RN-Quickstart/blob/sdk-v3/components/Video.js) maybe not lastest???

**Comment by LichKing-2234** [comment]
`UserJoined` means remote users joined.

**Comment by LichKing-2234** [comment]
if you do not need multiple channels, you just use the `RtcEngine `.
https://docs.agora.io/en/Interactive%20Broadcast/multiple_channel_android?platform=Android

**Comment by LichKing-2234** [comment]
> @LichKing-2234 I tried.
> 
> `engine.addListener('UserJoined', .....` did not work.
> 
> Both `RtcEngine` & `RtcChannel` class have `joinChannel` method, then what's difference??
> 
> I tried both, but both 'UserJoined' listener did not work.
> 
> I want to see sample code of lastest🙏
> 
> Is [this](https://github.com/EkaanshArora/Agora-RN-Quickstart/blob/sdk-v3/components/Video.js) maybe not lastest???

this demo is lastest.

**Comment by keisan1231** [comment]
> `UserJoined` means remote users joined.

yes, I tried by using two devices.  But did not work.

> if you do not need multiple channels, you just use the RtcEngine .

I see . Thanks🙏


 > this demo is lastest. 

I'll try again later

**Comment by keisan1231** [comment]
@LichKing-2234 

I tried 3.0.1-beta.5 version.

##  joinchannel

I cannot joinchannel with user info as ever😰

I can use joinChannel but `optionalUid` is allowed only `0`.

```js
engine.joinChannel(
   '006ad77514........',
      this.state.channelName,
      'ABC',  //  user info
      0,   //   I tried "1", but　UserJoined listener didnt work
    ); 
```

## getUserInfoByUid

And I tried `getUserInfoByUid` in `engine.addListener('UserJoined', data => {...`

But I cannot get user information🤔

```js
engine.addListener('UserJoined', data => {
        const {peerIds} = self.state; 
        if (peerIds.indexOf(data) === -1) {
          self.setState({peerIds: [...peerIds, data]}); 
        }
        console.log(data);
        engine
          .getUserInfoByUid(0)
          .then(r => console.log(`${JSON.stringify(r)}`));  // {"uid":0,"userAccount":""}
      });
```

## joinChannelWithUserAccount

And `engine.joinChannelWithUserAccount` can call`engine.addListener('JoinChannelSuccess'...`

but cannot call `engine.addListener('UserJoined'.....`

**Comment by LichKing-2234** [comment]
the `optionalInfo` param of `joinChannel` is not the userInfo. you can get more info from the comment about `joinChannel` method.
`getUserInfoByUid` should be called after `joinChannelWithUserAccount`

**Comment by keisan1231** [comment]
@LichKing-2234 

`joinChannelWithUserAccount` did not call `engine.addListener('UserJoined'.....`

I want to implement that users can join a channel with users' info (userName, point, etc...)

Please tell me how to😰

**Comment by marqroldan** [comment]
Try this guide https://docs.agora.io/en/faq/string you apparently need to call `registerLocalUserAccount` first

**Comment by keisan1231** [comment]
@marqroldan 

Thanks a lot!

I can register userAccount , but still `engine.addListener('UserJoined'...` was not called😰

So I cannot do video calling

Do I mistake addListener???

**Comment by marqroldan** [comment]
This works for me, I am receiving the event

```
      RtcEngine.registerLocalUserAccount(
        appid,
        'testuser',
      ).then(() => {
        console.log( registerLocalUserAccount 'success!');
        RtcEngine?.joinChannelWithUserAccount(
          tempToken,
          channel,
          'testuser',
        );
      });
```

**Comment by keisan1231** [comment]
@marqroldan 
what is your version??   I use `3.0.1-beta.5`

I tried your code but `addListener('UserJoined'...` was not called

I got normal joining(`joinChannel` method) successsfully, but did not `joinChannelWithUserAccount` method 😰

`joinChannelWithUserAccount` calls `addListener('JoinChannelSuccess'......`
 but does not call `addListener('UserJoined'.....`

**Comment by marqroldan** [comment]
`UserJoined` is not for the local user but for the remote

**Comment by keisan1231** [comment]
@marqroldan 

yes, I tried two devices. but `UserJoined` was not called after user in another device joined

**Comment by marqroldan** [comment]
Interesting, I'm using the web demo to join the channel for testing

https://webdemo.agora.io/agora-web-showcase/examples/Agora-Web-Tutorial-1to1-Web/?_ga=2.210623063.33363857.1588381252-1127249543.1583836640

**Comment by keisan1231** [comment]
@marqroldan 
in only react native bug?

**Comment by keisan1231** [comment]
@LichKing-2234 
 
I hope fixed . Thank you🙏

**Comment by LichKing-2234** [comment]
I use `engine.joinChannelWithUserAccount(null, channelName, userAccount)` and addListener
```
engine.addListener('JoinChannelSuccess', async (channel, uid, elapsed) => {
            console.log('RtcEngine onJoinChannelSuccess', channel, uid, elapsed);
            console.log(await RtcEngine.instance().getUserInfoByUserAccount(this.state.uid.toString()));
            console.log(await RtcEngine.instance().getUserInfoByUid(uid));
            this.setState({joinSucceed: true});
});
```
```
engine.addListener('UserJoined', (uid, elapsed) => {
            console.log('RtcEngine onUserJoined', uid, elapsed);
});
```
![image](https://user-images.githubusercontent.com/9312526/85506841-bb420c80-b623-11ea-8392-1f0c0aeb0a5b.png)

**Comment by LichKing-2234** [comment]
@keisan1231 it works fine. I join 2 users.
1 {"uid": 1000000012, "userAccount": "88"}
2 {"uid": 1000000013, "userAccount": "94"}

**Comment by keisan1231** [comment]
@LichKing-2234  
Really!?  Latest version??

**Comment by LichKing-2234** [comment]
@keisan1231 yes, latest version

**Comment by keisan1231** [comment]
@LichKing-2234 

Please show me full code🙏

maybe problem of lifecycle

**Comment by LichKing-2234** [comment]
```
        this.engine = await RtcEngine.create('yourAppId');
        this.engine.addListener('JoinChannelSuccess', async (channel, uid, elapsed) => {
            console.log('RtcEngine onJoinChannelSuccess', channel, uid, elapsed);
            console.log(await RtcEngine.instance().getUserInfoByUserAccount(this.state.uid.toString()));
            console.log(await RtcEngine.instance().getUserInfoByUid(uid));
        });
        this.engine.addListener('LeaveChannel', (stats) => {
            console.log('RtcEngine onLeaveChannel', stats.users, stats);
        });
        this.engine.addListener('UserJoined', (uid, elapsed) => {
            console.log('RtcEngine onUserJoined', uid, elapsed);
        });
        this.engine.addListener('UserOffline', (uid, reason) => {
            console.log('RtcEngine onUserOffline', uid, reason);
        });
        await this.engine.enableVideo();
        await this.engine.joinChannelWithUserAccount('yourToken', 'yourChannelName', 'yourUserAccount');
```

**Comment by keisan1231** [comment]
@LichKing-2234 
Thanks a lot ❗️

I try later👍

**Comment by keisan1231** [comment]
@LichKing-2234 

I tried your code but `UserJoined` listener wasn't called😰

I cannot understand😰

<img width="658" alt="スクリーンショット 2020-06-24 18 02 37" src="https://user-images.githubusercontent.com/46130313/85526486-04568880-b645-11ea-9e22-e50af2e87220.png">

**Comment by LichKing-2234** [comment]
because the uid is the same

**Comment by LichKing-2234** [comment]
you should use different userAccount on different client

**Comment by keisan1231** [comment]
@LichKing-2234 

> because the uid is the same

it works fine！！！
Thanks a lot🙏

**Comment by keisan1231** [comment]
@LichKing-2234 

Can  parameter of `userAccount` have only word a-z, A-Z, 0~9???

**Comment by LichKing-2234** [comment]
You should not set userAccount with json.
You can refer to the method doc in .ts file.

**Comment by keisan1231** [comment]
@LichKing-2234 

I want to use Japanese words as userAccount.

I hope such a update🙏

**Comment by LichKing-2234** [comment]
Sorry about it, We just support English. You can use your userId and get UserAccount from your system.
```
The user account. The maximum length of this parameter is 255 bytes. Ensure that you set this parameter and do not set it as null. Supported character scopes are:
* All lowercase English letters: a to z.
* All uppercase English letters: A to Z.
* All numeric characters: 0 to 9.
* The space character.
* Punctuation characters and other symbols, including: "!", "#", "$", "%", "&", "(", ")", "+", "-", ":", ";", "<", "=", ".", ">", "?", "@", "[", "]", "^", "_", " {", "}", "|", "~", ",".
```

**Comment by keisan1231** [comment]
@LichKing-2234 
I see

**Comment by keisan1231** [comment]
@LichKing-2234 

I want to get user info in UserJoined Listener.

But `TypeError: undefined is not an object (evaluating 'info.userAccount')`

## code 

```js
this.engine.addListener('UserJoined', async (uid, elapsed) => {
      console.log('RtcEngine onUserJoined', uid, elapsed, 'No ', a);
      const {peerIds} = this.state; //Get currrent peer IDs
      const info = await RtcEngine.instance().getUserInfoByUid(uid);
      console.log(info.userAccount);
      if (peerIds.indexOf(uid) === -1) {
        //If new user
        this.setState({peerIds: [...peerIds, uid]}); //add peer ID to state array
      }
    });
```

**Comment by LichKing-2234** [comment]
is remote user join by userAccount?

**Comment by keisan1231** [comment]
@LichKing-2234 
yes.

Sometimes successfully, but most of times failed by this error

**Comment by keisan1231** [comment]
@LichKing-2234 

I got it successfully by using `setTimeout()`

```js
this.engine.addListener('UserJoined', async (uid, elapsed) => {
      console.log('RtcEngine onUserJoined', uid, elapsed, 'No ', a);
      const {peerIds} = this.state; //Get currrent peer IDs
      setTimeout(async () => {
        const info = await RtcEngine.instance()
          .getUserInfoByUid(uid)
          .catch(e => console.log(e.toString()));
        console.log(info.userAccount);
        if (peerIds.indexOf(uid) === -1) {
          this.setState({peerIds: [...peerIds, uid]}); //add peer ID to state array
        }
      }, 2000);
    });
```
