### ISSUE TITLE
Could not invoke RCTAgora.init

### ISSUE THREAD

**Issue by JosephMulder** [syanbo/react-native-agora#22]
dlopen failed. I already have done react-native link react-native-agora and can confirm that  new AgoraPackage() is inside MainApplication.java. 

![screenshot_1540583953](https://user-images.githubusercontent.com/38866422/47589792-3ecfc580-d938-11e8-8c9a-2617265d7db8.png)

**Comment by kkumaresan** [comment]
I am facing the same issue when I switch the targetSdkVersion from 22 to 26. Can you please let me know if there is a solution to avoid this error. Thanks!
