### ISSUE TITLE
can not setBeautyEffectOptions，something wrong with setBeautyEffectOptions

### ISSUE THREAD

**Issue by KarenQiao** [syanbo/react-native-agora#220]
can not setBeautyEffectOptions！something wrong with setBeautyEffectOptions

user the following code:

 RtcEngine.setBeautyEffectOptions(true,{lighteningContrastLevel:1,lighteningLevel:0.7,smoothnessLevel:0.5,rednessLevel:0.1})
![image](https://user-images.githubusercontent.com/27947842/85108896-126e6880-b243-11ea-9016-791ce858b7b6.png)

Error as follows：
![image](https://user-images.githubusercontent.com/27947842/85108735-cb807300-b242-11ea-9deb-4f79b40dca23.png)

device info:

![image](https://user-images.githubusercontent.com/27947842/85109073-56616d80-b243-11ea-9005-f96245c5774a.png)

![image](https://user-images.githubusercontent.com/27947842/85109147-71cc7880-b243-11ea-9a2f-043668a1f032.png)

**Comment by LichKing-2234** [comment]
fixed in `2.9.1-alpha.7`
