### ISSUE TITLE
version 3.0.1-beta.5 Android error

### ISSUE THREAD

**Issue by keisan1231** [syanbo/react-native-agora#225]
## Android error

`package com.syan.agora does not exist`

I use 3.0.1-beta.5 version. 

I follow [this](https://github.com/syanbo/react-native-agora/blob/master/docs/v2/android.md)

<img width="600" alt="スクリーンショット 2020-06-26 16 23 21" src="https://user-images.githubusercontent.com/46130313/85831497-5c1dfc80-b7c9-11ea-9ff2-cecb3163a644.png">

**Comment by LichKing-2234** [comment]
You should refer to the new version readme.

**Comment by LichKing-2234** [comment]
You may linked the old version package.

**Comment by keisan1231** [comment]
@LichKing-2234 
I got success!!

Thanks a lot🙏
