### ISSUE TITLE
Can I use Cloud Recording with rn?

### ISSUE THREAD

**Issue by Thierry-Santos** [syanbo/react-native-agora#229]
if so, how?

**Comment by LichKing-2234** [comment]
you can use cloud recording with any platform SDK.

**Comment by Thierry-Santos** [comment]
there is an example or documentation on javascript?

**Comment by LichKing-2234** [comment]
Cloud Recording is Restful API, not the SDK. you can refer to [the doc](https://docs.agora.io/en/cloud-recording/product_cloud_recording?platform=Linux)

**Comment by Thierry-Santos** [comment]
ok, thanks

**Comment by Nits7029** [comment]
yes it is APIs, nu if we start live streaming from the web browser then it's working but when we start live streaming from App recording status remains "4" in query API and after some time getting 404 error.

I have tried in Agora RN example app as well, the same issue.

So @LichKing-2234 please advice, thanks

**Comment by plutoless** [comment]
@Nits7029 you should start cloud recording from your server, not client.

**Comment by Nits7029** [comment]
Yeah i know, but cloud recording is not starting for stream published from app. Its working fine if stream published from the web browser

**Comment by plutoless** [comment]
do you have the channel name?

**Comment by Nits7029** [comment]
yeah

**Comment by plutoless** [comment]
@Nits7029 i mean i might be able to take a look if you can provide the channel name for which you have tested. are you sure you have joined the channel successfully?

**Comment by Nits7029** [comment]
yes, giving you

**Comment by Nits7029** [comment]
Channel: "NW9PD4WEAjbNKcGVHVrfHgiP6jB3yRkPz8rEUz6O2cneZFLZluJ3UPbqLK74EyO9"

**Comment by Nits7029** [comment]
query response:

`{
    "resourceId": "nUwUbQf9Zg6tsgtLslGnDg0lk8RYaUE09pqOuSIgwfzcMYuZoWFATPsc33luiYhrLgTzw1V_Ahg_Ef0aqvRjjJOE7YYOb1V-tiN8gEBkbKPinXIozancLUQpXNk8vu3pjreL75LSMQT-dAk91GvCfdcf5UnnRehATfXje1b4CW7dhlb92fiRUotmzGYtaNOXC2vGOyGQrsB0wEB0ihO73Bt-GhDkCllV54b0XqZSHQeWRPTdWzbdfyxubwaf8QB9NcGGr9NgQUORTtjr9O0cVoJUuJ8zJhl_I3-Mpl8aGin0G3mkFNoz6X6BxTQUNHASnGw3Vk8vjiBXJ71cpNO_jgB7nN3vUcxAijUqtcumfuYr99mYplMwKCl41xFomT-d",
    "sid": "fbe3192ba34c3df54c556080d1c89eea",
    "serverResponse": {
        "status": 4,
        "fileList": "",
        "fileListMode": "string",
        "sliceStartTime": 0
    }
}`

after some time, i am getting

`{
    "resourceId": "nUwUbQf9Zg6tsgtLslGnDg0lk8RYaUE09pqOuSIgwfzcMYuZoWFATPsc33luiYhrLgTzw1V_Ahg_Ef0aqvRjjJOE7YYOb1V-tiN8gEBkbKPinXIozancLUQpXNk8vu3pjreL75LSMQT-dAk91GvCfdcf5UnnRehATfXje1b4CW7dhlb92fiRUotmzGYtaNOXC2vGOyGQrsB0wEB0ihO73Bt-GhDkCllV54b0XqZSHQeWRPTdWzbdfyxubwaf8QB9NcGGr9NgQUORTtjr9O0cVoJUuJ8zJhl_I3-Mpl8aGin0G3mkFNoz6X6BxTQUNHASnGw3Vk8vjiBXJ71cpNO_jgB7nN3vUcxAijUqtcumfuYr99mYplMwKCl41xFomT-d",
    "sid": "fbe3192ba34c3df54c556080d1c89eea",
    "code": 404
}`

**Comment by Nits7029** [comment]
@plutoless are you looking into?
