### ISSUE TITLE
用example中的代码，调用RtcEngine.muteAllRemoteAudioStreams和RtcEngine.setCameraTorchOn等方法在IOS和安卓真机上没有效果

### ISSUE THREAD

**Issue by SwordElucidator** [syanbo/react-native-agora#25]
按照example里的方式调用`RtcEngine.setCameraTorchOn(true)`后，在iOS和Android的实机上貌似都不好用，但`switchCamera`，`leaveChannel`和`enableVideo`等貌似都没有问题。

已经实现视频聊天，功能基本一切正常，除了这些控制闪光灯、麦克风静音和喇叭静音等地方暂时不知道什么问题。

不知有没有哪位能够解读一下可能的原因？

谢谢！

**Comment by renanpupin** [comment]
The RtcEngine.setCameraTorchOn(true) is not working on iOS.

**Comment by Matrixbirds** [comment]
setCameraTorchOn 在没有切后置摄像头的时候会无法开启闪光灯。已经在iOS上确认 这是系统行为问题。
Android 似乎也是一样
