### ISSUE TITLE
W/unknown:ViewManagerPropertyUpdater: Could not generated setter for class com.sym.agora.AgoraViewManager

### ISSUE THREAD

**Issue by TeruyaHaroldo** [syanbo/react-native-agora#27]
Hello!

I am trying to use your base example and I am getting the following warning:

`W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.syan.agora.AgoraViewManage`

My application in the native layer is getting the following events:

```
D/Agora: joinChannel: "name of the chanel" 0 0
D/Agora: "onJoinChannelSuccess---"
D/Agora: 1032warning---
```

Am I missing something?

... and my camera is always black...

**Comment by Matrixbirds** [comment]
@TeruyaHaroldo we have already updated the 2.3.3 native sdk in the latest version. now u can try 2.3.3-alpha version.
