### ISSUE TITLE
Editing configPublisher does not properly publish url

### ISSUE THREAD

**Issue by JonahElbaz** [syanbo/react-native-agora#28]
Adding the following code to src/index.js in the example did not yield the expected result of publishing the stream to my own RTMP server.

```
  componentDidMount() {

        // 当前版本号
        RtcEngine.getSdkVersion((version) => {
            console.log(version)
        });
        
        RtcEngine.configPublisher({
            publishUrL: "RMTP://jonahelbaz:password@192.168.0.101/live/myguy",
            rawStreamUrl: "RMTP://jonahelbaz:password@192.168.0.101/live/myguy"
        });

        //加入房间
        RtcEngine.joinChannel();

...
```

**Comment by JonahElbaz** [comment]
No errors thrown in the log either.

**Comment by Matrixbirds** [comment]
We have already deprecated the configPublisher methods, now u can upgrade to 2.3.3-alpha version to try the setLiveTranscoding. u can use the detail in the [docs](https://docs.agora.io/en/Video/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#a06d9129dfed219e52d4855d91da6616d) .
