### ISSUE TITLE
ios 真机闪退

### ISSUE THREAD

**Issue by yuyongmao** [syanbo/react-native-agora#29]
打包发布到app store 测试 闪退

**Comment by syanbo** [comment]
链接数据线 xcode 原生设置release模式 查看错误日志

**Comment by yuyongmao** [comment]
muteLocalAudioStream 这个方法真机无效（目前只测试了android）

**Comment by Matrixbirds** [comment]
麻烦一下日志和出现的行为，还有相关的代码。目前已经最2.3.3 native sdk做了适配，可以的话尝试一下新版的react-native-agora。
