### ISSUE TITLE
组件对RN版本有什么要求

### ISSUE THREAD

**Issue by 326886472** [syanbo/react-native-agora#3]
我用的是RN v0.34 跑iOS时出现react配置问题，请问这和我的RN版本有关吗？
![wechatimg49](https://user-images.githubusercontent.com/26337476/27946745-ae8a8f48-6325-11e7-89f2-7dfdab2baa30.jpeg)

**Comment by 326886472** [comment]
问题解决了。。。0.4以后的UIManager在目录下，把React删了就可以了

**Comment by Matrixbirds** [comment]
native SDK已经更新到2.3.3。可以考虑使用最新版本。最新版本支持0.58的react native
