### ISSUE TITLE
[BUG] Fatal Exception: com.facebook.react.bridge.JSApplicationIllegalArgumentException

### ISSUE THREAD

**Issue by renanpupin** [syanbo/react-native-agora#30]
# Bug Report

**Current behavior**
> AgoraManager.java line 81
> com.syan.agora.AgoraManager.setupLocalVideo

**Steps to reproduce**
> I do not know how to reproduce, because it was catch at our bug tracker.

**Relevant logs and/or screenshots**
<img width="1231" alt="captura de tela 2018-12-22 as 18 49 49" src="https://user-images.githubusercontent.com/8743530/50378480-78603c80-061a-11e9-84a8-a7683ca10be5.png">
<img width="1229" alt="captura de tela 2018-12-22 as 18 49 59" src="https://user-images.githubusercontent.com/8743530/50378481-78f8d300-061a-11e9-8b35-b6511eda9d77.png">
<img width="1230" alt="captura de tela 2018-12-22 as 18 50 17" src="https://user-images.githubusercontent.com/8743530/50378482-79916980-061a-11e9-88e4-70f06827deb2.png">

**Comment by Matrixbirds** [comment]
Its seems u setupLocalVideo with a null object, could you paste ur javascript code here?

**Comment by Matrixbirds** [comment]
if anyone can reproduce it, pls provide ur step and description here, then reopen thx.
