### ISSUE TITLE
iOS: library not found

### ISSUE THREAD

**Issue by VedavyasBhat** [syanbo/react-native-agora#33]
Whenever I try to run the iOS app on a real device (or simulator, for that matter), I keep getting the "library not found" error for one of these 3 dependencies: `AgoraRtcEnginerKit`, `AgoraRtcCryptoLoader` or `libcrypto`.

I have tried unlinking and relinking them, but it hasn't helped.

It's only happening with Agora related dependencies, cam you guys help?

**Comment by syanbo** [comment]
https://github.com/syanbo/react-native-agora/blob/master/docs/IOS_INSTALLATION.md

**Comment by Matrixbirds** [comment]
u can follow the documentation to install it.
