### ISSUE TITLE
Agora Rtc Engine Kit.h file not found

### ISSUE THREAD

**Issue by AarshApple** [syanbo/react-native-agora#39]
I cloned the repo and followed all the steps of installation and linking in iOS but still i experience this issue that is AgoraRtcEngineKit.h file not found. Any help would be helpful

**Comment by Matrixbirds** [comment]
Please, provide the error log here, I can get more details to help u effectively.

**Comment by AarshApple** [comment]
Actually i was able to run after supplying the apikey. But i still experience issue after running the app. I get an error message stating 'Unable to resolve module react-native-agora from components/agora'. If you can just help

**Comment by Matrixbirds** [comment]
It seems `AgoraRtcEngineKit`  in ur xcode project cannot resolve correctly. so u need to update it from ios/Pods folder, this folder will be created after `pod install`.
U can follow below step to fix it.
![image](https://user-images.githubusercontent.com/9990676/53554004-ca24c600-3b79-11e9-8cee-50b72b3afab1.png)

![image](https://user-images.githubusercontent.com/9990676/53554027-d6108800-3b79-11e9-82dd-ea3dc4b3c0af.png)
find AgoraRtcEngineKit.framework from your Pods folder and replace AgoraRtcEngineKit.framework in RCTAgora by dragging it into Your Project -> Libraries -> RCTAgora.xcodeproj -> Build Phases -> Link Binary With Libraries drag_sdk_into_your_project_rctagora_link_binary_with_libraires
![image](https://user-images.githubusercontent.com/9990676/53554064-e4f73a80-3b79-11e9-805a-7b7fcfab7e02.png)

**Comment by Matrixbirds** [comment]
I cannot reproduce it, If you same error again, pls reopen this issue.

**Comment by CyrusZei** [comment]
for anybody that wants to try this RM -fr stulls

be damn careful with this command
`rm -rf $TMPDIR/metro-bundler-cache-*`

 it will remove your yarn, npm homebrew etc...
maybe add a warning ?

**Comment by pyankoff** [comment]
Having the same error with both QuickStart project and clean react-native project. 
XCode Version 12.4 (12D4e)

**Comment by LichKing-2234** [comment]
pls check your are using the latest  version of SDK.

**Comment by devsideal** [comment]
I'm getting same error in my flutter project:

`Lexical or Preprocessor Issue (Xcode): 'AgoraRtcKit/AgoraRtcEngineKit.h' file not found
/Users/macbook/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-5.3.0/ios/Classes/Base/RtcEnginePlugin.h:1:8` 

Using:
agora_rtc_engine-5.3.0
Flutter 3.0.1

**Comment by dujinxin** [comment]
> 

+1

**Comment by Khurshidddbek** [comment]
@devsideal I have the same problem. Did you not solve the problem?

**Comment by utkudenis** [comment]
i have same problem in our flutter project
flutter version 3.0.5
rtc engine 5.3.0

**Comment by Aakash359** [comment]
Same issues i have how can i resolve this pls let me know ?
