### ISSUE TITLE
Calling disableVideo() freezes the video instead of switching off camera

### ISSUE THREAD

**Issue by prameetc** [syanbo/react-native-agora#43]
**Intended Behavoiur**

Calling these functions should disable my camera and render a black screen.

**Actual Behaviour**

Calling either of them freezes the video.

**Functions affected**

`RtcEngine.disableVideo()`

**OS** - Android
**Device used** - Redmi Note 4

**Comment by Matrixbirds** [comment]
Okay, I can only reproduce the `disableVideo`'s affected in your scenario.
the muteLocalVideoStream only controls sending the local video stream, u can find more details [here](https://docs.agora.io/en/Video/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#a949cd7044eec55ffd0b63ad3004db756)

**Comment by prameetc** [comment]
@Matrixbirds Thanks for that, I have updated the description.

**Comment by Matrixbirds** [comment]
I m going to fix this ASAP, thx for ur issue.

**Comment by Matrixbirds** [comment]
Finally, I have do some research. This is a design problem, Agora RTC SDK will keep the last video frame. My advice is to unmount this component in react layer, you need define a bool showVideo state and then render the AgoraView component when the state is true.

**Comment by Matrixbirds** [comment]
I have already update the [simpleDemo](https://github.com/syanbo/react-native-agora/blob/1448fc04a8fa294b74568cff05883332a9abf374/samples/simpleDemo/components/agora.js#L363), it is an example use the correct way to handle this case. If you still have any question here open the issue again.
