### ISSUE TITLE
Native module cannot be null.

### ISSUE THREAD

**Issue by CyrusZei** [syanbo/react-native-agora#45]
I did follow these steps

1.yarn add react-native-agora 
2.react-native link react-native-agora

then I get the error `Native module cannot be null.`

any chance you know anything about this? Have been trying to get Agora to work on React-native for two days not without any luck

**Comment by Matrixbirds** [comment]
could u provide more details here?
It is indicating that some native module is built failed or loaded failed in react native runtime.
You could try [quick start](https://github.com/AgoraIO-Community/Agora-RN-Quickstart) which one is a stable demo. U could just run it by easy step.
