### ISSUE TITLE
how to check user is online or offline in react native agora

### ISSUE THREAD

**Issue by 13gurjeetsingh** [syanbo/react-native-agora#48]
Hi,
I have build the react native agora sample successfully.
next is , how to implement the following things : 
1 how to check other user is online or offline. 
2 how to initiate call with particular user. 
3 while initiate a call then how other user will get ring on mobile

Note : i think the Signaling process will help me but nothing is present  about it on the follwing link :
https://www.npmjs.com/package/react-native-agora

**Comment by Matrixbirds** [comment]
I agree the signaling process will help. but it does not belong to our `react-native-agora`.
`react-native-agora` is only wrapper agora.io media SDK. If you need to implement some features like a video phone call or private meeting, we can create another react-native module with agora.io signaling SDK together.

**Comment by 13gurjeetsingh** [comment]
that would be great, if you can do this because the same thing are present for ios native sdk 
like 
1 Check status of user is offline or not. 
2 If online, then send a request to other user.
3 get request Notification from sender end at Receiver end. 
4. accept/ Reject call listener and start video calling.
5. End session listener.

**Comment by 13gurjeetsingh** [comment]
@

**Comment by 13gurjeetsingh** [comment]
@Matrixbirds  sorry to close. By mistake I have pressed the close button

**Comment by Nahani** [comment]
Hello,

Any news about this ?

Regards

**Comment by Matrixbirds** [comment]
@13gurjeetsingh @Nahani  Hi guys, we are planning begin Agora Real-time Messaging SDK react native wrapper ASAP.

**Comment by Matrixbirds** [comment]
We have already release the realtime message sdk on react native [here](https://github.com/AgoraIO/RN-SDK-RTM/blob/master/examples/chatsapp/README.md)
If u have any realtime message scenarios, i think using [agora-react-native-rtm] (https://github.com/AgoraIO/RN-SDK-RTM) is the best choice.
