### ISSUE TITLE
Android 通信的时候，remote画面 始终 压住 local画面

### ISSUE THREAD

**Issue by iamlion** [syanbo/react-native-agora#5]
组件很完美，
但我在做android开发的时候发现，远程视频过来的画面  始终压住  本地的视频画面。

**Comment by DBshaoYan** [comment]
收到，这个是原生视图层级问题，我修复一下。

**Comment by iamlion** [comment]
我在setuplocal和setupremote的代码加入了，surface.setzorder的代码，发现本地画面又始终压住了远程画面，我想做成两个画面可以切换，能实现吗？

**Comment by DBshaoYan** [comment]
可以解决
https://github.com/DBshaoYan/react-native-agora/blob/master/android/src/main/java/com/syan/agora/AgoraViewManage.java
你看下这个文件，有个至于最上层的设置你根据自己需求自己调整一下，我现在暂时木有时间修改

**Comment by DBshaoYan** [comment]
@iamlion 新的版本 1.0.8 已修复
