### ISSUE TITLE
archiving fails, but build works

### ISSUE THREAD

**Issue by CyrusZei** [syanbo/react-native-agora#50]
I can build it without any problem, but as soon as I am archiving the app it will show errors.

I did remove the framework and I can archive so it is clear that has to do with the Agora framework. 

so this is the errors I get

<img width="267" alt="Screenshot 2019-03-17 at 03 01 48" src="https://user-images.githubusercontent.com/5053903/54484188-4c430900-4861-11e9-8da2-68441d83a82b.png">

I have been working on this error for like 3 days now without any luck

**Comment by Matrixbirds** [comment]
i cannot reproduce it on my environment. Probably u cannot follow the newest readme build steps and make sure u cleared the old pods dependencies.

**Comment by CyrusZei** [comment]
Hi man, I will try making a new project and try it. thx

**Comment by CyrusZei** [comment]
Okej, this is the steps that I am doing.

If I create a new React-native init project and add Agora it works.
As soon as I add firebase it breaks.

If I go the other way around and add firebase first and then Agora it gives me the same error
about Agora.

If you want a live example on this I can give you access to my private Repo and then you can try to add Agora to it.

**This is the errors I am getting**

<img width="859" alt="Screenshot 2019-03-17 at 20 49 56" src="https://user-images.githubusercontent.com/5053903/54497039-421f1a00-48f6-11e9-8482-d36fc6d8b067.png">

**framework search path for Libraries -> RCTAgora**

<img width="802" alt="Screenshot 2019-03-17 at 20 51 13" src="https://user-images.githubusercontent.com/5053903/54497054-7e527a80-48f6-11e9-8d5f-c60be485cca1.png">

**Header search paths for Libraries -> RCTAgora**
<img width="806" alt="Screenshot 2019-03-17 at 20 52 15" src="https://user-images.githubusercontent.com/5053903/54497064-99bd8580-48f6-11e9-8fac-12f0f69c3c11.png">

**Library search Paths for Libraries -> RCTAgora**
![Uploading Screenshot 2019-03-17 at 20.52.54.png…]()

**I do get that the libRctAgora.a is red**

<img width="280" alt="Screenshot 2019-03-17 at 20 53 48" src="https://user-images.githubusercontent.com/5053903/54497091-d38e8c00-48f6-11e9-8e82-7b5b9defff2f.png">

**Link binary with Libraries, I have added the libRCTAgora.a there**
<img width="691" alt="Screenshot 2019-03-17 at 20 54 34" src="https://user-images.githubusercontent.com/5053903/54497099-f4ef7800-48f6-11e9-9b39-e1f26c5fdc77.png">

any idea or pointers on where I can start looking?

**Comment by CyrusZei** [comment]
never  mind, 

for anyone that have this problem is has to do with Firebase/firestore  gRPC-C++ issue

[https://github.com/invertase/react-native-firebase/issues/1984](url)

**Comment by CyrusZei** [comment]
for anybody that has this problem , this is how I fixed it

https://github.com/firebase/firebase-ios-sdk/issues/1916#issuecomment-474153045

**Comment by Matrixbirds** [comment]
so did u fix it? it seems to be a compiling environment problem. Our sdk doesn't have gRPC library as dependency. [react-native-agora-gitter](https://gitter.im/react-native-agora/community) If u are regarding any compiling environment problem, we recommend u send it into our channel, u will get more quickly reply here and anyway thx for ur reference.

**Comment by CyrusZei** [comment]
hi man, 
yes. I changed the header search for the pods to non-recursive and it worked. I will upload an answer to this issue since I think people might bump into this problem.

and write a detailed answer with images and step by step guide.

**Comment by tmjordan** [comment]
@CyrusZei @Matrixbirds i think i have the same problem, unable to build

**Comment by CyrusZei** [comment]
I will write a detailed answer later today. Are you using firebase and Agora ?

**Comment by tmjordan** [comment]
@CyrusZei yes i am using firebase too

**Comment by tmjordan** [comment]
![image](https://user-images.githubusercontent.com/27443995/54598563-0ccf1500-4a39-11e9-8f59-9e1dd3b073f4.png)

**Comment by tmjordan** [comment]
@CyrusZei for me, i'm not even able to build in debug mode.
Not sure if it is related to firebase. Did i miss something?
Anyway i will wait you answer. Thanks man

**Comment by tmjordan** [comment]
@CyrusZei your answer about changing the header search of the pods to "non recursive", works for me. Thanks

**Comment by CyrusZei** [comment]
@tmjordan no problem man , glad it works!!

**Comment by tmjordan** [comment]
@CyrusZei please man, did you succeed to make a video call.
I'm trying to do that but only audio works, the video is not displayed in my view.

**Comment by CyrusZei** [comment]
@tmjordan yes everything works on my end. I am working on ios

**Comment by tmjordan** [comment]
@tmjordan please man, can you share a simple example of how you implemented it?

**Comment by tmjordan** [comment]
@CyrusZei please man, can you share a simple example of how you implemented it?

**Comment by CyrusZei** [comment]
@tmjordan yes, still working on the doc here and I am making it so that this repo can use it as a doc if they want to. I don't have much left on it and will continue working on it after work, but it will be done today.

**Comment by tmjordan** [comment]
@CyrusZei  woohh, man thank you very much. we definitely improve the doc, cause it is a good lib.
Hope it won't be only in chinese lol

**Comment by CyrusZei** [comment]
@tmjordan no problem at all. I also Love this lib and what Agora does. So If I can help others not spend 4 days on this problem, I am glad to make the doc on how I did this.

I will do it in English so don't you worry 😄

**Comment by CyrusZei** [comment]
@tmjordan I made a Pr to the readme file so will see if they accept it.

For your issue follow this


# React native Agora iOS Installation
#### Minimum compatibility
* React native 0.58.x
* IOS SDK 8.0+
* Android 5.0+ x86 arm64 armv7a

#### 1. open up your terminal and write this :
When it comes to the version nr you can put any version you like as long as it it compatibility
```sh
$ react-native init agoraguide --version react-native@0.58
```

#### 2. cd into your project folder
```sh
$ cd agoraguide
```
#### 3. install npm package react-native-agora

with npm


```sh
$ npm install --save react-native-agora
```

or yarn

```sh
$ yarn add react-native-agora
```

#### 4. we need to link the Agora library
run this command in your terminal
```sh
$ react-native link react-native-agora
```

#### 5. cd into your ios folder
```sh
$ cd ios
```

#### 6. we need to initialize pod
if you don't have cocopods installed run this command in your terminal
```sh
$ sudo gem install Cocoapods
```
after you have installed Cocopods run this command inside of your ios folder
```sh
$ pod init
```
and then we need to install the pods
```sh
$ pod install
```
if you get a error from Cocopods saying something like this :

<img width="865" alt="06" src="https://user-images.githubusercontent.com/5053903/54722990-55382100-4b66-11e9-8e15-3a0dedb45240.png">

then you need to open up your "Podfile" and remove the part that is blue marked in the picture below

#### *before*
<img width="1680" alt="06a" src="https://user-images.githubusercontent.com/5053903/54722995-5b2e0200-4b66-11e9-817f-bc20f0b21575.png">


#### *after*
<img width="1680" alt="06b" src="https://user-images.githubusercontent.com/5053903/54723005-63863d00-4b66-11e9-87dd-2694be8486a2.png">
<img width="1442" alt="06c" src="https://user-images.githubusercontent.com/5053903/54723013-6e40d200-4b66-11e9-8b9f-8bc86f823348.png">


we need to add this code at the bottom to our pod file
```sh
post_install do |installer|
  installer.pods_project.targets.each do |target|

    # The following is needed to ensure the "archive" step works in XCode.
    # It removes React & Yoga from the Pods project, as it is already included in the main project.
    # Without this, you'd see errors when you archive like:
    # "Multiple commands produce ... libReact.a"
    # "Multiple commands produce ... libyoga.a"

    targets_to_ignore = %w(React yoga)
    
    if targets_to_ignore.include? target.name
      target.remove_from_project
    end

  end
end
```
This is how your podfile should look like
<img width="1442" alt="06c" src="https://user-images.githubusercontent.com/5053903/54723018-7731a380-4b66-11e9-88a0-aa8135b23746.png">



after that you can run this command again
```sh
$ pod install
```

#### 7. Open up your xcode project *[project name].xcworkspace* inside in ios folder

<img width="960" alt="07" src="https://user-images.githubusercontent.com/5053903/54723030-81ec3880-4b66-11e9-9f3c-c11078dcda6d.png">


#### 8. expand your project folder and right click on the *"Libraries"* folder and choose *"add files to [project name]"*

<img width="428" alt="08" src="https://user-images.githubusercontent.com/5053903/54723035-87e21980-4b66-11e9-9bab-1e4a42d90436.png">


#### 9. follow the image below to find the RCTAgora lib

<img width="362" alt="09a" src="https://user-images.githubusercontent.com/5053903/54723038-8d3f6400-4b66-11e9-96f2-922e15113a79.png">


the path is  node_modules => react-native-agora => ios => RCTAgora.xcodeproj

make sure you check so that those are checked

<img width="825" alt="09b" src="https://user-images.githubusercontent.com/5053903/54723041-90d2eb00-4b66-11e9-99f2-81ce0c4687e7.png">


If the file is greyed out it means you already have it inside of you library folder.
Check so that RCTAgora.xcodeproj are inside of your "Libraries" folder
<img width="325" alt="09c" src="https://user-images.githubusercontent.com/5053903/54723050-95979f00-4b66-11e9-8a4f-3d23de9399c2.png">



#### 10. we need to add the framework
expand your "Frameworks" folder and you should see the "AgoraRtcEngineKit.framework" are red.
<img width="291" alt="10a" src="https://user-images.githubusercontent.com/5053903/54723057-9af4e980-4b66-11e9-95d3-b4ac06e460a2.png">



right click and delete that
Left click on your "RCTAgora.xcodeproj" and clöick on "Build Phases"
<img width="1135" alt="10b" src="https://user-images.githubusercontent.com/5053903/54723069-a0eaca80-4b66-11e9-8a05-3b189c712c0e.png">



left click on the "AgoraRtcEngineKit.framework" in the list and click on the "-"(minus sign) to remove it from the list.
<img width="1141" alt="10c" src="https://user-images.githubusercontent.com/5053903/54723075-a6481500-4b66-11e9-9b43-e495a305a66c.png">



then click on the "+"(plus sign) so that we can add the framework.
Click on the "Add other..." button
<img width="455" alt="10d" src="https://user-images.githubusercontent.com/5053903/54723081-ae07b980-4b66-11e9-83ff-caee229b2a65.png">



then we need to navigate and find our framwork
<img width="1018" alt="10e" src="https://user-images.githubusercontent.com/5053903/54723087-b3650400-4b66-11e9-9853-d19f6b2dd2f5.png">



the path is : ios => Pods => AgoraRtcEngine_iOS => AgoraRtcEngineKit.framework and click on "add"

#### 11. at last we need to link the library
click on your project on the left and then click on "Build Phases" and then expand "Link Binary With Libraries" and then click on the "+"(plug sign)
<img width="1149" alt="11" src="https://user-images.githubusercontent.com/5053903/54723100-bb24a880-4b66-11e9-9ea3-3e353369523b.png">


Search for libRCTAGora and click on add
<img width="873" alt="12" src="https://user-images.githubusercontent.com/5053903/54723105-c37ce380-4b66-11e9-9397-4badcf0cc3e7.png">



if you cant find it in your list check so that you dont already have it

----------------------------------------------
### Troubleshooting

if you get some errors like the pictures below
<img width="267" alt="t01" src="https://user-images.githubusercontent.com/5053903/54723116-ce377880-4b66-11e9-82a1-d519a1a796f0.png">
<img width="859" alt="t02" src="https://user-images.githubusercontent.com/5053903/54723122-d394c300-4b66-11e9-87f9-51e770448c40.png">





the chances are that you have some framework that already have imported time.h something like firestore.

Expand your "Libraries" and then click on "RCTAgora.xcodeproj". Then click on "Build settings" and search for "Header search paths" 
<img width="1144" alt="t03" src="https://user-images.githubusercontent.com/5053903/54723130-db546780-4b66-11e9-9072-4aed1a0c2a74.png">



Doubble click on the path
<img width="1242" alt="t04" src="https://user-images.githubusercontent.com/5053903/54723143-e27b7580-4b66-11e9-8845-b5c7311bc9e4.png">


and change the Pods path from "recursive" to non-recursive
<img width="1292" alt="t05" src="https://user-images.githubusercontent.com/5053903/54723146-e5766600-4b66-11e9-8f3c-0f008d6e2146.png">

**Comment by tmjordan** [comment]
@CyrusZei Very well explained, it will help other people. I'm using react native 0.57.8 in my project, and it works, so i don't think the minimum compatibility is 0.58.

**Comment by CyrusZei** [comment]
@tmjordan great that it helped you. Yeah, I haven't tested it below 0.58, but the doc says 0.58.x + so I was going with that 😄

**Comment by tmjordan** [comment]
@CyrusZei thanks, but i have other problems with the lib. when i make a video call, there is a zoom when recording the video. i don't want that. Did you have the same problem?

**Comment by CyrusZei** [comment]
@tmjordan yeah I have also noticed that, but I am working on a different part and will be looking on the "Zoom" thing after that. I am pretty sure there is a way to "zoom" out, but I know that the ios also "zoom" in when you choose video

**Comment by tmjordan** [comment]
Yes there is a function setCameraZoomFactor on iOS, but when i try, it throws an error. I created an issue about that. If you find the solution, it will be nice to share :)
I also want to mirror the video when using front camera. In local, it is mirrored, but it is not in remote. That's weird.
Anyway i think i'm going to work on a different part for now.

**Comment by tmjordan** [comment]
@CyrusZei Yes there is a function setCameraZoomFactor on iOS, but when i try, it throws an error. I created an issue about that. If you find the solution, it will be nice to share :)
I also want to mirror the video when using front camera. In local, it is mirrored, but it is not in remote. That's weird.
Anyway i think i'm going to work on a different part for now.

**Comment by tmjordan** [comment]
@CyrusZei Yes there is a function setCameraZoomFactor , but when i try, it throws an error on iOS. I created an issue about that. If you find the solution, it will be nice to share :)
I also want to mirror the video when using front camera. In local, it is mirrored, but it is not in remote. That's weird.
Anyway i think i'm going to work on a different part for now.

**Comment by CyrusZei** [comment]
@tmjordan Yeah, I will look into this and see. Tell you if I solve it

**Comment by Matrixbirds** [comment]
so u guys have already done. it should be closed.

**Comment by abhilash300singh** [comment]
After following the steps, I was able to get other errors fixed, but instead this came up - 

```In file included from /Users/abhilashsingh/guidr/rn/node_modules/react-native-agora/ios/RCTAgora/RCTAgoraViewManager.m:9:
/Users/abhilashsingh/guidr/rn/node_modules/react-native-agora/ios/RCTAgora/RCTAgoraViewManager.h:9:9: fatal error: 'React/Views/RCTViewManager.h' file not found
#import <React/Views/RCTViewManager.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by langan** [comment]
@CyrusZei You sir are made of win!  Thank you so much!

**Comment by harshalijain** [comment]
> @tmjordan I will write a detailed answer later today. Are you using firebase and Agora ?

Hi,
Yes I am using firebase and agora together and getting above issue. Can you suggest any solution?

**Comment by KarenQiao** [comment]
> After following the steps, I was able to get other errors fixed, but instead this came up -
> 
> ```
> /Users/abhilashsingh/guidr/rn/node_modules/react-native-agora/ios/RCTAgora/RCTAgoraViewManager.h:9:9: fatal error: 'React/RCTViewManager.h' file not found
> #import <React/RCTViewManager.h>
>         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> ```
> 
> Any ideas?

same issue? Have you solved it？

**Comment by KarenQiao** [comment]
> @tmjordan I made a Pr to the readme file so will see if they accept it.
> 
> For your issue follow this
> 
> # React native Agora iOS Installation
> #### Minimum compatibility
> * React native 0.58.x
> * IOS SDK 8.0+
> * Android 5.0+ x86 arm64 armv7a
> 
> #### 1. open up your terminal and write this :
> When it comes to the version nr you can put any version you like as long as it it compatibility
> 
> ```shell
> $ react-native init agoraguide --version react-native@0.58
> ```
> 
> #### 2. cd into your project folder
> ```shell
> $ cd agoraguide
> ```
> 
> #### 3. install npm package react-native-agora
> with npm
> 
> ```shell
> $ npm install --save react-native-agora
> ```
> 
> or yarn
> 
> ```shell
> $ yarn add react-native-agora
> ```
> 
> #### 4. we need to link the Agora library
> run this command in your terminal
> 
> ```shell
> $ react-native link react-native-agora
> ```
> 
> #### 5. cd into your ios folder
> ```shell
> $ cd ios
> ```
> 
> #### 6. we need to initialize pod
> if you don't have cocopods installed run this command in your terminal
> 
> ```shell
> $ sudo gem install Cocoapods
> ```
> 
> after you have installed Cocopods run this command inside of your ios folder
> 
> ```shell
> $ pod init
> ```
> 
> and then we need to install the pods
> 
> ```shell
> $ pod install
> ```
> 
> if you get a error from Cocopods saying something like this :
> 
> <img alt="06" width="865" src="https://user-images.githubusercontent.com/5053903/54722990-55382100-4b66-11e9-8e15-3a0dedb45240.png">
> 
> then you need to open up your "Podfile" and remove the part that is blue marked in the picture below
> 
> #### _before_
> <img alt="06a" width="1680" src="https://user-images.githubusercontent.com/5053903/54722995-5b2e0200-4b66-11e9-817f-bc20f0b21575.png">
> 
> #### _after_
> <img alt="06b" width="1680" src="https://user-images.githubusercontent.com/5053903/54723005-63863d00-4b66-11e9-87dd-2694be8486a2.png">
> 
> <img alt="06c" width="1442" src="https://user-images.githubusercontent.com/5053903/54723013-6e40d200-4b66-11e9-8b9f-8bc86f823348.png">
> 
> we need to add this code at the bottom to our pod file
> 
> ```shell
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
> 
>     # The following is needed to ensure the "archive" step works in XCode.
>     # It removes React & Yoga from the Pods project, as it is already included in the main project.
>     # Without this, you'd see errors when you archive like:
>     # "Multiple commands produce ... libReact.a"
>     # "Multiple commands produce ... libyoga.a"
> 
>     targets_to_ignore = %w(React yoga)
>     
>     if targets_to_ignore.include? target.name
>       target.remove_from_project
>     end
> 
>   end
> end
> ```
> 
> This is how your podfile should look like
> <img alt="06c" width="1442" src="https://user-images.githubusercontent.com/5053903/54723018-7731a380-4b66-11e9-88a0-aa8135b23746.png">
> 
> after that you can run this command again
> 
> ```shell
> $ pod install
> ```
> 
> #### 7. Open up your xcode project _[project name].xcworkspace_ inside in ios folder
> <img alt="07" width="960" src="https://user-images.githubusercontent.com/5053903/54723030-81ec3880-4b66-11e9-9f3c-c11078dcda6d.png">
> 
> #### 8. expand your project folder and right click on the _"Libraries"_ folder and choose _"add files to [project name]"_
> <img alt="08" width="428" src="https://user-images.githubusercontent.com/5053903/54723035-87e21980-4b66-11e9-9bab-1e4a42d90436.png">
> 
> #### 9. follow the image below to find the RCTAgora lib
> <img alt="09a" width="362" src="https://user-images.githubusercontent.com/5053903/54723038-8d3f6400-4b66-11e9-96f2-922e15113a79.png">
> 
> the path is node_modules => react-native-agora => ios => RCTAgora.xcodeproj
> 
> make sure you check so that those are checked
> 
> <img alt="09b" width="825" src="https://user-images.githubusercontent.com/5053903/54723041-90d2eb00-4b66-11e9-99f2-81ce0c4687e7.png">
> 
> If the file is greyed out it means you already have it inside of you library folder.
> Check so that RCTAgora.xcodeproj are inside of your "Libraries" folder
> <img alt="09c" width="325" src="https://user-images.githubusercontent.com/5053903/54723050-95979f00-4b66-11e9-8a4f-3d23de9399c2.png">
> 
> #### 10. we need to add the framework
> expand your "Frameworks" folder and you should see the "AgoraRtcEngineKit.framework" are red.
> <img alt="10a" width="291" src="https://user-images.githubusercontent.com/5053903/54723057-9af4e980-4b66-11e9-95d3-b4ac06e460a2.png">
> 
> right click and delete that
> Left click on your "RCTAgora.xcodeproj" and clöick on "Build Phases"
> <img alt="10b" width="1135" src="https://user-images.githubusercontent.com/5053903/54723069-a0eaca80-4b66-11e9-8a05-3b189c712c0e.png">
> 
> left click on the "AgoraRtcEngineKit.framework" in the list and click on the "-"(minus sign) to remove it from the list.
> <img alt="10c" width="1141" src="https://user-images.githubusercontent.com/5053903/54723075-a6481500-4b66-11e9-9b43-e495a305a66c.png">
> 
> then click on the "+"(plus sign) so that we can add the framework.
> Click on the "Add other..." button
> <img alt="10d" width="455" src="https://user-images.githubusercontent.com/5053903/54723081-ae07b980-4b66-11e9-83ff-caee229b2a65.png">
> 
> then we need to navigate and find our framwork
> <img alt="10e" width="1018" src="https://user-images.githubusercontent.com/5053903/54723087-b3650400-4b66-11e9-9853-d19f6b2dd2f5.png">
> 
> the path is : ios => Pods => AgoraRtcEngine_iOS => AgoraRtcEngineKit.framework and click on "add"
> 
> #### 11. at last we need to link the library
> click on your project on the left and then click on "Build Phases" and then expand "Link Binary With Libraries" and then click on the "+"(plug sign)
> <img alt="11" width="1149" src="https://user-images.githubusercontent.com/5053903/54723100-bb24a880-4b66-11e9-9ea3-3e353369523b.png">
> 
> Search for libRCTAGora and click on add
> <img alt="12" width="873" src="https://user-images.githubusercontent.com/5053903/54723105-c37ce380-4b66-11e9-9397-4badcf0cc3e7.png">
> 
> if you cant find it in your list check so that you dont already have it
> 
> ### Troubleshooting
> if you get some errors like the pictures below
> <img alt="t01" width="267" src="https://user-images.githubusercontent.com/5053903/54723116-ce377880-4b66-11e9-82a1-d519a1a796f0.png">
> <img alt="t02" width="859" src="https://user-images.githubusercontent.com/5053903/54723122-d394c300-4b66-11e9-87f9-51e770448c40.png">
> 
> the chances are that you have some framework that already have imported time.h something like firestore.
> 
> Expand your "Libraries" and then click on "RCTAgora.xcodeproj". Then click on "Build settings" and search for "Header search paths"
> <img alt="t03" width="1144" src="https://user-images.githubusercontent.com/5053903/54723130-db546780-4b66-11e9-9072-4aed1a0c2a74.png">
> 
> Doubble click on the path
> <img alt="t04" width="1242" src="https://user-images.githubusercontent.com/5053903/54723143-e27b7580-4b66-11e9-8845-b5c7311bc9e4.png">
> 
> and change the Pods path from "recursive" to non-recursive
> <img alt="t05" width="1292" src="https://user-images.githubusercontent.com/5053903/54723146-e5766600-4b66-11e9-8f3c-0f008d6e2146.png">

thanks!!! but that's when I finished all the steps，There are other problems。

-lcrypto is not an object file (not allowed in a library)
