### ISSUE TITLE
RctEngine.setCameraZoomFactor function not working on iOS

### ISSUE THREAD

**Issue by tmjordan** [syanbo/react-native-agora#52]
I wanted to disable the zoom on the video chat, so i called the function:
RctEngine.setCameraZoomFactor(1.0). But it throws an error:

Exception 'The RCTPromiseResolveBlock must be the second to last parameter in - [RCTAgora setCameraZoomFactor:resolve:]' was thrown while invoking setCameraZoomFactor on target Agora with params (1, 3040, 3041).

**Comment by Matrixbirds** [comment]
Okay, we will check it ASAP.

**Comment by Matrixbirds** [comment]
Pls u provide which version of npm module used and compiling errors here.

**Comment by tmjordan** [comment]
@Matrixbirds, the error happens only on iOS. I'm using:
- React native 0.57.8
- react-native-agora 2.3.3-alpha.5

![IMG_2817](https://user-images.githubusercontent.com/27443995/54765836-7fd3b980-4bfa-11e9-86c7-856115b5ed02.PNG)
![IMG_2818](https://user-images.githubusercontent.com/27443995/54765834-7fd3b980-4bfa-11e9-9b9b-460c96fc06d5.PNG)
![IMG_2819](https://user-images.githubusercontent.com/27443995/54765835-7fd3b980-4bfa-11e9-8a38-4b337ff1c367.PNG)

**Comment by Matrixbirds** [comment]
You can update to 2.3.3-alpha.6. I have already fixed it. thx for your issue.

**Comment by tmjordan** [comment]
@Matrixbirds thank you
