### ISSUE TITLE
Cannot build: Native module cannot be null or unknown type 'namespace'

### ISSUE THREAD

**Issue by joelgetaction** [syanbo/react-native-agora#54]
Hi,

Thanks for making this available, it's very helpful and I appreciate all of your hard work!

I have followed your instructions at https://github.com/syanbo/react-native-agora/blob/master/docs/v2/ios.md exactly, but one of two bugs happens:

- If I **do not** add libRCTAgora.a to my main target's "Linked Frameworks and Libraries" then at runtime I get "Native Module cannot be null" any time I try to use `Agora` as a native module.
- If I **do** add libRCTAgora.a to my main target's "Linked Frameworks and Libraries" then it fails to build with a bunch of errors like the following:
```
Showing Recent Messages
/Users/joel/src/getaction/bidvid/AgoraTestExpoBare/node_modules/react-native-agora/ios/RCTAgora/AgoraConst.h:9:9: While building module 'AgoraRtcEngineKit' imported from /Users/joel/src/getaction/bidvid/AgoraTestExpoBare/node_modules/react-native-agora/ios/RCTAgora/AgoraConst.h:9:

/ios/Pods/AgoraRtcEngine_iOS/AgoraRtcEngineKit.framework/Headers/AgoraRtcEngineKit.h:8:9: While building module 'Foundation' imported from ../../../ios/Pods/AgoraRtcEngine_iOS/AgoraRtcEngineKit.framework/Headers/AgoraRtcEngineKit.h:8:

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:10: While building module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:10: While building module 'Darwin' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:

/<module-includes>:29:9: In file included from <module-includes>:29:

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/string.h:180:10: In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/string.h:180:

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/strings.h:92:10: In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/strings.h:92:

/ios/Pods/Folly/folly/string.h:20:10: In file included from ../../../ios/Pods/Folly/folly/string.h:20:

```
- If I set files to compile as "Objective-C++" then I get a bunch of "symbol "abort" not found in the global namespace"

Either way, I simply cannot get react-native-agora to compile .... And if it does compile, it crashes at runtime with "Native Module cannot be null".

Any ideas?

I'm on:
- macOS 10.14.3
- Xcode 10.1
- React Native 0.58.6
- react-native-agora 2.3.3-alpha.6

Thanks!

**Comment by Matrixbirds** [comment]
Okay, I just build it as usual in my environment, Probably you could give me your demo code in your github repository so that I can reproduce it and help you to locate the compiling issue.

**Comment by joelgetaction** [comment]
Hi @Matrixbirds thank you for responding so quickly.  I'd be happy to upload a demo repo that you could compile.  It's late at night here - I will do that in the morning and let you know when it's uploaded.  Thanks again.

**Comment by Matrixbirds** [comment]
This issue is already fixed [here](https://github.com/AgoraIO-Community/Agora-RN-Quickstart/issues/6), If you have same issue pls follow this link.
