### ISSUE TITLE
How to use voice chat only?

### ISSUE THREAD

**Issue by guopeng1994** [syanbo/react-native-agora#55]
i only want to use voice chat, but in 'init' function i found 'enableVideo', and it can not be close, so i think this parameter should be controlled. because sometimes it's unnecessary

am i right?

**Comment by Matrixbirds** [comment]
Yep u r right. I should redesign the `init` function I think should be able support switch option parameter to invoke enableVideo/Audio for us.

**Comment by guopeng1994** [comment]
@Matrixbirds hope this will be released soon.

**Comment by Matrixbirds** [comment]
I will implement audio only video in next version.

**Comment by Matrixbirds** [comment]
It is already support in 2.3.3-alpha.7

**Comment by guopeng1994** [comment]
all right. thanks

**Comment by mohamed-sultan** [comment]
how can i disable video
i need only voice call in my app

**Comment by jsmile1994** [comment]
How can i just use voice call? Because i don't want to waste mobile data to load video while i don't need that video.
Thank you very much!

**Comment by Matrixbirds** [comment]
@mohamed-sultan @jsmile1994 
u can pass mode: 0 with init method and it will only enable capture & send audio data through agora cloud service.
```
RtcEngine.init({
   ...,
   mode: 0
});
```
