### ISSUE TITLE
Argument list too long: recursive header expansion failed

### ISSUE THREAD

**Issue by duongduckien** [syanbo/react-native-agora#56]
I'm having a problem.  How to fix it? Thanks.
<img width="923" alt="Screen Shot 2019-04-01 at 4 46 13 AM" src="https://user-images.githubusercontent.com/22634319/55295610-4d675f00-5439-11e9-99da-afd892d7245c.png">

**Comment by Matrixbirds** [comment]
Did you follow the readme setup steps and then still get the error?
Please provide ur compiling environment.
react native version.
react-native-agora version.
xcode version.
I didn't get this error in my environment.

**Comment by Matrixbirds** [comment]
If you can, I think that should be better way to upload your issue repo to Github that i can help u to fix that.

**Comment by duongduckien** [comment]
I found the reason for this issue. After I installed Firebase/Database. This is my package.json file
{
  "name": "Trust",
  "version": "0.0.1",
  "private": true,
  "rnpm": {
    "assets": [
      "./src/assets/fonts/"
    ]
  },
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "devtools": "react-devtools"
  },
  "dependencies": {
    "@expo/vector-icons": "^9.0.0",
    "@react-native-community/async-storage": "^1.2.2",
    "@types/lodash": "^4.14.123",
    "@types/react-native-drawer": "^2.5.2",
    "@types/react-native-i18n": "^2.0.0",
    "@types/react-native-loading-spinner-overlay": "^0.5.1",
    "@types/react-native-vector-icons": "^4.6.4",
    "@types/react-navigation": "^3.0.1",
    "@types/react-redux": "^6.0.12",
    "axios": "^0.18.0",
    "firebase": "^5.9.2",
    "moment": "^2.24.0",
    "native-base": "^2.10.0",
    "react": "16.6.3",
    "react-native": "^0.59.2",
    "react-native-agora": "^2.3.3-alpha.5",
    "react-native-awesome-alerts": "^1.2.0",
    "react-native-elements": "^0.19.1",
    "react-native-firebase": "^5.2.3",
    "react-native-flash-message": "^0.1.10",
    "react-native-gifted-chat": "^0.7.2",
    "react-native-i18n": "^2.0.15",
    "react-native-linkedin": "^1.3.1",
    "react-native-linkedin-signin": "^0.0.2",
    "react-native-loading-spinner-overlay": "^1.0.1",
    "react-native-router-flux": "^4.0.6",
    "react-native-vector-icons": "^6.2.0",
    "react-navigation": "^3.0.9",
    "react-redux": "^6.0.0",
    "redux": "^4.0.1",
    "redux-saga": "^0.16.2"
  },
  "devDependencies": {
    "@types/react": "^16.7.18",
    "@types/react-native": "^0.57.25",
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.51.1",
    "react-devtools": "^3.6.1",
    "react-native-typescript-transformer": "^1.2.11",
    "react-test-renderer": "16.6.3",
    "typescript": "^3.2.2"
  },
  "jest": {
    "preset": "react-native"
  }
}

Pod file
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Trust' do
  
  # pod 'AgoraRtcEngine_iOS'

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  pod 'react-native-agora', :path => '../node_modules/react-native-agora'

end

**Comment by duongduckien** [comment]
But I can't resolve it.

**Comment by duongduckien** [comment]
This is my repository: https://github.com/duongduckien/Trust.git

**Comment by duongduckien** [comment]
Can you help me? Thanks!

**Comment by Matrixbirds** [comment]
I m already clone your repo and trying setup it on local.

**Comment by Matrixbirds** [comment]
Okay, I find the problem and fixed the compiling environment already, but I still don't know why.
I will do more work around to find the reason. You could try below step to fix it in your Xcode.
1. Find `RCTAgora.xcodeproj` in project Libraries folder. and the select the target `RCTAgora` -> `Build Settings` -> `Header Search Paths` + `Framework Search Paths`, change `recursive` to `non-recursive` and replace all `../ios/Pods/` to `../ios/Pods/AgoraRtcEngine_iOS` as the picture.
![image](https://user-images.githubusercontent.com/9990676/55457040-4c8e2300-561b-11e9-8d33-d28ec076993e.png)
![image](https://user-images.githubusercontent.com/9990676/55457054-54e65e00-561b-11e9-8e9f-d9427171702a.png)

**Comment by Matrixbirds** [comment]
I can't resolved the `GoogleService-Info.plist` but i can compiled the RCTAgora module in my Xcode environment's. I think you could try my fix step first.

**Comment by duongduckien** [comment]
> I can't resolved the `GoogleService-Info.plist` but i can compiled the RCTAgora module in my Xcode environment's. I think you could try my fix step first.

**Comment by duongduckien** [comment]
I'm trying the first way. Thanks!

**Comment by duongduckien** [comment]
@Matrixbirds It's working now. Thanks!
