### ISSUE TITLE
Guidelines around receiving calls in background

### ISSUE THREAD

**Issue by abhilash300singh** [syanbo/react-native-agora#57]
Hi, are there any guidelines/best practices around receiving calls when the app is in background. I know signaling isn't a part of this sdk. I'm using websockets for signaling, but I'm not sure how to make things work when in background. I could probably use https://www.npmjs.com/package/react-native-background-timer to check some remote state after every defined interval. Just wondering if you guys have come across this situation and have anything to suggest on what could be the best way.

Thanks.

**Comment by tmjordan** [comment]
@abhilash300singh to achieve that, i think you should use notifications to wake up your application when receiving a call. On iOS you have VoIP Notifications

**Comment by Matrixbirds** [comment]
I agree with tmjordan, probably we can consider it in the future version when the signaling sdk is in develop.
