### ISSUE TITLE
Typescript?

### ISSUE THREAD

**Issue by Jonovono** [syanbo/react-native-agora#60]
Seeing this error:

```
Could not find a declaration file for module 'react-native-agora'. '/Users/jordan/Desktop/BunchV5/node_modules/react-native-agora/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-native-agora` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-agora';`ts(7016)
```

Is typescript not setup properly or am I missing something?

**Comment by Matrixbirds** [comment]
Because this project still using javascript code as runtime. So if you are using with typescript you need to defined declaration mannual in your project .d.ts file.
```typescript
// types.d.ts
declare module "react-native-agora" {
   const ReactNativeAgora;
   export default ReactNativeAgora;
}
```

**Comment by Jonovono** [comment]
Cool, makes sense, thanks @Matrixbirds, and then I would have to update this with types for the different events and what not that agora can send over?

**Comment by Jonovono** [comment]
@Matrixbirds do you have plans to submit a types definition to definitely typed or something? Otherwise, I might see if I can submit a PR to it with types for this library, but don't want to if this is already something you guys will be doing.
