### ISSUE TITLE
ability to save or not save video call

### ISSUE THREAD

**Issue by Solomon198** [syanbo/react-native-agora#61]
Libary is very ok but please add an ability to save or not save a video call without it my project is useless

**Comment by Matrixbirds** [comment]
did you mean to recording the video/audio call?

**Comment by Solomon198** [comment]
yeah

**Comment by Matrixbirds** [comment]
Sorry, for late reply, It was duplicate, I already schedule it in the next 2.9.0 release, If you want to follow changes, you could move to [this link](https://github.com/syanbo/react-native-agora/issues/81). Thx.
