### ISSUE TITLE
RtcEngine.setCameraZoomFactor

### ISSUE THREAD

**Issue by CyrusZei** [syanbo/react-native-agora#62]
I think there is an issue with the `RtcEngine.setCameraZoomFactor`.

I looked at the doc and some samples and they all expect this to work.

`RtcEngine.setCameraZoomFactor(1.0)`
When I look at the RtcEngine it says that the setCameraZoomFactor is a promise.
Is his only for IOS or? I am using react native

<img width="1349" alt="Screenshot 2019-04-14 at 03 50 56" src="https://user-images.githubusercontent.com/5053903/56087305-97ecd080-5e68-11e9-963e-9d298963128e.png">

**Comment by CyrusZei** [comment]
Never mind, I updated to version `2.3.3-alpha.6` and it worked, but I feel like the camera is still zoomed in even if I enter `RtcEngine.setCameraZoomFactor(1)`

**Comment by tmjordan** [comment]
@CyrusZei same problem for me, it was a bug on iOS, the last version 2.3.3-alpha.7 has fixed that.
But yes the camera is still zoomed.

**Comment by CyrusZei** [comment]
I feel like the doc could have more examples. I mean how do I publish a stream and get the URL for it? so that I can add that into a video preview for others to watch?

**Comment by Matrixbirds** [comment]
`RtcEngine.setCameraZoomFactor(1.0)` is work fine for me. It just control the camera zoom ratio. you could find on our [docs](https://docs.agora.io/en/Video/API%20Reference/oc/Classes/AgoraRtcEngineKit.html#//api/name/setCameraZoomFactor:)
I cannot reproduce it. If you means the camera is auto focusing, iOS platform will enable auto focusing as usual, so if you want to fixed that problem, Please wait for the next version, we will support gesture for iOS & android ASAP. 

If you can please provider your demo project and paste github link here. I will do work around for you.

**Comment by CyrusZei** [comment]
@Matrixbirds If you open up your iphone camera you will see that baseline of the zoom, but if you open up the agora camera when you broadcast you will see that it is "Zoomed".

I have got the zoom to work, but I feel like the camera is "zoomed". It feels like the zoom is set to 2.0 instead of 1.0

**Comment by tmjordan** [comment]
@CyrusZei @Matrixbirds  yes i agree, the camera is zoomed at the remote side and it is also not mirrored.
I did not try on android, because i don't have a device.

**Comment by CyrusZei** [comment]
This might be a bug since I talked to Agora on the slack channel

**Comment by CyrusZei** [comment]
Okej guys,

I got help from Agora and this fixed it for me.


in your 

`videoEncoderConfig: {
        width: 360,
        height: 480,
        bitrate: 0,
        frameRate: FPS15,
      },`

**Comment by tmjordan** [comment]
@CyrusZei thank you man, it's working for me too. But i noticed something, it was zoomed because i had set the orientation_mode with  "FixedLandscape" value in the videoEncoderConfig. Remove that makes it work.
Here's what i had:

```
         videoEncoderConfig: {
                width: 360,
                height: 480,
                bitrate: 1,
                frameRate: FPS30,
                orientationMode: FixedLandscape,
            },
```

**Comment by CyrusZei** [comment]
yes, the Agora team told me to remove the FixedLandscape and then it worked.
