### ISSUE TITLE
client ?

### ISSUE THREAD

**Issue by CyrusZei** [syanbo/react-native-agora#63]
When I look at the docs 
https://docs.agora.io/en/Interactive%20Broadcast/API%20Reference/web/interfaces/agorartc.client.html

They are referring to the `client`, but I have gone over the react-native-agora package code and can't find any expert on the `client`. Is this implemented?

**Comment by Matrixbirds** [comment]
Because the Native SDK is a totally different design, you could consider `RtcEngine` is our client as the web version's `client` you see on the document center. And We will considering to make our rn sdk more simply to used.

**Comment by CyrusZei** [comment]
okej, that is great.

So I import : `import { RtcEngine, AgoraView } from 'react-native-agora';`

Then if I follow this doc (https://docs.agora.io/en/Interactive%20Broadcast/publish_web_live?platform=Web)

I should write `RtcEngine.createStream ` with the object key and value pair. This is the part that I can't find in the docs. I am trying to figure all this out and as soon as I understand the whole thing I will make a detailed Pr with a DOC that goes step by step on how to do the whole thing. I am apart of the all Star at Agora.

I am having hard to understand how to publish the stream and i will help you out with the doc as a gratitude for you help

**Comment by Matrixbirds** [comment]
thx for your attention, we will make the rnsdk more better from your advices.
If you have any suggestion we could reopen it and talk in this issue. probably we can use another short title which would more meaningful.
