### ISSUE TITLE
Error when trying to call sendMessage function

### ISSUE THREAD

**Issue by zinzaducnm** [syanbo/react-native-agora#65]
In the 2.4.0-alpha version, i try to sendMessage in the same channel but get error like image below. Please help!
![image (1)](https://user-images.githubusercontent.com/49972775/56713113-03814880-675b-11e9-908c-1b3a6c99d1ff.png)

----------
/**
     * send stream message
     * 
     * This method sends stream message by specified uid
     * 
     * @param uid
     * @param data 
     * @returns Promise<{success, value}>
     */
    public static sendMessage(streamID: number, data: any, reliable: boolean, ordered: boolean): Promise<any> {
        return Agora.sendMessage({streamID, data, reliable, ordered});
    }

**Comment by Matrixbirds** [comment]
Please provide your device info here.

**Comment by zinzaducnm** [comment]
@Matrixbirds sorry for late reply. I cant run it in any device.

**Comment by Matrixbirds** [comment]
@zinzaducnm Okay could u provide you repo on github, then i could help reproduce and fix it.

**Comment by Matrixbirds** [comment]
if you have any update, pls provide the code snippet or project link here and reopen this issue, i will keep help u.
