### ISSUE TITLE
zOrderMediaOverlay throw Exception on Android

### ISSUE THREAD

**Issue by ensargunesdogdu** [syanbo/react-native-agora#66]
Hello,

I am using react-native-agora for a while but after upgrading to rn 0.59.x we are facing a problem which we cannot detect the reason. We just know the exception line (AgoraViewManage.java line 42)

Unfortunately problem is not occurring the devices i have and simulators. Some devices gives this exception which we could not see any visible pattern.

I want to ask, do you have any idea about this problem ? Did you hear any feedback before?

react-native-agora Version -> 2.3.3-alpha.7

-----

  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 169.52 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.7.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.2, 28.0.3
        System Images: android-22 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.5 => 0.59.5 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

**Comment by Matrixbirds** [comment]
okay thx for your issue. I will try reproduce it ASAP and i will fix in the next version.

**Comment by Matrixbirds** [comment]
@ensargunesdogdu hi dude, could u push your issue environment here that i could get more information about your situation.

**Comment by Matrixbirds** [comment]
I think that caused by your were passed a invalid component property in your side. If you have any update u could reopen the issue and paste your code snippet or project link here, that i will keep help u.

**Comment by ensargunesdogdu** [comment]
Found a real device to test.

Samsung J7 Prime -> Android 6.0.1

-- Running Code--
`
import React from "react";
import {StyleSheet, View, Dimensions, NativeModules} from 'react-native'
import {RtcEngine, AgoraView} from 'react-native-agora';

const {Agora} = NativeModules;
if (!Agora) {
    throw new Error("Agora load failed in react-native, please check ur compiler environments");
}
const {
    FPS30,
    FPS24,
    Adaptative,
    Audience,
    AudioProfileDefault,
    AudioProfileMusicStandard,
    AgoraChannelProfileLiveBroadcasting,
    AudioScenarioGameStreaming,
    AudioScenarioEducation,
} = Agora;

export default class StreamView extends React.PureComponent {
    constructor(props) {
        super(props);
        this.state = {
            broadcasterExist: false,
            visible: false,
            joinSucceed: false,
        }
    }

    componentDidMount() {
        RtcEngine.joinChannel("1");
    }

    componentWillUnmount() {
        if (this.state.joinSucceed) {
            RtcEngine.stopPreview();
            setTimeout(() => {
                RtcEngine.removeAllListeners();
                RtcEngine.leaveChannel().then((val, val2) => {
                    console.log("Leave", val, val2);
                    RtcEngine.destroy();
                });
            }, 500)
        }
    }

    componentWillMount() {
        const config = {
            appid: 'MY_API_KEY',
            channelProfile: 1,
            videoProfile: 1048,
            clientRole: Audience,
            videoEncoderConfig: {
                height: 848,
                width: 480,
                bitrate: 2,
                frameRate: FPS24,
                orientationMode: Adaptative,
            },
            audioProfile: AudioProfileMusicStandard,
            audioScenario: AudioScenarioGameStreaming,
        };
        RtcEngine.init(config);
        RtcEngine.on('firstRemoteVideoDecoded', (data) => {
            console.log('[RtcEngine] onFirstRemoteVideoDecoded', data);
        });
        RtcEngine.on('error', (data) => {
            console.log("error", data);
            if (data.error === 17) {
                this.connectAgora();
            }
        });
        RtcEngine.on('userOffline', (data) => {
            console.log('[RtcEngine] onUserOffline', data);
            if (data.uid === 1) {
                this.setState({visible: false})
            }
        });
        RtcEngine.on('joinChannelSuccess', (data) => {
            console.log('[RtcEngine] onJoinChannelSuccess', data);
            RtcEngine.startPreview();
            this.setState({
                joinSucceed: true
            })
        });
    }

    render() {
        if (this.state.joinSucceed)
            return <AgoraView
                style={styles.remoteView}
                zOrderMediaOverlay={false}
                remoteUid={MY_REMOTE_ID}
            />;
        else
            return <View/>
    }
}

const styles = StyleSheet.create({
    remoteView: {
        width: '100%',
        height: '100%',
        top: 0,
        left: 0
    }
});
`
![Screenshot_20190524-004802](https://user-images.githubusercontent.com/5063517/58289229-862f0f00-7dbe-11e9-983c-5001121372f7.png)

This code run perfect on ios Devices. However as i mentioned some android devices it throw the exception mentioned in main issue detail. When i change your code with code below. It runs without problem
`
    @ReactProp(name = "zOrderMediaOverlay")
    public void setZOrderMediaOverlay(final AgoraVideoView agoraVideoView, boolean zOrderMediaOverlay) {
        if (null != surfaceView)
            surfaceView.setZOrderMediaOverlay(zOrderMediaOverlay);
    }
`

However, Then it creates another problem. When i try to kill agoraview and black screen appears on screen as attached.
![Screenshot_20190524-005024](https://user-images.githubusercontent.com/5063517/58289237-8b8c5980-7dbe-11e9-9af6-494796f2605f.png)

**Comment by sislovesmedotcom** [comment]
+1
