### ISSUE TITLE
Not able to change the style of AgoraView

### ISSUE THREAD

**Issue by AkashDaga** [syanbo/react-native-agora#72]
**Agora View Component**   

    <AgoraView
          style={styles.peerViewStyleTest}
          zOrderMediaOverlay
          showLocalVideo={this.state.showVideo}
        />

**Style**
  peerViewStyleTest: {
    width: (width - 40) / 3,
    height: (width - 40) / 3,
    borderRadius: (width - 40) / 2,
    borderColor: theme.PAGE_BACKGROUND,
    borderWidth: StyleSheet.hairlineWidth,
    margin: 10,
    alignSelf: 'flex-end'
  }

I want the video stream should come in rounded view but I am not able to change the style of this AgoraView.

**Any suggestions will be helpful**

**Comment by syanbo** [comment]
```
<View  style={styles.peerViewStyleTest}>
<AgoraView
      style={styles.peerViewStyleTest}
      zOrderMediaOverlay
      showLocalVideo={this.state.showVideo}
    />
</View>
```


**Style add  overflow: 'hidden'**
```
peerViewStyleTest: {
width: (width - 40) / 3,
height: (width - 40) / 3,
borderRadius: (width - 40) / 2,
borderColor: theme.PAGE_BACKGROUND,
borderWidth: StyleSheet.hairlineWidth,
margin: 10,
alignSelf: 'flex-end',
 overflow: 'hidden',
}
```

**Comment by AkashDaga** [comment]
It's not working, 

**Component**
`      <TouchableOpacity style={styles.peerViewStyle}>
        <AgoraView
          style={styles.agoraViewStyle}
          zOrderMediaOverlay
          showLocalVideo={this.state.showVideo}
        />
      </TouchableOpacity>`

**Styles**
`  peerViewStyle: {
    width: (width - 40) / 3,
    height: (width - 40) / 3,
    borderRadius: (width - 40) / 2,
    borderColor: theme.PAGE_BACKGROUND,
    borderWidth: StyleSheet.hairlineWidth,
    marginLeft: 5,
    marginRight: 5,
    margin: 10,
    alignSelf: 'flex-end',
    overflow: 'hidden'
  },
  agoraViewStyle: {
    width: (width - 40) / 3,
    height: (width - 40) / 3,
    overflow: 'hidden'
  }`

if you add overflow: hidden  in both peerViewStyle and agoraViewStyle then a white circle ( as I have border color white ) we can see inside the square agora view. if we remove oveflow: 'hidden' from peerViewStyle then the circle is coming below agora view, you will be able to see the circle barely, but its coming below agora view the agora views size is not changing from square to round

**Comment by Matrixbirds** [comment]
probably u need using react devtools to inspect this component or find some ui component mix with it.

**Comment by codetheweb** [comment]
Using `{overflow: hidden, borderRadius: 8}` on a `<View/>` that wrapped the Agora video feed worked fine for me.

**Comment by LichKing-2234** [comment]
@ShelbyIB Pls use TextureView on Android.
