### ISSUE TITLE
error 回调报错 rtc.audio.enabled error: 11 是什么？

### ISSUE THREAD

**Issue by sihuayin** [syanbo/react-native-agora#73]
使用的sdk是 2.3.3
真机是： ipad
执行：
    RtcEngine.on('error', (data) => {
      console.log('[RtcEngine] onError', data);
    })

打印的data错误是 {api: "rtc.audio.enabled", result: "", error: 11}
如何修正此问题？

**Comment by Matrixbirds** [comment]
@sihuayin 
这是SDK 内部绑定到网络 Socket 失败。仅供 SDK 内部使用。可以忽略的。[docs](https://docs.agora.io/cn/Video/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_i_rtc_engine_event_handler_1_1_error_code.html#ae233e20c000611a6a709f1a5b7d0fc4e)，如果还有别的影响的话，麻烦一下集成代码。

**Comment by sihuayin** [comment]
@Matrixbirds 如此说来，这个错误就忽略也没啥影响吧。

**Comment by Matrixbirds** [comment]
@sihuayin 是的

**Comment by sihuayin** [comment]
@Matrixbirds  OK
