### ISSUE TITLE
simpleDemo not building

### ISSUE THREAD

**Issue by thomasonweb** [syanbo/react-native-agora#74]
I've downloaded the project and I am trying to get the simpleDemo to work. Here is what I have done:

1. Go to simpleDemo folder
2. run "npm install"
3. Go to simpleDemo/ios folder
4. run "pod install"
5. Try to build with xCode (or with npm run ios - either way)
6. I get this error:

<img width="866" alt="Screenshot 2019-06-14 at 17 10 16" src="https://user-images.githubusercontent.com/41863161/59519263-c23e2700-8ec7-11e9-82e2-6741d41864e4.png">

The problem is that I can't get it to work in my other project which is why I've tried running the demo but unfortunately without luck.

I'm using xCode 10.2.1

**Comment by tmjordan** [comment]
https://github.com/syanbo/react-native-agora/blob/master/docs/v2/ios.md

**Comment by Matrixbirds** [comment]
You could try to use this [one](https://github.com/agoraio-community/agora-rn-quickstart)

**Comment by Matrixbirds** [comment]
If you have any other question or you didn't build the quick start, you could reopen it.
