### ISSUE TITLE
Agora.createDataStream is not a function

### ISSUE THREAD

**Issue by spectre3ooo** [syanbo/react-native-agora#77]
I'm trying to create a data stream, but I'm getting this error:
![IMG_0051](https://user-images.githubusercontent.com/1303075/60391991-b27a3180-9ac8-11e9-88ed-fbbdd3ccab24.PNG)
When I step into `RtcEngine.createDataStream()` and inspect the `Agora` object, it does not have a `createDataStream` function.
![IMG_0050](https://user-images.githubusercontent.com/1303075/60391994-bc039980-9ac8-11e9-8f2d-64f097b94d61.JPG)

**Comment by spectre3ooo** [comment]
Nevermind.  I dug into the RCTAgora code and saw where you're wrapping it in `sendMessage()`.

**Comment by spectre3ooo** [comment]
I spoke too soon.  `sendMessage()` is creating a new stream each time.  According to the agora docs, you can only have 5 open streams.  The app is crashing when I send the 6th message with `createDataStream failed`.

**Comment by Matrixbirds** [comment]
`sendMessage` & `createDataStream` are still not recommend to use and we will deprecate `sendMessage` & `createDataStream` ASAP and Our Real Time Message react native agora wrapper will soon publish, probably this week. Which scenario u need to send message? @spectre3ooo

**Comment by spectre3ooo** [comment]
I am creating a simple card game and need to pass events and data between players.  Is there a recommended way to pass data with the current library?  Is there a beta release yet for the Real Time Message wrapper?  Thanks!

**Comment by Matrixbirds** [comment]
We will release RTM wrapper beta version this week. For now, react-native-agora wrapper not recommend to use it to pass data in your scenario.

**Comment by spectre3ooo** [comment]
Will this be a new wrapper library, or built in to the current react-native-agora library?  Do you have an example of how it will work?  Thanks!

**Comment by Matrixbirds** [comment]
@spectre3ooo  yeah, it will release to a new npm library. we will consider write simple quickstart ASAP.

**Comment by spectre3ooo** [comment]
Will it create a data stream on the channel you're currently in, or will it be completely separate from the video channel?

**Comment by Matrixbirds** [comment]
We have already release the [agora-react-native-rtm](https://github.com/AgoraIO/RN-SDK-RTM) and there is an example [here](https://github.com/AgoraIO/RN-SDK-RTM/blob/master/examples/chatsapp/README.md)
