### ISSUE TITLE
Could not invoke RCTAgora.init

### ISSUE THREAD

**Issue by ndcollins** [syanbo/react-native-agora#79]
Receiving the following error message within the Android emulator.
[https://files.slack.com/files-pri/T265K8ZT9-FL9AWTWKT/screen_shot_2019-07-16_at_3.28.49_am.png](url)

Using React Native 0.59.0 and React-Native-Agora

**Comment by Matrixbirds** [comment]
Could you upload the screenshot here ? Probably u didn't pass correct `appid` when invoke `init` method.

**Comment by ndcollins** [comment]
@Matrixbirds @syanbo  The issue I'm running into is that the Agora library pulled in by gradle is missing the code for supporting the Intel x86 chipset, which is what is used by the Android emulator.

**Comment by Matrixbirds** [comment]
@ndcollins Our Agora native SDK support the x86 CPU arch, probably ur set some abi filter in  gradle script which effect the building step that issue your emulator cannot reach the x86 abi. 
You can try to build with this [quick start](https://github.com/agoraio-community/agora-rn-quickstart) and find the key different from your gradle configuration.

**Comment by Matrixbirds** [comment]
Can't reproduce it and it caused by your deploy environment. Please read the docs or just try our [quick start](https://github.com/agoraio-community/agora-rn-quickstart)
