### ISSUE TITLE
Android从进程中杀掉  onUserOffline  没有回调

### ISSUE THREAD

**Issue by iamlion** [syanbo/react-native-agora#8]
我是  ios  和 android 通话，ios 从进程中划掉onUserOffline有回调，android 从进程中划掉没有回调。

                RtcEngine.eventEmitter({
                    onFirstRemoteVideoDecoded: onFirstRemoteVideoDecoded,
                    onUserOffline: (data) => {
                       //安卓进程杀死没有回调这里
                        Alert.alert(`${123456}`);
                    },
                    onJoinChannelSuccess: onJoinChannelSuccess,
                    onUserJoined: onUserJoined,
                    onError: onError,
                    onWarning: onWarning,
                    onLeaveChannel: (data) => {
                        RtcEngine.removeEmitter();
                        RtcEngine.destroy();
                        agoraClient = false;
                        onLeaveChannel && onLeaveChannel(data)
                    }
                })

**Comment by syanbo** [comment]
这个回调是用户离开触发的， 你的意思是  iOS 上的用户划掉进程  在Android上onUserOffline没有收到回调通知吗？

**Comment by iamlion** [comment]
安卓划掉ios没收到

**Comment by Matrixbirds** [comment]
你可以尝试一下最新版本2.3.3-alpha。

**Comment by mzyisbest** [comment]
me too
