### ISSUE TITLE
Is there any possibility of saving video from Agora

### ISSUE THREAD

**Issue by HemanthSurimani** [syanbo/react-native-agora#81]
Is there any possibility of saving video from Agora 

@Matrixbirds

**Comment by Matrixbirds** [comment]
Which scenario do you want to save the video and save it into file or some general form? The current latest version is not support save video.

**Comment by HemanthSurimani** [comment]
Thanks For your Quick reply.
I want to save video into both cases
@Matrixbirds

**Comment by Matrixbirds** [comment]
@HemanthSurimani okay, i will schedule it on the roadmap in the next release.

**Comment by Matrixbirds** [comment]
@HemanthSurimani 
During my long time workaround, i found it a little bit difficult to implementation. 
1. Capture the video & audio raw data: Fortunately, the [agora.io C++ SDK](https://docs.agora.io/en/Interactive%20Broadcast/API%20Reference/cpp/index.html#rawvideo) enables to capture the raw data. But the react-native need using main thread to handle jsBridge event dispatch to the javascript layer, Probably need implement the native thread scheduler to subscribe the media stream.
2. Remux: You can capture the yuv video data and audio data from sdk event, and therefore we need to somecase like check good the data frame & timestamps and resolve the **synchronization** problem, the codec processing is also a **scheduling problem**, when your mobile devices transmit from active to inactive state, it is really have so many edge case need to consider and test.

If u want to saving video from agora services. For the convenience, we recommend you using [cloud recording](https://docs.agora.io/en/cloud-recording/product_cloud_recording%20?platform=Linux)
