### ISSUE TITLE
Screen sharing not working from WebSDK to React native SDK

### ISSUE THREAD

**Issue by harshalijain** [syanbo/react-native-agora#82]
Hi,
I am trying to integrate Agora SDK for React native, and I am facing some issues while sharing screen from my desktop app which uses Agora WebSDK to my Android mobile using React native SDK. 
When I start sharing my screen, onUserJoined in mobile SDK gets invoked, but the uid is sometimes a negative value and no screen data comes for that uid. But if uid is positive, screen sharing works perfectly.
Can you please provide any insight or solutions for above issue!

**Comment by Matrixbirds** [comment]
@harshalijain 
I think it is websdk integrate problem.You can pass a positive number for streamID when u call `createStream`, so that wouldn't be negative anymore.

**Comment by harshalijain** [comment]
The streamID passed from WebSDK is always positive, but somehow the uid received on Mobile SDK is different than that value, it is a random negative number. Is their any possible explanation regarding this issue.

**Comment by Matrixbirds** [comment]
It seems your passed number from WebSDK is too large that caused signed integer overflow in Mobile SDK. Our Mobile SDK used signed integer for `uid` which is same things as `streamID`.

**Comment by Himanshu557** [comment]
Agora WebSDK allows us to set uId as a 32-bit unsigned integer with a value ranging from 1 to (2^32-1).We want to fix the userId of screen sharing user to make it easier from implementation and identification perspective.So we are now passing the uId of screen sharing as 4294967295 i.e. 2^32 -1.
Is it possible to support this uId in Mobile SDK?

**Comment by Matrixbirds** [comment]
this issue already fix in the 2.4.1-alpha.3

**Comment by mmatheusmmiguel** [comment]
Hello harshalijain, can you tell me what function you are using for screen sharing on Mobile?
