### ISSUE TITLE
React-Native 0.59 upgradation issues

### ISSUE THREAD

**Issue by harshalijain** [syanbo/react-native-agora#83]
I upgraded my react-native version to "^0.59.10" and react version to "^16.8.6". After installing all node modules, getting the error
```
npm ERR! peer dep missing: react@16.8.3, required by react-native@0.59.10
npm ERR! peer dep missing: react@16.3.1, required by react-native-agora@2.4.1-alpha.2
```

I build and install the application and ran into following crash
```
Error: Exception in HostObject::set: Unable to put on NativeModules: Operation unsupported
    
    This error is located at:
        in t
        in RCTView
        in RCTView
        in t, stack:
```
Can you please provide some workaround to resolve this issue.

**Comment by Matrixbirds** [comment]
It seems babel or js runtime mismatch the problem.
