### ISSUE TITLE
listener can not be destroyed! [BUG report]

### ISSUE THREAD

**Issue by guopeng1994** [syanbo/react-native-agora#87]
version:2.4.1-alpha.3
questions: 目前的事件监听器一旦监听一个事件后，便无法移除掉。我看了下源代码，因为removeAllListeners和off 都已经deprecated，所以只能调用destroy来销毁，但是实际在调用后，虽然原生端确实stopObserving和destroy了，但是在RN端的下次重新初始化实例和事件监听器时，就会有在同一种事件类型中收到个回调，如下图：
![image](https://user-images.githubusercontent.com/30316642/63149951-1be1df80-c038-11e9-8b2c-710ffc91f701.png)

上图中joinChannelSuccess只有一次，是因为我手动改了源代码，如下：
![image](https://user-images.githubusercontent.com/30316642/63150025-46cc3380-c038-11e9-9ec1-3967a5c2e403.png)
![image](https://user-images.githubusercontent.com/30316642/63150554-a971ff00-c039-11e9-9514-33287782c7bd.png)

这样就相当于我在页面退出时移除了这个监听器，然后在下次重新进入这个页面的时候就回重新常见这个监听器了，所以看起来似乎仅存的destory并没有将RN端的listener给注销掉，导致回调了几次

如何复现：创建一个单独的页面来进行视频聊天（比如说匹配成功后的音视频聊天），在页面didmount时，初始化实例和一系列监听器，unmount时，销毁实例（只有destory方法），第一次聊天时，一切正常，第二次跳转到该页面建立聊天时，其中的事件监听器会回调2次，继续关闭页面（销毁一切），第三次会回调3次。。以此类推

**Comment by Matrixbirds** [comment]
麻烦提供一下复现的设备和环境 以及 react-native info

**Comment by guopeng1994** [comment]
@Matrixbirds 

![image](https://user-images.githubusercontent.com/30316642/63208852-27063f80-c10c-11e9-841b-7f52b2a06ea7.png)

任意两个模拟器，因为我这边是ios切Xcode使用的是11 beta2 ，所以跑的模拟器是iOS 13.0的

**Comment by Matrixbirds** [comment]
感谢反馈我这里复现了，是之前理解错了 这里是有react native用到的NativeEventEmitter，我这里已经在主版本里取消了。下一个版本会发这个功能。

**Comment by guopeng1994** [comment]
OK
