### ISSUE TITLE
onUserJoined listener not triggered on iOS

### ISSUE THREAD

**Issue by tmjordan** [syanbo/react-native-agora#88]
I'm trying to make a video call between my iPhone 8 and my Samsung Galaxy S6 Edge.
The Samsung detects when a user joined the channel but doest not on the iPhone. I don't know why?

Environment:
React Native 0.59.8
react-native-agora:  2.8.0-alpha-1

**Comment by Matrixbirds** [comment]
@tmjordan 
Can you reproduce this issue on the [quick start](https://github.com/AgoraIO-Community/Agora-RN-Quickstart)

**Comment by tmjordan** [comment]
i can't install it on iOS, many build errors. I will try later, i'm a little busy right now.
But it seems to work well on android

**Comment by Matrixbirds** [comment]
Could u please paste the build errors here ? that I could help u to fixed the issue. @tmjordan

**Comment by tmjordan** [comment]
![image](https://user-images.githubusercontent.com/27443995/63590704-e9426480-c5ac-11e9-8a38-0324cdd00a55.png)

**Comment by Matrixbirds** [comment]
It seems you did duplicate link in your iOS project. In the current sdk, you didn't need add `RCTAgora.xcodeproj` manually, the `react-native link react-native-agora` will automatically setup the sdk correct. So let's do remove `RCTAgora.xcodeproj` from your `library` xcode project first, then run link command, and try to rebuild it again.

**Comment by tmjordan** [comment]
I did nothing, but `RCTAgora.xcodeproj` was already there after linking the project using `react-native link react-native-agora`.
I tried to remove `RCTAgora.xcodeproj`, and link again (even if it says that the project is already linked). After doing that, now i have this error :
![image](https://user-images.githubusercontent.com/27443995/63788336-955db580-c8f5-11e9-84c1-43753e8736dd.png)

I want to say also, that there is a problem with RCTBridgeModule, but i fixed by following this workaround: https://stackoverflow.com/questions/41663002/react-rctbridgemodule-h-file-not-found

I will try to test with a new project

**Comment by tmjordan** [comment]
@Matrixbirds I managed to make it to work, by creating a new project which uses autolinking with the last version 
of react native. And the video call works very well, so my problem is probably related to my code i think, i'll check it again later.
I think we should update the quickstart project to make it simple to test and also update the readme according to the last version of the lib.
