### ISSUE TITLE
 _reactNativeAgora.RtcEngine.eventEmitter is not a function

### ISSUE THREAD

**Issue by rizwan92** [syanbo/react-native-agora#89]
my dependencies

 ```
 "axios": "^0.19.0",
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-agora": "^2.8.0-alpha.1",
    "react-native-webrtc": "^1.75.0"
```
my App.js is this
https://gist.github.com/rizwan92/0afdcbe7402eb2c3311cedfbbdada865
my Live.js is this
https://gist.github.com/rizwan92/6edbb346b03bc6295abfdadfbf96ebcf 

while running app  it runs Live.js and thrown an error 

```
 TypeError: _reactNativeAgora.RtcEngine.removeEmitter is not a function

This error is located at:
    in RNAgoraExample (at App.js:69)
    in App (at renderApplication.js:40)
    in RCTView (at View.js:35)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:35)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:39)
 
```

```
Uncaught TypeError: TypeError: _reactNativeAgora.RtcEngine.removeEmitter is not a function

This error is located at:
    in RNAgoraExample (at App.js:69)
    in App (at renderApplication.js:40)
    in RCTView (at View.js:35)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:35)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:39)
```

**Comment by Matrixbirds** [comment]
`removeEmitter` is deprecated from the `2.3.3-alpha.5`, If you r facing the event handler still remaining issue that I m already fixed in the hotfix tag. You can just renpm install from github `2.8.0-alpha.1.hotfix`.In this fixed version, u just need to invoke destroy when you don't want to subscribe the `react-native-agora` event.

**Comment by Matrixbirds** [comment]
We already released `2.8.0-alpha.2`. you just need to upgrade to this version.

**Comment by rizwan92** [comment]
do you have latest react native code sample so I can understand the API how to integrate into react native? i am using this code which is throwing an error with latest  2.8.0-alpha.2
```
RtcEngine.eventEmitter({
      onFirstRemoteVideoDecoded: data => {
        console.log(data);
        // 有远程视频加入 返回重要的  uid  AgoraView 根据uid 来设置remoteUid值
        const { remotes } = this.state;
        const newRemotes = [...remotes];

        // 存在断网重连导致回调多次该方法的情况，已加入过的远程视频不再重复添加
        if (!remotes.find(uid => uid === data.uid)) {
          newRemotes.push(data.uid);
        }
        this.setState({ remotes: newRemotes });
      },
      onUserOffline: data => {
        console.log(data);
        // 有人离开了！
        const { remotes } = this.state;
        const newRemotes = remotes.filter(uid => uid !== data.uid);
        this.setState({ remotes: newRemotes });
      },
      onJoinChannelSuccess: data => {
        // 加入房间成功
        console.log(data);
        // 开启摄像头预览
        RtcEngine.startPreview();

        this.setState({
          isJoinSuccess: true
        });
      },
      onAudioVolumeIndication: data => {
        // 声音回调
        console.log(data, '-----');
      },
      onUserJoined: data => {
        console.log(data);
        // 有人来了!
      },
      onError: data => {
        console.log(data);
        // 错误!

        if (data.err === 17) {
          RtcEngine.leaveChannel();
          RtcEngine.destroy();
        }

        const { onCancel } = this.props;
        onCancel(data.err);
      }
    });
```

**Comment by rizwan92** [comment]
thanks man I ran it finally
![1566469010984](https://user-images.githubusercontent.com/19162978/63507192-cf454b00-c4f4-11e9-9990-84dc5c67e656.JPEG)


I have quick questions.
1. how can I someone else will join this call?
2. I want to build an application where I want to connect with multiple users. but not at one time instead of one by one. suppose that I am connected with one person, at the same time another person wants to join, then how can I stop him to join like I am busy with someone else.
is there any properties in on joining call back so I can see how many entities are connected right there so i could stop third person to join the call

**Comment by Matrixbirds** [comment]
@rizwan92 I think probably you need some **real-time messaging services** like [agora-react-native-rtm](http://github.com/agoraio/agora-react-native-rtm) to control the video & audio call. For now, we have a very simple quick start about [chat message apps](https://github.com/AgoraIO/agora-react-native-rtm/tree/master/examples/chatsapp)

**Comment by varunsdcet** [comment]
@rizwan92 on my app voice is not coming on Video Call .

**Comment by Matrixbirds** [comment]
@varunsdcet  If you have any integration question. You can upload your demo code to Github repo and refer it here, i will check it ASAP.
