### ISSUE TITLE
android 第一次通话完毕后  再次进入直接报错

### ISSUE THREAD

**Issue by iamlion** [syanbo/react-native-agora#9]
![image](https://user-images.githubusercontent.com/4600033/32211090-ecac5d16-be4b-11e7-9097-f0a551573e5c.png)

安卓机第一次呼叫结束后退出   

RtcEngine.removeEmitter();
RtcEngine.destroy();

再次呼叫对方进入通话界面就报错了。

**Comment by syanbo** [comment]
@iamlion 查看新的demo问题已解决
