### ISSUE TITLE
How to differentiate Video  and Video Broadcasting

### ISSUE THREAD

**Issue by HemanthSurimani** [syanbo/react-native-agora#92]
Video Calling property works fine.

I am trying to add Live Video Broadcasting to my react native application , 

right now there are no properties for differentiate Video Call and Live Video Broadcasting

Please Help me!

@Matrixbirds

**Comment by Matrixbirds** [comment]
In Live broadcasting mode, you have two roles params need be passed with setClientRole function,
If you set audience role when u join channel, u just can receive audio or video data, instead the broadcast role allows you both send & receive audio or video data
