### ISSUE TITLE
Not able to change location of my screen with caller's screen location

### ISSUE THREAD

**Issue by awesomesince96** [syanbo/react-native-agora#94]
Want to change the location of my screen and person calling me's screen. So here Person A is video calling me. The Black screen you see if my screen (It working, it's just I had something in front of the camera) and Keyboard screen on the corner is Person A's screen. Instead what should happen is  my screen (black screen) should be in corner and Person A's screen should be in front.

![image](https://user-images.githubusercontent.com/19352183/64908684-6a36dc80-d6d1-11e9-89b2-35ba5c8ea464.png)

![agora-error](https://user-images.githubusercontent.com/19352183/64908587-24c5df80-d6d0-11e9-8677-26336b8fe6fb.jpg)

Here you can find the code of video call library implementation, Here's the render function:

    render() {
        this.secondsRemaining = this.secondsRemaining + this.props.addedTime
        const {
            isMute,
            isSpeaker,
            isCameraTorch,
            disableVideo,
            isHideButtons,
            remotes,
            isJoinSuccess,
            visible,
            isTimerStart
            ,
        } = this.state;

        return (
            <TouchableOpacity
                activeOpacity={1}
                style={styles.container}
            >
                <AgoraView style={styles.localView} showLocalVideo={false}/>
                           
                {!isHideButtons ?
                    <View style={{ backgroundColor: 'transparent',position:'absolute',bottom:0,left:0,right:0 }}>
                        {    
                            isTimerStart       
                            ? (
                                <TimerCountdown
                                    initialSecondsRemaining={this.secondsRemaining}
                                    onTick={(secondsRemaining)=> {this.secondsRemaining = secondsRemaining;
                                      this.duration += 1}}
                                    onTimeElapsed={()=> this.onTimerElapsed()}
                                    allowFontScaling={true}
                                    style={{
                                        fontSize: 20,
                                        color: 'white',
                                        alignSelf: 'center',
                                        // marginTop: 10,
                                    }}
                                />
                            ) : null     
                        }   
                        
                      
                        <View style={styles.bottomView}>
                            <OperateButton   
                                onPress={()=>this.handlerMuteAllRemoteAudioStreams()}
                                source={isMute ? require('../../images/icon_muted.png') : require('../../images/btn_mute.png')}
                            />
                            {this.props.showAdd?
                                <AddTimeForDoctorButton
                                onPress={()=>this.addTime()}
                            />
                            :<Text></Text>

                             }

                             {/* <OperateButton
                                onPress={()=>this.start()}
                                source={require('../images/btn_video.png')}
                        /> 
                         */}

                            <OperateButton
                                onPress={this.handlerSwitchCamera}
                                source={require('../../images/btn_switch_camera.png')}
                            />

                             
                        </View>
                       
                        
                        <OperateButton
                            style={{alignSelf: 'center',}}
                            onPress={()=>this.confirmEndingCall()}
                            imgStyle={{width: 60, height: 60}}
                            source={require('../../images/btn_endcall.png')}
                        />
                    </View>:null
                    }
                <View style={styles.absView}>
                    <View >
                            {!visible ?
                    <View style={styles.videoView}>         
                        {remotes.map((v, k) => {
                            return (
                                <TouchableOpacity   
                                    activeOpacity={1}
                                    onPress={() => this.onPressVideo(v)}
                                    key={k}       
                                >
                                    <AgoraView
                                        style={styles.remoteView}
                                        zOrderMediaOverlay={true}
                                        remoteUid={v}
                                    />
                                     </TouchableOpacity>
                            )
                        })}                       
                    </View> : <View style={styles.videoView}/>
                    }  
                    </View>
                </View>

                <Modal            
                    visible={visible}
                    presentationStyle={'fullScreen'}
                    animationType={'slide'}
                    onRequestClose={() => {}}
                >
                    <TouchableOpacity
                        activeOpacity={1}
                        style={{flex: 1}}
                        onPress={() => this.setState({
                            visible: false,
                        })}
                    >
                        <AgoraView
                            style={{flex: 1}}
                            zOrderMediaOverlay={true}
                            remoteUid={this.state.selectUid}
                        />
                    </TouchableOpacity>
                </Modal>
            </TouchableOpacity>
        );
    }

**Comment by Matrixbirds** [comment]
I think probably you need install react-native-debugger or some layout debug tool to help you inspect your current layout. In the below code snippet, you set a local **AgoraView**  the inside TouchableOpacity, so your main view will always use the local view as the fullscreen view.

**Comment by Matrixbirds** [comment]
If u still have any problem about it, please reopen the issue and provide your demo apps on Github and link it here. I will check on it ASAP.
