### ISSUE TITLE
希望官方增加一份 SDK 2.x 手动安装指南

### ISSUE THREAD

**Issue by hiscc** [syanbo/react-native-agora#95]
### 希望增加一份 SDK 2.x 手动安装指南
用 Pod 管理依赖的方式是大势所趋，但目前社区中的大部分库依然没有支持 Pod 安装。我在升级自己的项目为 Pod 依赖管理时就出现了多个库还没有更新 Pod 依赖的情况，导致升级失败。

希望官方出一份简单的手动安装指南来帮助开发者平滑过渡这个阶段，谢谢🙏

**Comment by Shealtiel-Li** [comment]
您好，您目前是在用pods进行管理吗？

**Comment by hiscc** [comment]
> 您好，您目前是在用pods进行管理吗？

目前还没有，现在依然在用 0.59 的版本
