### ISSUE TITLE
Video is very blurred from web to mobile

### ISSUE THREAD

**Issue by prameetc** [syanbo/react-native-agora#96]
I was on a video call, the video quality on web is very good, but on mobile the video quality is very bad when call is started from web. Mobile to Mobile works fine.

**Comment by varunsdcet** [comment]
Hi Please give sample . On my app voice is not coming

**Comment by Matrixbirds** [comment]
Please provide your runtime parameters here.

**Comment by prameetc** [comment]
@Matrixbirds 

const localStream = AgoraRTC.createStream(
       ``` {streamID: uid, 
            audio: audioEnabled, 
            video: videoEnabled,          
          cameraId, 
          microphoneId, 
          screen: false, 
          width:720, 
          height:1280, 
          aspectRatio:3.7777778,
          audioProcessing:{
            AEC:true, AGC:false,ANS:true
          }});
      localStream.setVideoProfile('1080p_5');
      localStream.setAudioProfile('high_quality')```

I change the `setVideoProfile` value but it doesn't improve

**Comment by Matrixbirds** [comment]
@prameetc Can u reproduce the case on this [demo](https://webdemo.agora.io/agora-web-showcase/examples/Agora-Web-Tutorial-1to1-Web/)? If you could please provide your channelName here.

**Comment by prameetc** [comment]
@Matrixbirds Thanks I will check this out. Do you have the code sample for that demo?

**Comment by Matrixbirds** [comment]
@prameetc This is web demo's sample [project](https://github.com/AgoraIO/Basic-Video-Call/tree/master/One-to-One-Video/Agora-Web-Tutorial-1to1-Webpack)
