### ISSUE TITLE
Build Error on RN 0.60 IOS

### ISSUE THREAD

**Issue by erickbank** [syanbo/react-native-agora#98]
I can`t build the app @ rn 0.60 , i ve downloaded the package using npm , and every build i make , returns this error, any solution ?

![Captura de Tela 2019-09-18 às 11 34 45](https://user-images.githubusercontent.com/27246190/65158255-69bb8000-da08-11e9-848f-e4e859d59a57.png)

**Comment by Matrixbirds** [comment]
Our react-native-agora module is just a native module adapter for react-native it is not same as AgoraRTCSDK that need agora rtc compatible browser or webView. If you r using AgoraRTCSDK on webView or browser, please check the [compatible list](https://docs.agora.io/en/Interactive%20Broadcast/start_live_web?platform=Web)
